#!/bin/sh

# if app not exist
if [ ! -f /bin/zebra ] || [ ! -f /bin/ripd ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t dynroute"

start() {
    eval `nvram_buf_get 2860 RIPEnable Password Login HostName`
    if [ "$RIPEnable" = "1" ] && [ -f /bin/zebra ]; then
	# confog and start zebra
	printf "hostname $HostName
    		password $Password
    		enable password Admin
    		log syslog" > /etc/zebra.conf
	$LOG "Starting ZEBRA"
	zebra -u $Login -g $Login -d -f /etc/zebra.conf
    fi
    if [ "$RIPEnable" = "1" ] && [ -f /bin/ripd ]; then
	# confog and start ripd
	printf "hostname $HostName
    		password $Password
    		enable password Admin
    		log syslog
    		router rip
    		version 2" > /etc/ripd.conf
	$LOG "Starting RIPD"
	ripd -u $Login -g $Login -f /etc/ripd.conf -d
    fi
}

stop() {
    pid=`pidof zebra`
    if [ "$pid" != "" ]; then
	$LOG "Stopping ZEBRA"
	killall -q zebra
	killall -q -SIGKILL zebra
    fi
    pid=`pidof ripd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping RIPD"
	killall -q ripd
	killall -q -SIGKILL ripd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
