#!/bin/sh

# if app not exist
if [ ! -f /bin/zebra ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t zebra"

start() {
    eval `nvram_buf_get 2860 RIPEnable Password Login HostName`
    if [ "$RIPEnable" = "1" ]; then
	printf "hostname $HostName
    		password $Password
    		enable password Admin
    		log syslog" > /etc/zebra.conf
	$LOG "Starting ZEBRA"
	zebra -u $Login -g $Login -d -f /etc/zebra.conf
    fi
}

stop() {
    pid=`pidof zebra`
    if [ "$pid" != "" ]; then
	$LOG "Stopping ZEBRA"
	killall -q zebra
	killall -q -SIGKILL zebra
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
