#!/bin/sh

# if app not exist
if [ ! -f /bin/ripd ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t ripd"

start() {
    eval `nvram_buf_get 2860 RIPEnable Login`
    if [ "$RIPEnable" = "1" ] && [ -f /etc/ripd.conf ]; then
	$LOG "Starting RIPD"
	ripd -u $Login -g $Login -f /etc/ripd.conf -d
    fi
}

stop() {
    pid=`pidof ripd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping RIPD"
	killall -q ripd
	killall -q -SIGKILL ripd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
