#!/bin/sh

# if app not exist
if [ ! -e /bin/bndstrg ]; then
    exit 0
fi


# get params
. /etc/scripts/global.sh

LOG="logger -t bndstr"

start() {
    get_param
    if [ "$BandSteering" != "" ] && [ "$BandSteering" != "0" ] ; then
	if [ "$RadioOn" = "1" ] && [ "$RadioOnINIC" = "1" ] && [ "$SSID1" = "$SSID1INIC" ]; then
	    $LOG "Starting bandsteering daemon"
	    bndstrg &
	else
	    $LOG "For bandsteering work are required enable all bands support and identical SSID for 2.4GHz and 5GHz modules. Please change it and restart."
	fi
    fi
}

get_param() {
    eval `nvram_buf_get 2860 RadioOn RadioOnINIC BandSteering SSID1 SSID1INIC`
}

stop() {
    pid=`pidof bndstrg`
    if [ "$pid" != "" ]; then
	$LOG "Stopping bandsteering roaming daemon"
	killall -q bndstrg
	killall -q -SIGKILL bndstrg
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
esac
