#!/bin/sh

# if app not exist
if [ ! -f /bin/ralinkiappd ]; then
    exit 0
fi


# get params
. /etc/scripts/global.sh

LOG="logger -t apd"

start() {
    get_param
    if [ "$FastRoaming" = "1" ] && [ "$FtSupport" != "" ] && [ "$FtSupport" != "0;0;0;0" ] ; then
	$LOG "Starting iappd roaming daemon"
	# ethernet if - lan_if
	# wlan if for recive data - standalone if or bridge interface
	# wlan if for ioctl - standalone if
	ralinkiappd -e "$lan_if" -w "$lan_if" -wi "$first_wlan_root_if"
    fi
}

get_param() {
    eval `nvram_buf_get 2860 FastRoaming FtSupport`
}

stop() {
    pid=`pidof ralinkiappd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping  iappd roaming daemon"
	killall -q ralinkiappd
	killall -q -SIGKILL ralinkiappd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
