#!/bin/sh

# if app not exist
if [ ! -e /bin/radiusd ]; then
    exit 0
fi


# get params
. /etc/scripts/global.sh

LOG="logger -t apd"

start() {
    get_param
    if [ "$radius_srv_enabled" = "1" ] || [ "$radius_srv_enabled" = "2" ]; then
	# Generate password file.
	configured=0
	echo > $AUTHFILE
	for usernum in `seq 0 $radius_srv_user_num`; do
	    radius_srv_user=`nvram_get 2860 radius_srv_user"$usernum"`
	    radius_srv_pass=`nvram_get 2860 radius_srv_pass"$usernum"`
	    if [ "$radius_srv_user" != "" ] && [ "$radius_srv_pass" != "" ]; then
		    printf "$radius_srv_user Cleartext-Password := "$radius_srv_pass"\n" >> $AUTHFILE
		    configured=1
	    fi
	done
	if [ "$configured" = "1" ]; then
	    $LOG "Starting radius daemon"
	    radiusd &
	fi
    fi
}

get_param() {
    eval `nvram_buf_get 2860 radius_srv_enabled radius_srv_user_num`
    AUTHFILE="/etc/raddb/mods-config/files/authorize"
}

stop() {
    pid=`pidof radiusd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping  radius roaming daemon"
	killall -q radiusd
	killall -q -SIGKILL radiusd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
esac
