#!/bin/sh

# if app not exist
if [ ! -e /bin/lld2d ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

LOG="logger -t lldpd"

start() {
    get_param
    if [ "$lldpdEnabled" = "1" ]; then
	$LOG "Starting LLDPD"
	mkdir -p /etc/lldpd.d
	DEVNAME=`grep "DEVNAME" < /etc/version | awk {' print $3 '} | sed s'@"@@'g`
	VERSIONPKG=`grep "VERSIONPKG" < /etc/version | awk {' print $3 '} | sed s'@"@@'g`
	HOSTNAME=`hostname`
        lldpd -s -e -f -M2 -S "$DEVNAME $VERSIONPKG $HOSTNAME" -L/sbin/lldpcli
    fi
}

get_param() {
    eval `nvram_buf_get 2860 lldpdEnabled`
}

stop() {
    pid=`pidof lldpd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping LLDPD"
	killall -q lldpd
	killall -q -SIGKILL lldpd
    fi
    pid=`pidof lldpcli`
    if [ "$pid" != "" ]; then
	$LOG "Stopping LLDPD cli"
	killall -q lldpcli
	killall -q -SIGKILL lldpcli
    fi
    rm -f /var/run/lldpd.socket
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
