#!/bin/sh

# if app not exist
if [ ! -e /bin/cwmpd ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

LOG="logger -t cwmpd"

start() {
    get_param

    # cwmp allways use url by dhcp if exist
    # only if ISP not send url by dhcp use static mode
    if [ "$cwmpdEnabled" = "1" ] && [ "$acs_url" = "" ]; then
	( # send to background
	$LOG "Starting CWMPD"
	cwmpd
	) & # send to background
    elif [ "$cwmpdEnabled" != "0" ] && [ "$acs_url" != "" ]; then
	( # send to background
	$LOG "Starting CWMPD"
	cwmpd cwmp:acs_url="$acs_url"
	) & # send to background
    fi
}

get_param() {
    export DEVNAME=`grep "DEVNAME" < /etc/version | awk {' print $3 '} | sed s'@"@@'g`
    export VERSIONPKG=`grep "VERSIONPKG" < /etc/version | awk {' print $3 '} | sed s'@"@@'g`
    if [ -e /tmp/acsurl ]; then
	acs_url=`tail -qn1 /tmp/acsurl`
    fi
}

stop() {
    pid=`pidof cwmpd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping CWMPD"
	killall -q cwmpd
	killall -q -SIGKILL cwmpd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
esac
