#!/bin/sh

# if app not exist
if [ ! -f /bin/chilli ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

LOG="logger -t ChilliSpot"
PARAMS="net dhcpstart dhcpend dynip dns1 dns2 domain \
	radiuslisten radiusserver1 radiusserver2 radiussecret radiusnasid radiusnasip radiuslocationid radiuslocationname radiusnasporttype coaport lease \
	uamserver uamhomepage uamsecret uamallowed macallowed"

BOOLPARAMS="coanoipcheck uamanyip uamanydns"

start() {
    if [ "$hotspot" = "on" ]; then
	$LOG "Starting ChilliSpot"
	get_params
	modprobe -q tun
	chilli $DEBUG $PARLINE &
	#wget http://tech.hotspotsystem.com/up.php?mac=`echo $LAN_MAC_ADDR|sed s/:/-/g`\&nasid=$chilli_radiusnasid\&os_date=coova -O /tmp/remote.sh
    fi
}

stop() {
    pid=`pidof chilli`
    if [ "$pid" != "" ]; then
	$LOG "Stopping ChilliSpot"
	killall -q chilli
	killall -q -SIGKILL chilli
    fi
}

get_params() {
    eval `nvram_buf_get 2860 chilli_debug chilli_radiusnasid`
    if [ "$chilli_debug" = "1" ]; then
	DEBUG="-d -f -F --debugfacility=7 --logfacility=7 --loglevel=7"
    else
	DEBUG="--logfacility=7 --loglevel=7"
    fi
    PARLINE="--dhcpif $lan_if"
    for i in $PARAMS; do
	val=`nvram_get 2860 chilli_$i`
	[ -n "$val" ] && PARLINE="$PARLINE --$i $val"
    done
    for i in $BOOLPARAMS; do
	val=`nvram_get 2860 chilli_$i`
	[ "$val" = "on" ] && PARLINE="$PARLINE --$i"
    done
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
