#!/bin/sh

# if app not exist
if [ ! -f /bin/nodogsplash ]; then
    exit 0
fi

LOG="logger -t nodogsplash"

# get params
. /etc/scripts/global.sh

start() {
    get_param
    if [ "$nodogsplash_enable" = "1" ]; then
	$LOG "Starting SNMPD"
	printf "
	    GatewayInterface $lan_if
	    GatewayAddress $lan_ipaddr
	    GatewayName $HostName
	" > $CONF
	cat $CTMP >> $CONF
	nodogsplash -s &
    fi
}

get_param() {
    eval `nvram_buf_get 2860 nodogsplash_enable`
    CONF="/etc/nodogsplash/nodogsplash.conf"
    CTMP="/etc/nodogsplash/nodogsplash.conf.template"
}

stop() {
    pid=`pidof nodogsplash`
    if [ "$pid" != "" ]; then
	$LOG "Stopping SNMPD"
	killall -q nodogsplash
	killall -q -SIGKILL nodogsplash
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
