#!/bin/sh

# if app not exist
if [ ! -f /bin/nodogsplash ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

if [ "$OperationMode" = "0" ]; then
    exit 0
fi

LOG="logger -t nodogsplash"
PARAMS="GatewayIPRange RedirectURL MaxClients ClientIdleTimeout ClientForceTimeout \
AuthenticateImmediately MACMechanism BlockedMACList AllowedMACList TrustedMACList \
PasswordAuthentication Password UsernameAuthentication Username PasswordAttempts"

start() {
    get_param
    if [ "$nodogsplash_enable" = "1" ]; then
	$LOG "Starting Nodogsplash"
	echo "GatewayInterface $lan_if"		>  $CONF
	echo "GatewayAddress $lan_ipaddr"	>> $CONF
	echo "GatewayName $HostName"		>> $CONF
	for i in $PARAMS; do
	    val=`nvram_get 2860 nodog_$i`
	    [ -n "$val" ] && echo "$i $val"	>> $CONF
	done
	cat $CTMP >> $CONF
	nodogsplash -s &
    fi
}

get_param() {
    eval `nvram_buf_get 2860 nodogsplash_enable`
    CONF="/etc/nodogsplash/nodogsplash.conf"
    CTMP="/etc/nodogsplash/nodogsplash.conf.template"
}

stop() {
    pid=`pidof nodogsplash`
    if [ "$pid" != "" ]; then
	$LOG "Stopping Nodogsplash"
	killall -q nodogsplash
	killall -q -SIGKILL nodogsplash
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
