#!/bin/sh

# if app not exist
if [ ! -e /bin/snmpd ]; then
    exit 0
fi

LOG="logger -t snmpd"

start() {
    get_param
    if [ "$snmpd" != "" ] && [ "$snmpd" != "0" ]; then
	if [ "$snmpdcommunity" = "" ]; then
	    snmpdcommunity="$HostName"
	fi
	$LOG "Starting SNMPD"
	snmpd -c "$snmpdcommunity" &
    fi
}

get_param() {
    eval `nvram_buf_get 2860 snmpd HostName snmpdcommunity`
}

stop() {
    pid=`pidof snmpd`
    if [ "$pid" != "" ]; then
	$LOG "Stopping SNMPD"
	killall -q snmpd
	killall -q -SIGKILL snmpd
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
esac
