#!/bin/sh

# if app not exist
if [ ! -f /bin/irqbalance ]; then
    exit 0
fi

#include global config
. /etc/scripts/global.sh

LOG="logger -t irqbalance"

start() {
    get_param
    if [ "$IRQBalance" = "auto" ]; then
	$LOG "Start irqbalance auto mode"
	irqbalance
    elif [ "$IRQBalance" = "router" ]; then
	$LOG "Start irqbalance routing/wifi optimize mode"
	irqbalance --oneshot
	if [ $cpunum == "4" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 4 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 8 > /proc/irq/24/smp_affinity #PCIe1
	    echo 8 > /proc/irq/25/smp_affinity #PCIe2
	    echo 8 > /proc/irq/19/smp_affinity #VPN
	    echo 8 > /proc/irq/20/smp_affinity #SDXC
	    echo 8 > /proc/irq/22/smp_affinity #USB

	    echo 3 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/eth2/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/eth3/queues/rx-0/rps_cpus
	elif [ $cpunum == "2" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 1 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 2 > /proc/irq/24/smp_affinity #PCIe1
	    echo 2 > /proc/irq/25/smp_affinity #PCIe2
	    echo 1 > /proc/irq/19/smp_affinity #VPN
	    echo 1 > /proc/irq/20/smp_affinity #SDXC
	    echo 1 > /proc/irq/22/smp_affinity #USB

	    echo 2 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 2 > /sys/class/net/eth2/queues/rx-0/rps_cpus
	    echo 2 > /sys/class/net/eth3/queues/rx-0/rps_cpus
	fi
    elif [ "$IRQBalance" = "storage" ]; then
	$LOG "Start irqbalance storage/local services optimize mode"
	irqbalance --oneshot
	if [ $cpunum == "4" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 4 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 4 > /proc/irq/24/smp_affinity #PCIe1
	    echo 8 > /proc/irq/25/smp_affinity #PCIe2
	    echo 8 > /proc/irq/19/smp_affinity #VPN
	    echo 8 > /proc/irq/20/smp_affinity #SDXC
	    echo 8 > /proc/irq/22/smp_affinity #USB

	    echo f > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo f > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo c > /sys/class/net/eth2/queues/rx-0/rps_cpus
	    echo c > /sys/class/net/eth3/queues/rx-0/rps_cpus
	elif [ $cpunum == "2" ]; then
	    echo 1 > /proc/irq/3/smp_affinity  #GMAC
	    echo 1 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 1 > /proc/irq/24/smp_affinity #PCIe1
	    echo 1 > /proc/irq/25/smp_affinity #PCIe2
	    echo 1 > /proc/irq/19/smp_affinity #VPN
	    echo 2 > /proc/irq/20/smp_affinity #SDXC
	    echo 2 > /proc/irq/22/smp_affinity #USB

	    echo 1 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/eth2/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/eth3/queues/rx-0/rps_cpus
	fi
    fi
}

stop() {
    pid=`pidof irqbalance`
    if [ "$pid" != "" ]; then
	$LOG "Stopping irqbalance"
	killall -q irqbalance
	killall -q -SIGKILL irqbalance
    fi
}

get_param() {
    eval `nvram_buf_get 2860 IRQBalance`
    cpunum=`grep -c processor /proc/cpuinfo`
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;

	reload)
            killall -HUP transmission-daemon
            ;;

        *)
            echo $"Usage: $0 {start|stop|reload|restart}"
            exit 1
esac
