#!/bin/sh

# if app not exist
if [ ! -f /bin/irqbalance ]; then
    exit 0
fi

#include global config
. /etc/scripts/global.sh

#if not SMP
if [ "$CONFIG_SMP" = "" ]; then
    exit 0
fi

LOG="logger -t irqbalance"

start() {
    get_param
    if [ "$IRQBalance" = "auto" ] || [ "$IRQBalance" = "router" ]; then
	$LOG "Start irqbalance routing/wifi optimize mode"
	if [ $cpunum == "4" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 4 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 8 > /proc/irq/24/smp_affinity #PCIe1
	    echo 8 > /proc/irq/25/smp_affinity #PCIe2
	    echo 8 > /proc/irq/19/smp_affinity #VPN
	    echo 8 > /proc/irq/20/smp_affinity #SDXC
	    echo 8 > /proc/irq/22/smp_affinity #USB

	    # phys
	    echo 3 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/ra0/queues/tx-0/xps_cpus
	    echo 3 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/rai0/queues/tx-0/xps_cpus
	    echo 3 > /sys/class/net/$phys_lan_if/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/$phys_lan_if/queues/tx-0/xps_cpus
	    echo 3 > /sys/class/net/$phys_wan_if/queues/rx-0/rps_cpus
	    echo 3 > /sys/class/net/$phys_wan_if/queues/tx-0/xps_cpus

	    # VPN
	    find /sys -type d -name 'ppp[0-10]' | while read dev_ppp; do
		echo 4 > $dev_ppp/queues/rx-0/rps_cpus
		echo 4 > $dev_ppp/queues/tx-0/xps_cpus
	    done
	elif [ $cpunum == "2" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 1 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 2 > /proc/irq/24/smp_affinity #PCIe1
	    echo 2 > /proc/irq/25/smp_affinity #PCIe2
	    echo 1 > /proc/irq/19/smp_affinity #VPN
	    echo 1 > /proc/irq/20/smp_affinity #SDXC
	    echo 1 > /proc/irq/22/smp_affinity #USB

	    # phys
	    echo 2 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 2 > /sys/class/net/ra0/queues/tx-0/xps_cpus
	    echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/rai0/queues/tx-0/xps_cpus
	    echo 2 > /sys/class/net/$phys_lan_if/queues/rx-0/rps_cpus
	    echo 2 > /sys/class/net/$phys_lan_if/queues/tx-0/xps_cpus
	    echo 2 > /sys/class/net/$phys_wan_if/queues/rx-0/rps_cpus
	    echo 2 > /sys/class/net/$phys_wan_if/queues/tx-0/xps_cpus

	    # VPN
	    find /sys -type d -name 'ppp[0-10]' | while read dev_ppp; do
		echo 2 > $dev_ppp/queues/rx-0/rps_cpus
		echo 2 > $dev_ppp/queues/tx-0/xps_cpus
	    done
	fi
    elif [ "$IRQBalance" = "storage" ]; then
	$LOG "Start irqbalance storage/local services optimize mode"
	if [ $cpunum == "4" ]; then
	    echo 2 > /proc/irq/3/smp_affinity  #GMAC
	    echo 4 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 4 > /proc/irq/24/smp_affinity #PCIe1
	    echo 8 > /proc/irq/25/smp_affinity #PCIe2
	    echo 8 > /proc/irq/19/smp_affinity #VPN
	    echo 8 > /proc/irq/20/smp_affinity #SDXC
	    echo 8 > /proc/irq/22/smp_affinity #USB

	    # phys
	    echo f > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo f > /sys/class/net/ra0/queues/tx-0/xps_cpus
	    echo f > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo f > /sys/class/net/rai0/queues/tx-0/xps_cpus
	    echo c > /sys/class/net/$phys_lan_if/queues/rx-0/rps_cpus
	    echo c > /sys/class/net/$phys_lan_if/queues/tx-0/xps_cpus
	    echo c > /sys/class/net/$phys_wan_if/queues/rx-0/rps_cpus
	    echo c > /sys/class/net/$phys_wan_if/queues/tx-0/xps_cpus

	    # VPN
	    find /sys -type d -name 'ppp[0-10]' | while read dev_ppp; do
		echo 1 > $dev_ppp/queues/rx-0/rps_cpus
		echo 1 > $dev_ppp/queues/tx-0/xps_cpus
	    done
	elif [ $cpunum == "2" ]; then
	    echo 1 > /proc/irq/3/smp_affinity  #GMAC
	    echo 1 > /proc/irq/4/smp_affinity  #PCIe0
	    echo 1 > /proc/irq/24/smp_affinity #PCIe1
	    echo 1 > /proc/irq/25/smp_affinity #PCIe2
	    echo 1 > /proc/irq/19/smp_affinity #VPN
	    echo 2 > /proc/irq/20/smp_affinity #SDXC
	    echo 2 > /proc/irq/22/smp_affinity #USB

	    # phys
	    echo 1 > /sys/class/net/ra0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/ra0/queues/tx-0/xps_cpus
	    echo 1 > /sys/class/net/rai0/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/rai0/queues/tx-0/xps_cpus
	    echo 1 > /sys/class/net/$phys_lan_if/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/$phys_lan_if/queues/tx-0/xps_cpus
	    echo 1 > /sys/class/net/$phys_wan_if/queues/rx-0/rps_cpus
	    echo 1 > /sys/class/net/$phys_wan_if/queues/tx-0/xps_cpus

	    # VPN
	    find /sys -type d -name 'ppp[0-10]' | while read dev_ppp; do
		echo 2 > $dev_ppp/queues/rx-0/rps_cpus
		echo 2 > $dev_ppp/queues/tx-0/xps_cpus
	    done
	fi
    fi
    if [ "$IRQBalance" = "auto" ]; then
	$LOG "Start irqbalance auto mode"
	irqbalance $banirq
    fi
}

stop() {
    pid=`pidof irqbalance`
    if [ "$pid" != "" ]; then
	$LOG "Stopping irqbalance"
	killall -q irqbalance
	killall -q -SIGKILL irqbalance
    fi
}

get_param() {
    eval `nvram_buf_get 2860 IRQBalance`
    cpunum=`grep -c processor /proc/cpuinfo`
    banirq=`grep ipi_ /proc/interrupts | cut -f1 -d":" | awk {' print "--banirq="$1 '}`
}

case "$1" in
        start)
            start
            ;;

	stop)
            stop
            ;;

	restart)
            stop
            start
            ;;
        *)
            echo $"Usage: $0 {start|stop|reload|restart}"
            exit 1
esac
