#!/bin/sh

PWD=`pwd`

rm -rf $PWD/releases
mkdir -p $PWD/releases

DEVLIST="MT7620-2T2R-8M MT7620-2T2R-MT7610-1T1R-5GHZ-8M"

./clear

for devname in $DEVLIST
do
    ./clear RELEASE
    nice -19 ./compile "$devname" $1 || exit 1
    cp -f $PWD/images/*.zip $PWD/releases
done
