#!/bin/sh

PWD=`pwd`

rm -rf $PWD/releases
mkdir -p $PWD/releases

# production devices
DEVLISTONEBAND="MT7620-2T2R-8M"
DEVLISTDUALBAND="MT7620-2T2R-MT7610-1T1R-5GHZ-8M-R1.1 MT7620-2T2R-MT7610-1T1R-5GHZ-8M"
DEVLISTGIGADUALBAND="MT7621-MT7603-MT7610-1T1R-16M-USB"

./clear

DEVLIST="$DEVLISTGIGADUALBAND $DEVLISTDUALBAND $DEVLISTONEBAND"

for devname in $DEVLIST
do
    ./clear RELEASE
    nice -19 ./compile "$devname" $1 || exit 1
    cp -f $PWD/images/*.zip $PWD/releases
done
