#!/bin/sh

#include global config
. /etc/scripts/global.sh

PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"

PPP_FIREWALL="/tmp/ppp_firewall_${PPP_IFACE}"

LOG="logger -t pppd"

eval `nvram_buf_get 2860 vpnPeerDNS`

    $LOG "Disable forwarding for $PPP_IFACE interface"
    sysctl -wq net.ipv4.conf.$PPP_IFACE.forwarding=0

    $LOG "Restore netfilter rules from pppd"
    iptables -D FORWARD -o $PPP_IFACE -j ACCEPT > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan_ipaddr/$lan_netmask -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $chilli_net -j MASQUERADE > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $lan_ipaddr/$lan_netmask -j SNAT --to-source $PPP_LOCAL > /dev/null 2>&1
    iptables -t nat -D POSTROUTING -o $PPP_IFACE -s $chilli_net -j SNAT --to-source $PPP_LOCAL > /dev/null 2>&1

    if [ -e $PPP_FIREWALL ]; then
	rm -f $PPP_FIREWALL
    fi

    #remove portforward rules
    if [ -e /etc/portforward_vpn ]; then
	/etc/portforward_vpn "D" "$PPP_IFACE" "$PPP_LOCAL" > /dev/null 2>&1
    fi

    #remove route rules
    if [ -e /etc/routes_ppp_replace ]; then
	$LOG "Delete user routes"
	/etc/routes_ppp_replace del $PPP_IFACE > /dev/null 2>&1
    fi

    $LOG "Restore default gateway"
    #clear all default route
    if [ -e /tmp/ip-down-route-reload ] || [ "$firstgw" != "" ]; then
	while ip -4 route del default ; do
    	    :
	done
    fi

    #restore default gateway
    if [ -e /tmp/ip-down-route-reload ]; then
	$LOG "Restore default gateways from backup"
	/tmp/ip-down-route-reload
	rm -f /tmp/ip-down-route-reload
    fi
    if [ "$firstgw" != "" ]; then
	$LOG "Restore default gateway $firstgw"
	ip -4 route replace default via $firstgw
    fi

    if [ "$IPv6OpMode" = "2" -o "$IPv6OpMode" = "3" ]; then
	$LOG "all tunnels in ipv6 deconfig before modules reload (prevent race)"
        service six stop
    fi

    $LOG "Flush route cache"
    ip -4 route flush cache

    $LOG "Restart need service and rebuild shaper and iptables rules"
    services_restart.sh pppd

    export PPP_IFACE PPP_TTY PPP_SPEED PPP_LOCAL PPP_REMOTE PPP_IPPARAM
    if [ -d /etc/ppp/ip-down.d -a -x /bin/run-parts ]; then
	$LOG "Run scripts from /etc/ppp/ip-down.d"
        run-parts /etc/ppp/ip-down.d
    fi
    #remove exported vpn_if_name
    rm -f /tmp/vpn_if_name
