#!/bin/sh

# ipv6-up
# Called by pppd after IPV6CP/up was finished

LOG="logger -t pppd"

#include global config
. /etc/scripts/global.sh

if [ -f /bin/dhcp6c ] && [ "$IPv6Dhcpc" = "1" ] && [ "$vpnDGWSIX" = "on" ]; then
    $LOG "Replace IPV6 dgw to $PPP_IFACE"
    ip -6 route replace default dev $PPP_IFACE
    service six dhcpcreconf
fi
