#!/bin/sh

# ipv6-down
# Called by pppd after IPV6CP/up was finished

LOG="logger -t pppd"

#include global config
. /etc/scripts/global.sh

if [ -f /bin/dhcp6c ] && [ "$IPv6Dhcpc" = "1" ] && [ "$vpnDGWSIX" = "on" ]; then
    killall -q dhcp6c
    killall -q -SIGKILL dhcp6c
fi
