#!/bin/sh

##########################################################
# include profile variables
##########################################################
. /etc/profile

##########################################################
# Start all init scripts in /etc/rc.d
# executing them in numerical order.
##########################################################
for exname in /etc/rc.d/S??* ;do
     # Ignore dangling symlinks (if any).
     [ ! -f "$exname" ] && continue
     [ ! -x "$exname" ] && continue
     case "$exname" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $exname
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $exname start
	    ;;
    esac
done
