#!/bin/sh

# only clean load start this
if [ -f /tmp/is_preconfigured ]; then
    exit 0
fi

LOG="echo PRECONFIG"

start() {
    $LOG "Preconfigure."

    # blink sys/vpn leds
    if [ -f /bin/gpio ]; then
	# include kernel config
	. /etc/scripts/config.sh

	if [ "$CONFIG_RALINK_GPIO_SYS_LED" != "" ]; then
	    gpio l "$CONFIG_RALINK_GPIO_SYS_LED" 1 1 0 0 1000
	fi
    fi

    # create fstab if not exist
    touch /etc/fstab

    mount -t devpts /dev/pts /dev/pts
    mount -a
    chmod 777 /tmp

    # create some folders in var"
    mkdir -p /var/run /var/lock /var/lock/subsys /var/log /var/tmp

    # remove vpn resolv.conf
    rm -f /etc/ppp/resolv.conf

    # this may be need for some apps
    ln -sf /var/lock /var/locks

    # set is_preconfigured flag
    touch /tmp/is_preconfigured
}

stop() {
    :
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
