#!/bin/sh

LOG="echo SYSLOG"

start() {
    get_param
    if [ "$KLogd" = "1" ]; then
	$LOG "Start klogd"
	klogd &
    fi

    if [ -z "$SysLogLevel" ]; then
        SysLogLevel=7
    fi


    if [ "$SysLogd" = "1" ]; then
	if [ "$RemoteSysLogIP" != "0.0.0.0" ] && [ "$RemoteSysLogIP" != "" ]; then
	    $LOG "Start syslogd remote mode. Host $RemoteSysLogIP"
	    syslogd -b0 -s100 -l$SysLogLevel -R $RemoteSysLogIP -D -L &
	else
	    $LOG "Start syslogd local"
	    syslogd -b0 -s100 -l$SysLogLevel -S -D &
	fi
    fi
}

get_param() {
    eval `nvram_buf_get 2860 SysLogd KLogd RemoteSysLogIP SysLogLevel`
}

stop() {
    if [ -e /var/run/klogd.pid ] || [ -e /var/run/syslogd.pid ]; then
	$LOG "Stop syslog and klog"
        # terminate klogd daemon
        while killall -q klogd; do
            usleep 500000
            killall -q -SIGKILL klogd
        done
        # terminate syslogd daemon
        while killall -q syslogd; do
            usleep 500000
            killall -q -SIGKILL syslogd
        done
	rm -f /var/log/messages > /dev/null 2>&1
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
