#!/bin/sh

LOG="logger -t genkey"

start() {
    if [ ! -e /etc/miniupnpd.conf.uuid ] && [ -e /bin/miniupnpd ]; then
       $LOG "No UPNP UUID found. Generate new UUID."
       num=0
        for uuidn in `seq 1 36`; do
            id=`cat /dev/urandom | hexdump | head -1 | cut -c9`
            num=`expr $num + 1`
            if [ "$num" = "9" ] || [ "$num" = "19" ] || [ "$num" = "24" ]; then
	        id="-"
            fi
            outid="$outid$id"
        done
        serial=`echo "$outid" | cut -f1 -d-`
        $LOG "UPNP UUID is $outid , serial is $serial"
	printf "uuid=$outid\nserial=$serial\n" > /etc/miniupnpd.conf.uuid
	needrwfssave=1
    fi

    if [ -e /bin/dhcp6s ] && [ ! -e /etc/dhcp6cctlkey -o ! -e /etc/dhcp6sctlkey ]; then
	$LOG "DHCP6 ctl keys generate."
	dd if=/dev/urandom count=1 2> /dev/null | md5sum | cut -d" " -f1 > /etc/dhcp6cctlkey
	dd if=/dev/urandom count=1 2> /dev/null | md5sum | cut -d" " -f1 > /etc/dhcp6sctlkey
	needrwfssave=1
    fi

    if [ "$needrwfssave" = "1" ]; then
	touch /tmp/needrwfssave
    fi
}

stop() {
    :
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
