#!/bin/sh

LOG="logger -t sysctl"

# include kernel config
. /etc/scripts/config.sh

start() {
    $LOG "Tune kernel with sysctl."
    sysctl -wpneq /etc/sysctl.conf

    get_param

    # set domainname
    if [ "$dhcpDomain" != "" ]; then
	krn_domain="$dhcpDomain"
    else
	krn_domain="Wive-NG-MT"
    fi
    sysctl -wq kernel.domainname="$krn_domain"

    # only at boot time
    if [ ! -e /tmp/bootgood ]; then
        # disable forward at boot
	sysctl -wq net.ipv4.conf.all.forwarding=0
	sysctl -wq net.ipv4.conf.default.forwarding=0
	sysctl -wq net.ipv6.conf.all.forwarding=0
	sysctl -wq net.ipv6.conf.default.forwarding=0
    fi

###################### SECTION FOR SAMBA AND TRANSMISION KERNEL TUNE ###################
    if [ "$SmbEnabled" = "1" ] || [ "$TransmissionEnabled" = "1" ] || [ "$xupnpd" = "1" ] || [ "$UDPXYMode" != "0" ]; then
	# banish core dump files to /dev/null
	ulimit -c 0
	# increase file descriptors
	ulimit -n 32768
	# virtual memory
	ulimit -v unlimited
	# max memory size
	ulimit -m unlimited
	# always overommit
	sysctl -wq vm.overcommit_ratio=100
	sysctl -wq vm.overcommit_memory=2
    else
	# heruistic overcommit
	sysctl -wq vm.overcommit_memory=0
    fi
}

stop() {
    :
}

get_param() {
    eval `nvram_buf_get 2860 dhcpDomain SmbEnabled TransmissionEnabled xupnpd UDPXYMode`
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
