#!/bin/sh

# get params
. /etc/scripts/global.sh

LOG="logger -t lan"

start() {
  $LOG "Start LAN network interfaces."
    # flush ip from interfaces
    addr_flush

    # lan/wan particions and hardware adresses preconfigure
    if [ ! -e /tmp/bootgood ]; then
	config-switch.sh
    fi

    # bridge preconfigure if not ethernet converter mode
    brisup=`ip -o -4 link show br0 up | wc -l` > /dev/null 2>&1
    if [ "$brisup" = "0" ] && [ "$OperationMode" != "2" ]; then
	if [ ! -d /proc/sys/net/ipv4/conf/br0 ]; then
	    $LOG "Add bridge in the system"
	    brctl addbr br0
        fi
	$LOG "br0_MACADDR $LAN_MAC_ADDR"
	ifconfig br0 hw ether "$LAN_MAC_ADDR"
	ifconfig br0 txqueuelen "$txqueuelen"
	$LOG "Up bridge interface"
	ip link set br0 up
    fi

    if [ "$OperationMode" = "1" ] || [ "$CONFIG_RAETH_BOTH_GMAC" = "y" ]; then
	# always up lan iface
	ip link set "$phys_lan_if" up
    fi

    # configure LAN1/BR0
    ifconfig "$lan_if" "$lan_ipaddr" netmask "$lan_netmask" up
    $LOG "Add LAN1 Mode is $OperationMode lan iface $lan_if, adress $lan_ipaddr"

    # enable forward for LAN interfaces only not bridge mode enable forward
    if [ "$OperationMode" != "0" ] && [ "$ApCliBridgeOnly" != "1" ]; then
	sysctl -wq net.ipv4.conf.$lan_if.forwarding=1
    fi
}

addr_flush() {
    # drop adresses
    ip -4 addr flush dev "$lan_if" > /dev/null 2>&1
    ip -4 addr flush dev "$phys_lan_if" > /dev/null 2>&1
}

stop() {
  $LOG "Stop LAN network interfaces."
    # flush ip from interfaces
    addr_flush
    ip link set "$phys_lan_if" down > /dev/null 2>&1
    # last delete bridge interface
    if [ -d /proc/sys/net/ipv4/conf/br0 ]; then
	ip link set br0 down
	brctl delbr br0
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
