#!/bin/sh

LOG="logger -t vlan"

# get params
. /etc/scripts/global.sh

##########################################################################
# Incoming VLAN pkts to SKB priomap
##########################################################################
set_vlan_ingress_prio_map()
{
    for vlannum in `seq 0 7`; do
	# vlan priority tag => skb->priority mapping
        vconfig set_ingress_map $1 $vlannum $vlannum
	# skb->priority => vlan priority tag mapping
        vconfig set_egress_map $1  $vlannum $vlannum
    done
}

##########################################################################
# Outgoings VLAN pkts priomap
##########################################################################
set_vlan_egress_prio_map()
{
    echo "add future"
}

idx=6
hw_tx_vlan_map()
{
    if [ -e /proc/mt7620/vlan_tx ]; then
	# VIDs < 6 not need map
	if [ "$vid" -lt "6" ]; then
	    return
	fi
	# use slots 6..10 for custom VID
	# NOTE: slots 11..15 used by hw_nat WiFi/USB offload
	if [ "$offloadMode" = "2" ] || [ "$offloadMode" = "3" ]; then
	    maxslots="12"
	else
	    maxslots="16"
	fi
	if [ "$idx" = "$maxslots" ]; then
	    if [ "$vlanDoubleTag" != "1" ]; then
		$LOG "Overflow number of max supported vlans $maxslots, please enable vlan doble tag support for switch to software vlan_tx mode."
	    fi
	    return
	fi
	echo "$idx:$1" > /proc/mt7620/vlan_tx
	idx="$(($idx+1))"
    fi
}

bridgewlvlan() {
    count=0
    for vid in $1
    do
	if [ "$vid" != "0" ] && [ -d /proc/sys/net/ipv4/conf/$3${count} ]; then
	    # add and configure vlan bridges only one time
	    if [ ! -d /proc/sys/net/ipv4/conf/$2.$vid ]; then
		$LOG "Add VLAN interface $2.${vid} to system"
		vconfig add "$2" "${vid}"
		hw_tx_vlan_map "${vid}"
		set_vlan_ingress_prio_map "$2.${vid}"
		$LOG "Add BRIDGE brvl${vid}wl${count} to system"
		brctl addbr "brvl${vid}wl${count}"
		ip link set "brvl${vid}wl${count}" up
		$LOG "Add VLAN interface $2.${vid} to bridge brvl${vid}wl${count}"
		brctl addif "brvl${vid}wl${count}" "$2.${vid}"
		ip link set "$2.${vid}" up
	    fi
	    $LOG "Move interface $3${count} from br0 and to new bridge brvl${vid}wl${count}"
	    delif_from_br br0 "$3${count}"
	    brctl addif "brvl${vid}wl${count}" "$3${count}"
	    ip link set "$3${count}" up
	fi
	count="$(($count+1))"
    done
}

start() {
    get_param

    if [ ! -e /tmp/bootgood ]; then
	##############################################
	# ADD BRIDGES FOR VLAN PARTS USED
	# ADD VLAN LINKS FORM KERNEL TO ESW PORST
	# ONLY ONE TIME AT START!!!
	##############################################
	if [ "$PortVlanEnabled" = "1" ]; then
	    if [ "$CONFIG_RAETH_BOTH_GMAC" = "y" ]; then
		rootif="eth3"
	    else
		rootif="eth2"
	    fi
	    if [ "$tv_port" = "1" ]; then
		$LOG "Add bridge for TV/STB"
		brctl addbr "$vlantvif"
		if [ "$tv_port_mcast" = "1" ]; then
		    # generate random ip from zeroconfig range end set need for igmpproxy work
		    rndip="169.254.$(($RANDOM%253+1)).$(($RANDOM%253+1))"
		    ip -4 addr flush dev "$vlantvif"
		    ip -4 addr add "$rndip"/32 dev "$vlantvif"
		fi
		ip link set "$vlantvif" up
		$LOG "Add vlan to esw for TV/STB"
		vconfig add $rootif 3
		hw_tx_vlan_map "3"
		set_vlan_ingress_prio_map "${rootif}.3"
		brctl addif "$vlantvif" "${rootif}.3"
		ip link set "${rootif}.3" up
	    fi
	    if [ "$sip_port" = "1" ]; then
		$LOG "Add bridge for SIP/STB"
		brctl addbr "$vlansipif"
		if [ "$sip_port_mcast" = "1" ]; then
		    # generate random ip from zeroconfig range end set need for igmpproxy work
		    rndip="169.254.$(($RANDOM%253+1)).$(($RANDOM%253+1))"
		    ip -4 addr flush dev "$vlansipif"
		    ip -4 addr add "$rndip"/32 dev "$vlansipif"
		fi
		ip link set "$vlansipif" up
		$LOG "Add vlan to esw for SIP/STB"
		vconfig add $rootif 4
		hw_tx_vlan_map "4"
		set_vlan_ingress_prio_map "${rootif}.4"
		brctl addif "$vlansipif" "${rootif}.4"
		ip link set "${rootif}.4" up
	    fi
	fi
    else
	##############################################
	# ADD WAN VLANS FOR IPTV/SIP/ETC USAGE
	##############################################
	if [ "$PortVlanEnabled" = "1" ]; then
	    if [ "$tv_port" = "1" ]; then
		for vid in $tv_portVLAN; do
		    $LOG "Add vlan $vid for TV/STB port input (WAN) $tv_portVLAN"
		    vconfig add "$phys_wan_if" "$vid"
		    hw_tx_vlan_map "$vid"
		    set_vlan_ingress_prio_map "${phys_wan_if}.${vid}"
		    brctl addif "$vlantvif" "${phys_wan_if}.${vid}"
		    ip link set "${phys_wan_if}.${vid}" up
		done
	    fi
	    if [ "$sip_port" = "1" ]; then
		for vid in $sip_portVLAN; do
		    $LOG "Add vlan $vid for TV/STB port input (WAN) $sip_portVLAN"
		    vconfig add "$phys_wan_if" "$vid"
		    hw_tx_vlan_map "$vid"
		    set_vlan_ingress_prio_map "${phys_wan_if}.${vid}"
		    brctl addif "$vlansipif" "${phys_wan_if}.${vid}"
		    ip link set "${phys_wan_if}.${vid}" up
		done
	    fi
	fi
	#############################################
	# correct lan ifname for add vlans
	#############################################
	if [ "$switchpart" = "LLLLL" ]; then
	    phys_lan_if="eth2"
	fi
	#############################################
	# ADD LAN VLANS FOR ZONE ISOLATED NETWORKS
	#############################################
	VlanLan=`nvram_get 2860 VlanLan | awk '{ gsub(","," "); print }'`
	if [ "$VlanLan" != "" ] && [ "$VlanLan" != "0" ] && [ "$lan_if" = "br0" ]; then
	    for vid in $VlanLan
	    do
		$LOG "Add LAN network VLAN interface ${phys_lan_if}.${vid} to system"
		vconfig add "$phys_lan_if" "$vid"
		hw_tx_vlan_map "$vid"
		set_vlan_ingress_prio_map "${phys_lan_if}.${vid}"
		brctl addif "$lan_if" "${phys_lan_if}.${vid}"
		ip link set "${phys_lan_if}.${vid}" up
	    done
	    # in router mode allow isolate vlans
	    if [ "$switchpart" != "LLLLL" ]; then
		VlanLanIsolate=`nvram_get 2860 VlanLanIsolate | awk '{ gsub(","," "); print }'`
		for vid in $VlanLanIsolate
		do
		    $LOG "VLAN ${phys_lan_if}.${vid} isolate from others in bridge."
		    echo 1 > /sys/devices/virtual/net/${phys_lan_if}.${vid}/brport/isolate_mode
		done
	    else
		$LOG "AP mode need remove root interface from bridge to work vlan"
		brctl delif "$lan_if" "$phys_lan_if"
	    fi
	fi
	#############################################
	# ADD VLAN TO WLAN BRIDGES
	#############################################
	VlanWifiLan=`nvram_get 2860 VlanWifiLan | awk '{ gsub(","," "); print }'`
	if [ "$VlanWifiLan" != "" ] && [ "$VlanWifiLan" != "0" ] && [ "$lan_if" = "br0" ]; then
	    bridgewlvlan "$VlanWifiLan" "${phys_lan_if}" "$first_wlan_mbss"
	fi
	VlanWifiLanINIC=`nvram_get 2860 VlanWifiLanINIC | awk '{ gsub(","," "); print }'`
	if [ "$VlanWifiLanINIC" != "" ] && [ "$VlanWifiLanINIC" != "0" ] && [ "$lan_if" = "br0" ]; then
	    bridgewlvlan "$VlanWifiLanINIC" "${phys_lan_if}" "$second_wlan_mbss"
	fi
	if [ "$switchpart" != "LLLLL" ]; then
	    VlanWifiWan=`nvram_get 2860 VlanWifiWan | awk '{ gsub(","," "); print }'`
	    if [ "$VlanWifiWan" != "" ] && [ "$VlanWifiWan" != "0" ] && [ "$lan_if" = "br0" ]; then
		bridgewlvlan "$VlanWifiWan" "${phys_wan_if}" "$first_wlan_mbss"
	    fi
	    VlanWifiWanINIC=`nvram_get 2860 VlanWifiWanINIC | awk '{ gsub(","," "); print }'`
	    if [ "$VlanWifiWanINIC" != "" ] && [ "$VlanWifiWanINIC" != "0" ] && [ "$lan_if" = "br0" ]; then
		bridgewlvlan "$VlanWifiWanINIC" "${phys_wan_if}" "$second_wlan_mbss"
	    fi
	fi
	#############################################
	# CALL USER SCRIPTS AFTER VLAN CONFIG
	#############################################
	if [ -d /etc/vlan.d -a -x /bin/run-parts ]; then
	    $LOG "Run scripts from /etc/vlan.d"
	    run-parts /etc/vlan.d
	fi
    fi
}

stop() {
    ##############################################
    # REMOVE WAN VLANS FOR IPTV/SIP/ETC USAGE
    ##############################################
    if [ "$CONFIG_RAETH_BOTH_GMAC" = "y" ]; then
	oldwanvlans=`ip -o -4 link show up | grep 'eth3\.' | awk {' print $2 '} | cut -f -1 -d @`
    else
	oldwanvlans=`ip -o -4 link show up | grep 'eth2.2\.' | awk {' print $2 '} | cut -f -1 -d @`
    fi
    for iface in $oldwanvlans
    do
	# remove tv/sip vlans network interfaces
	ip link set "$iface" down		> /dev/null 2>&1
	brctl delif "$vlantvif" "$iface"	> /dev/null 2>&1
	brctl delif "$vlansipif" "$iface"	> /dev/null 2>&1
	vconfig rem "$iface"			> /dev/null 2>&1
    done
    ##############################################
    # REMOVE LAN VLANS FOR ZONE ISOLATED NETWORKS
    ##############################################
    if [ "$switchpart" = "LLLLL" ] || [ "$CONFIG_RAETH_BOTH_GMAC" = "y" ]; then
	oldlanvlans=`ip -o -4 link show up | grep 'eth2\.' | awk {' print $2 '} | cut -f -1 -d @`
    else
	oldlanvlans=`ip -o -4 link show up | grep 'eth2.1\.' | awk {' print $2 '} | cut -f -1 -d @`
    fi
    for iface in $oldlanvlans
    do
	# remove isolated vlans network interfaces
	ip link set "$iface" down		> /dev/null 2>&1
	brctl delif "$lan_if" "$iface"		> /dev/null 2>&1
	vconfig rem "$iface"			> /dev/null 2>&1
    done
    ##############################################
    # REMOVE BRIDGE INTERFACES FOR VLAN BRIDGES
    ##############################################
    bridgenames=`brctl show | grep brvl | awk {' print $1 '}`
    for bridge in $bridgenames
    do
	for num in `seq 0 4`; do
	    brctl delif "$bridge" "ra$num"	> /dev/null 2>&1
	    brctl delif "$bridge" "rai$num"	> /dev/null 2>&1
	done
	ip link set "$bridge" down		> /dev/null 2>&1
	brctl delbr "$bridge"			> /dev/null 2>&1
    done
}

get_param() {
    # need get offlad mode for limit hw_vlan_tx slot use
    eval `nvram_buf_get 2860 vlanDoubleTag offloadMode`
    if [ -e /proc/sys/net/core/vlan_double_tag ]; then
	# get currecnt double vlan tag mode if present
	vlanDoubleTag=`cat /proc/sys/net/core/vlan_double_tag`
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
