#!/bin/sh

LOG="logger -t resolv"

# include global config
. /etc/scripts/global.sh

start() {
get_param
if [ ! -e /tmp/bootgood ] || [ "$wan_static_dns" = "on" ]; then
    # drop current
    rm -f $fname
    touch $fname

    # add domain name option
    echo "domain $HostName.lo" >> $fname

    # put manual dns to resolv.conf
    # if nameservers is null add 127.0.0.1 for local dns use
    # if nameservers not valid use googledns
    if [ "$wan_primary_dns" != "" -o "$wan_secondary_dns" != "" ] && [ "$wan_static_dns" = "on" ] && [ "$purepppoemode" != "1" -o "$vpnPeerDNS" != "on" ]; then
	$LOG "Generate resolv DNS1: $wan_primary_dns DNS2: $wan_secondary_dns"
	if [ "$wan_primary_dns" != "" ]; then
	    echo "nameserver $wan_primary_dns" >> $fname
	fi
	if [ "$wan_secondary_dns" != "" ]; then
	    echo "nameserver $wan_secondary_dns" >> $fname
	fi
    elif [ "$dnsPEnabled" = "1" ]; then
	$LOG "Generate resolv at local."
	echo "nameserver 127.0.0.1" >> $fname
    else
	$LOG "Not correct DNS use Google dns for fallback"
	echo "nameserver 8.8.8.8" >> $fname
	echo "nameserver 8.8.4.4" >> $fname
    fi

    if [ "$vpnEnabled" = "on" ] && [ "$vpnPeerDNS" = "on" ] && [ -e /etc/ppp/resolv.conf ]; then
	    $LOG "Add ISP DNS from vpn servers for local resolv"
	    cat /etc/ppp/resolv.conf | grep "nameserver" >> $fname
    fi

    if [ "$IPv6OpMode" != "0" ]; then
	if [ -e /etc/resolvipv6.conf ]; then
	    $LOG "Add ISP DNS from ipv6 servers for local resolv"
	    cat /etc/resolvipv6.conf | grep "nameserver" >> $fname
	else
	    if [ "$IPv6Dhcpc" = "0" ] && [ "$IPv6DNSPrimary" != "" -o "$IPv6DNSSecondary" != "" ]; then
		$LOG "Add user ipv6 servers $IPv6DNSPrimary $IPv6DNSSecondary for local resolv"
		if [ "$IPv6DNSPrimary" != "" ]; then
		    echo "nameserver $IPv6DNSPrimary" >> $fname
		fi
		if [ "$IPv6DNSSecondary" != "" ]; then
		    echo "nameserver $IPv6DNSSecondary" >> $fname
		fi
	    elif [ "$dnsPEnabled" = "1" ]; then
		$LOG "Generate ipv6 resolv at local."
		echo "nameserver ::1" >> $fname
	    else
		$LOG "Add google ipv6 servers for local resolv"
		echo "nameserver 2001:4860:4860::8888" >> $fname
		echo "nameserver 2001:4860:4860::8844" >> $fname
	    fi
	fi
    fi
    # read for all write by root
    chmod 644 "$fname" > /dev/null 2>&1
fi
}

get_param() {
    eval `nvram_buf_get 2860 wan_primary_dns wan_secondary_dns IPv6DNSPrimary IPv6DNSSecondary vpnPeerDNS`
    fname="/etc/resolv.conf"

    #if no file create
    if [ ! -e $fname ]; then
        touch $fname
    fi
}

stop() {
    :
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
esac
