#!/bin/sh

# if app not exist
if [ ! -e /bin/inetd ]; then
    exit 0
fi

LOG="logger -t inetd"

start() {
    get_param
    if [ "$Login" != "" ]; then
	echo > /etc/inetd.conf
	need_start=0
	if [ -e /bin/dropbear ] && [ "$RemoteSSH" != "" ] && [ "$RemoteSSH" != "0" ]; then
	    echo "$RemoteSSHPort stream tcp nowait $Login /bin/dropbear /bin/dropbear -i -R -K 60 -I 360 -j" >> /etc/inetd.conf
	    need_start=1
	fi
	if [ -e /bin/ftpd ] && [ "$RemoteFTP" != "" ] && [ "$RemoteFTP" != "0" ]; then
	    if [ "$FtpIdleTime" != "" ]; then
		timeout="-t $FtpIdleTime"
	    fi
	    echo "$FtpPort stream tcp nowait $Login /bin/ftpd ftpd -wS $timeout $FtpRootDir" >> /etc/inetd.conf
	    need_start=1
	fi
	if [ -e /bin/telnetd ] && [ "$RemoteTelnet" != "" ] && [ "$RemoteTelnet" != "0" ]; then
	    echo "telnet stream tcp nowait $Login /bin/telnetd telnetd -i" >> /etc/inetd.conf
	    need_start=1
	fi
	if [ "$need_start" = "1" ]; then
	    $LOG "Starting inetd"
    	    inetd -R 30 -q 64
	fi
    fi
}

get_param() {
    eval `nvram_buf_get 2860 Login RemoteSSH RemoteSSHPort RemoteFTP FtpPort FtpRootDir FtpIdleTime RemoteTelnet`
}

stop() {
    if [ -e /var/run/inetd.pid ]; then
	$LOG "Stopping inetd"
	killall -q inetd
	killall -q -SIGKILL inetd
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
