#!/bin/sh

LOG="logger -t goahead"

# include kernel config
. /etc/scripts/config.sh

WAITBOOTCOMPLETE="20"

start() {
 $LOG "Start goahead"
    #set bootcomplite flag
    touch /tmp/bootgood

    if [ -e /bin/goahead ]; then
	#blink only sys led limit blink time 20 sec after goahead start
	if [ -e /bin/gpio ]; then
	    if [ "$CONFIG_RALINK_GPIO_SYS_LED" != "" ]; then
		gpio l "$CONFIG_RALINK_GPIO_SYS_LED" 1 1 0 0 $WAITBOOTCOMPLETE
	    fi
	fi
	$LOG "Copy web pages to tmpfs."
	mkdir -p /tmp/web
	cp -rpf /web/* /tmp/web
	if [ -d /etc/web ]; then
	    $LOG "Copy user web pages to tmpfs."
    	    cp -rpf /etc/web/* /tmp/web
	fi
	$LOG "Start WEB Managment Server."
	echo "#!/bin/sh"							>  /tmp/webmon
        echo "while true; do"							>> /tmp/webmon
	echo "goahead -f"							>> /tmp/webmon
	echo "logger -t webmon web server unexpectedly stopped - restart."	>> /tmp/webmon
	echo "sleep 1"								>> /tmp/webmon
	echo "done"								>> /tmp/webmon
	if [ -e /tmp/webmon ]; then
	    killall -q webmon
	    killall -q -SIGKILL webmon
	    chmod 555 /tmp/webmon
	    /tmp/webmon &
	fi
	if [ -e /tmp/needrwfssave ]; then
	    $LOG "Wait 20sec for rwfs changes save"
	    sh `(sleep $WAITBOOTCOMPLETE && fs save > /dev/console)` &
	    rm -f /tmp/needrwfssave
	fi
    else
	echo "GOAHEAD NOT FOUND!!! FIX THIS AND REBUILD FIRMWARE."
    fi

}

stop() {
    if [ -e /var/run/goahead.pid ]; then
	$LOG "Stop goahead"
	killall -q webmon
	killall -q -SIGKILL webmon
	killall -q goahead
	killall -q -SIGKILL goahead
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
