#!/bin/sh

LOG="logger -t goahead"

# include kernel config
. /etc/scripts/config.sh

WAITBOOTCOMPLETE="20"

start() {
 $LOG "Start goahead"
    #set bootcomplite flag
    touch /tmp/bootgood

    if [ -f /bin/goahead ]; then
	#blink only sys led limit blink time 20 sec after goahead start
	if [ -f /bin/gpio ]; then
	    if [ "$CONFIG_RALINK_GPIO_SYS_LED" != "" ]; then
		gpio l "$CONFIG_RALINK_GPIO_SYS_LED" 1 1 0 0 $WAITBOOTCOMPLETE
	    fi
	fi
	$LOG "Copy web pages to tmpfs."
	mkdir -p /tmp/web
	cp -rpf /web/* /tmp/web
	if [ -d /etc/web ]; then
	    $LOG "Copy user web pages to tmpfs."
    	    cp -rpf /etc/web/* /tmp/web
	fi
	$LOG "Start WEB Managment Server."
	if [ "$CONFIG_SMP" = "y" ]; then
	    taskset 0x1 goahead &
	else
	    goahead &
	fi
	if [ -f /tmp/needrwfssave ]; then
	    $LOG "Wait 20sec for rwfs changes save"
	    sh `(sleep $WAITBOOTCOMPLETE && fs save > /dev/console)` &
	    rm -f /tmp/needrwfssave
	fi
    else
	echo "GOAHEAD NOT FOUND!!! FIX THIS AND REBUILD FIRMWARE."
    fi

}

stop() {
    if [ -f /var/run/goahead.pid ]; then
	$LOG "Stop goahead"
	killall -q goahead
	killall -q -SIGKILL goahead
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
