#!/bin/sh

LOG="logger -t 2nd_stage"

# include kernel config
. /etc/scripts/config.sh

WAITBOOTCOMPLETE="20"

start() {
    #set bootcomplite flag
    touch /tmp/bootgood

    #blink only sys led limit blink time 20 sec after second satge init start
    if [ -e /bin/gpio ]; then
	if [ "$CONFIG_RALINK_GPIO_SYS_LED" != "" ]; then
	    gpio l "$CONFIG_RALINK_GPIO_SYS_LED" 1 1 0 0 $WAITBOOTCOMPLETE
	fi
    fi

    $LOG "Switch to 2nd boot stage and start webui."
    internet.sh

    if [ -e /bin/nginx ]; then
        eval `nvram_buf_get 2860 Login`
	$LOG "Copy web pages to tmpfs."
	mkdir -p /tmp/web
	cp -rpf /web/* /tmp/web
	if [ -d /etc/web ]; then
	    $LOG "Copy user web pages to tmpfs."
    	    cp -rpf /etc/web/* /tmp/web
	fi
	$LOG "Start WEB Managment Server."
	/etc/scripts/config-nginx.sh > /dev/null 2>&1
	nginx -g "user $Login ;" &
    fi

    if [ "$CONFIG_RALINK_GPIO_PWR_USB" != "0" ] && [ "$CONFIG_RALINK_GPIO_PWR_USB" != "" ]; then
	$LOG "USB Port power ON."
	# usb gpio inverted, 4000 infinity
	gpio l "$CONFIG_RALINK_GPIO_PWR_USB" 0 4000 0 0 0
    fi

    # wait and save rwfs if need
    if [ -e /tmp/needrwfssave ]; then
	$LOG "Wait 20sec for rwfs changes save"
	sh `(sleep $WAITBOOTCOMPLETE && fs save > /dev/console)` &
	rm -f /tmp/needrwfssave
    fi

}

stop() {
    if [ -e /var/run/goahead.pid ]; then
	$LOG "Stop goahead"
	killall -q webmon
	killall -q -SIGKILL webmon
	killall -q goahead
	killall -q -SIGKILL goahead
	killall -q nginx
	killall -q -SIGKILL nginx
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
