#!/bin/sh

# get params
. /etc/scripts/global.sh

LOG="logger -t wan"

# preconfigure some manual parametrs
wan_if_preconf() {
    if [ "$OperationMode" != "0" ] && [ "$ApCliBridgeOnly" != "1" ]; then
	# set manual mtu to wan if set
	if [ "$wan_manual_mtu" != "0" ] && [ "$wan_manual_mtu" != "" ]; then
	    $LOG "Set manual MTU to WAN $wan_manual_mtu"
	    ip link set mtu $wan_manual_mtu dev "$wan_if"
	fi
	# no need forward for phys wan in pure pppoe
	if [ "$igmpEnabled" = "1" ] || [ "$purepppoemode" != "1" ]; then
	    $LOG "Allow forward for $wan_if"
	    sysctl -wq net.ipv4.conf.$wan_if.forwarding=1
	fi
    fi
}

# configure and start zeroconf daemon
zero_conf() {
    (zcip $wan_if /etc/scripts/zcip.script > /dev/null 2>&1) &
}

# configure dhcp client
udhcpc_conf() {
    eval `nvram_buf_get 2860 dhcpRequestIP dhcpVendorClass wan_manual_mtu`
    if [ "$dhcpRequestIP" != "" ]; then
	dhcpRequestIP="-r $dhcpRequestIP"
    else
	dhcpRequestIP=""
    fi
    if [ "$dhcpVendorClass" != "" ]; then
	dhcpVendorClass="-V $dhcpVendorClass"
    else
	dhcpVendorClass=""
    fi
    if [ "$wan_manual_mtu" = "0" ] || [ "$wan_manual_mtu" = "" ]; then
	wan_manual_mtu="-O mtu"
    else
	wan_manual_mtu=""
    fi
    if [ "$IPv6OpMode" = "2" ]; then
	rd_support="-O ip6rd"
    else
	rd_support=""
    fi
    UDHCPCOPTS="-i $wan_if $dhcpRequestIP -S -R -T 5 -a -s /bin/udhcpc.sh -p /var/run/udhcpc.pid \
		-O routes -O staticroutes -O msstaticroutes -O wins $rd_support $dhcpVendorClass $wan_manual_mtu -x hostname:$HostName -f"

    # remove routes updated flags
    rm -f /tmp/routes_applied

    # small wait and start dhcp client
    (udhcpc $UDHCPCOPTS > /dev/null 2>&1) &
}

start() {
 $LOG "Start WAN config"

    # preconfigure WAN interface
    wan_if_preconf

    ####################################################################################
    # Start config wan and start configure daemon depend by current mode
    ####################################################################################

    # enable wan interface
    ip link set "$wan_if" up

    if [ "$wanConnectionMode" = "STATIC" ] || [ "$OperationMode" = "0" ] || [ "$ApCliBridgeOnly" = "1" ]; then
	if [ "$OperationMode" != "0" ] && [ "$ApCliBridgeOnly" != "1" ]; then
	    # lan and wan ip should not be the same except in bridge mode
	    if [ "$wan_ipaddr" = "" ] || [ "$wan_netmask" = "" ]; then
		$LOG "ERROR: WAN's IP address/nemask not set. Need set this in WAN config!!!"
		exit 0
	    fi
	    if [ "$wan_ipaddr" = "$lan_ipaddr" ]; then
		$LOG "ERROR: WAN's IP address is set identical to LAN. Need change LAN_IP adress!!!"
		exit 0
	    fi
	    # wan interface adress set and up
	    ifconfig "$wan_if" "$wan_ipaddr" netmask "$wan_netmask"
	else
	    # bridge interface adress set and up
	    ifconfig br0 "$lan_ipaddr" netmask "$lan_netmask"
        fi
	# always treat bridge mode having static wan connection
	if [ "$wan_gateway" != "" ] && [ "$wan_gateway" != "0.0.0.0" ]; then
	    $LOG "Add default route via $wan_gateway."
	    ip -4 route replace default via $wan_gateway
	fi
	# add routes configured in web
	if [ -f /etc/routes_replace ]; then
	    $LOG "Add user routes."
	    /etc/routes_replace replace "$phys_lan_if" "$wan_if"
	fi
	# Add route to multicast subnet
	if [ "$igmpEnabled" = "1" -o "$UDPXYMode" != "0" ] || [ "$xupnpd" = "1" ]; then
	    $LOG "Add route to multicast subnet."
	    ip -4 route replace "$mcast_net" dev "$wan_if"
	fi
    elif [ "$wanConnectionMode" = "DHCP" ] && [ "$purepppoemode" != "1" ]; then
	$LOG "Start DHCP client at $wan_if."
	udhcpc_conf
    elif [ "$wanConnectionMode" = "ZERO" ] || [ "$purepppoemode" = "1" ]; then
	$LOG "Call zeroconf for get wan ip address."
	zero_conf
    else
	$LOG "Unknown mode. Please reset device."
    fi
}

stop() {
    # stop all vpn services
    service vpnhelper stop

    # stop dhcp and zeroconf clients
    killall -q udhcpc
    killall -q zcip
    killall -q -SIGKILL udhcpc
    killall -q -SIGKILL zcip

    # in gw mode down wlan if not bridge and not apcli_bridge
    if [ "$OperationMode" = "1" ] || [ "$OperationMode" = "3" -a "$ApCliBridgeOnly" != "1" ]; then
	# down wan iface
	ip link set "$wan_if" down > /dev/null 2>&1
    fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
