#!/bin/sh

# get params
. /etc/scripts/global.sh

# constants
LOG="logger -t ethtun"

# sta mode not support MBSSID or Bridges
if [ "$OperationMode" = "2" ]; then
    exit 0
fi

l2tpstart() {
    get_param

    # sanity and enable check
    if [ "$l2tp_eth_enabled" == "" ] || [ "$l2tp_eth_enabled" == "0" ] || [ "$l2tp_eth_tid" == "" ] || [ "$l2tp_eth_ptid" == "" ] \
        || [ "$l2tp_eth_sid" == "" ] || [ "$l2tp_eth_psid" == "" ] || [ "$l2tp_eth_sport" == "" ] || [ "$l2tp_eth_dport" == "" ]  \
        || [ "$l2tp_eth_remote" == "" ] || [ "$l2tp_eth_local" == "" ] && [ "$l2tp_eth_brifs" = "" ]; then
        exit 0
    fi

    $LOG "Configure l2tpv3_eth mode tunnel to $l2tp_eth_remote via $l2tp_eth_local"

    modprobe -q l2tp_eth

    ip l2tp add tunnel tunnel_id "$l2tp_eth_tid" peer_tunnel_id "$l2tp_eth_ptid" encap udp local "$l2tp_eth_local" remote "$l2tp_eth_remote" \
        udp_sport "$l2tp_eth_sport" udp_dport "$l2tp_eth_dport"
    ip l2tp add session tunnel_id "$l2tp_eth_tid" session_id "$l2tp_eth_sid" peer_session_id "$l2tp_eth_psid"

    if [ "$l2tp_eth_brifs" == "all" ]; then
	$LOG "Add l2tp interface to syslem LAN bridge"
	brctl addif br0 l2tpeth0
	ip link set l2tpeth0 up
    else
	$LOG "Add BRIDGE brl2tp to system"
	brctl addbr brl2tp
	for iface in $l2tp_eth_brifs
	do
	    delif_from_br br0 "$iface"
	    # check interface free from bridges
	    allreadyinbr=`brctl show | grep "${iface}$" -c`
	    if [ "$allreadyinbr" = "0" ]; then
		brctl addif brl2tp "$iface"
	    else
		$LOG "$iface allready in used in other bridge, pls see config."
	    fi
	    # allways up after call del_if_from_br
	    ip link set "$iface" up
	done
	brctl addif brl2tp l2tpeth0
	ip link set l2tpeth0 up
	ip link set brl2tp up
    fi

}

l2tpstop() {
    l2tp_eth_tid=`ip l2tp show session | grep "Session" | awk {' print $5 '} | tail -qn1`
    l2tp_eth_sid=`ip l2tp show session | grep "Session" | awk {' print $2 '} | tail -qn1`

    if [ "$l2tp_eth_tid" != "" ]; then
	$LOG "eth l2tp_v3 tunnel stop"
	if [ "$l2tp_eth_sid" != "" ]; then
	    ip l2tp del session tunnel_id "$l2tp_eth_tid" session_id "$l2tp_eth_sid"
	fi
	ip l2tp del tunnel tunnel_id "$l2tp_eth_tid"
    fi

    # remove radio interfaces from l2tpbridge
    for num in `seq 0 4`; do
	    brctl delif brl2tp "ra$num"		> /dev/null 2>&1
	    brctl delif brl2tp "rai$num"	> /dev/null 2>&1
    done
    # remove lan interface from l2tpbridge
    brctl delif brl2tp "$phys_lan_if"		> /dev/null 2>&1

    ip link set brl2tp down			> /dev/null 2>&1
    brctl delbr brl2tp 				> /dev/null 2>&1

    rmmod l2tp_eth 				> /dev/null 2>&1
}

get_param() {
    # get local param always
    eval `nvram_buf_get 2860 l2tp_eth_enabled l2tp_eth_tid l2tp_eth_ptid l2tp_eth_sid l2tp_eth_psid l2tp_eth_sport l2tp_eth_dport \
				l2tp_eth_remote l2tp_eth_local l2tp_eth_brifs`
}

start() {
    l2tpstart
}

stop() {
    l2tpstop
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
esac
