#!/bin/sh

# if app not exist
if [ ! -e /bin/inadyn ]; then
    exit 0
fi

# get params
. /etc/scripts/global.sh

LOG="logger -t dyndns"

start() {
    get_param
    if  [ "$DDNS" = "" ] || [ "$DDNSProvider" = "" ] || [ "$DDNSProvider" = "none" ] || \
	[ "$DDNSAccount" = "" -a "$DDNSProvider" != "freedns.afraid.org" ] || [ "$DDNSPassword" = "" ]; then
	exit 0
    fi
    $LOG "Starting DynDNS"
    if [ "$DDNSProvider" = "dyndns.org" ]; then
        inadyn -u $DDNSAccount -p $DDNSPassword -a $DDNS --dyndns_system dyndns@$DDNSProvider --background $logto
    elif [ "$DDNSProvider" = "zoneedit.com" ] || [ "$DDNSProvider" = "no-ip.com" ]; then
        inadyn -u $DDNSAccount -p $DDNSPassword -a $DDNS --dyndns_system default@$DDNSProvider --background $logto
    elif [ "$DDNSProvider" = "freedns.afraid.org" ]; then
        inadyn -a $DDNS,$DDNSPassword --dyndns_system default@$DDNSProvider --background $logto
    else
        $LOG "Unknown DDNS provider: $DDNSProvider"
    fi
}

get_param() {
    eval `nvram_buf_get 2860 DDNS DDNSProvider DDNSAccount DDNSPassword`
    if [ "$SysLogd" = "1" ]; then
	logto="--syslog"
    fi
}

stop() {
    pid=`pidof inadyn`
    if [ "$pid" != "" ]; then
	$LOG "Stopping DynDns"
	killall -q inadyn
	killall -q -SIGKILL inadyn
    fi
}

case "$1" in
        start)
            start
            ;;

        stop)
            stop
            ;;

        restart)
            stop
            start
            ;;

        *)
            echo $"Usage: $0 {start|stop|restart}"
            exit 1
esac
