#!/bin/sh

# Wive-NG dhcp6c script

LOG="logger -t dhcp6c"
new_resolv_conf=/etc/resolvipv6.conf

if [ -n "$new_domain_name_servers" ]; then
    $LOG "ipv6: domain name servers - $new_domain_name_servers"
    rm -f "$new_resolv_conf"
    for nameserver in $new_domain_name_servers; do
	echo nameserver $nameserver >> $new_resolv_conf
    done
    dnsreload="1"
fi

if [ -e "$new_resolv_conf" ] && [ "$dnsreload" = "1" ]; then
    # regenerate resolv conf and reload dnsmasq config for apply
    service resolv restart
    service dnsserver reload
fi

$LOG "Call reconfigure radvd/dhcp6s for apply new params from dhcp"
service six dhcpradvdreconf
