#!/bin/sh

#############################################################
# global.sh - correct enviroment helper for automatization  #
#############################################################
# This script calculate values and export for usb in others #
# scripts 						    #
#############################################################

#############################################################
# OperationMode:
# 0 - AP Bridge Mode (all ports and wifi in one bridge)
# 1 - AP Gateway (classic router mode)
# 2 - ETH Converter (WAN - ra0 in STA mode, others LAN)
# 3 - AP-Client/Bridge mode
# 4 - Chillispot (classic router mode + chillispot)
#############################################################

# include kernel config
. /etc/scripts/config.sh

# include profile variables
. /etc/profile

# set some constatns
vpn_def_if="ppp0"
txqueuelen="1000"
mcast_net="224.0.0.0/4"
upnmp_net="239.0.0.0/8"

# first get operation mode and wan mode  dns mode and relay mode vpn mode and type
eval `nvram_buf_get 2860 HostName OperationMode \
	wanConnectionMode wan_ipaddr wan_netmask wan_gateway wan_static_dns wan_manual_mtu \
	lan_ipaddr lan_netmask Lan2Enabled lan2_ipaddr lan2_netmask \
	wan_port tv_port sip_port tv_port_mcast sip_port_mcast \
	WLAN_MAC_ADDR WLAN2_MAC_ADDR WAN_MAC_ADDR LAN_MAC_ADDR \
	ApCliAutoConnect ApCliBridgeOnly \
	ApCliIfName WdsIfName BssidIfName \
	dnsPEnabled UDPXYMode UDPXYPort igmpEnabled SysLogd \
	vpnEnabled vpnPurePPPOE vpnType vpnDGW \
	IPv6OpMode IPv6Dhcpc \
	Ipv6InVPN \
	QoSEnable`

# name/mask for first wlanmodule used in system logic
getFirstWlanIfName() {
    if [ "$CONFIG_RT_FIRST_IF_NONE" = "" ]; then
	first_wlan_root_if="ra0"			# is first root interface name
	first_wlan="ra"					# this is mask name vifs for first wlan module
	if [ "$CONFIG_RT2860V2_AP_MBSS" != "" ] || [ "$CONFIG_MT76X2_AP_MBSS" != "" ]; then
	    first_wlan_mbss="ra"			# this is mask name vifs for first mbss wlan module
	fi
	if [ "$CONFIG_RT2860V2_AP_APCLI" != "" ] || [ "$CONFIG_MT76X2_AP_APCLI" != "" ]; then
	    first_wlan_apcli="apcli0"			# this is name vif for first acli wlan module
	fi
	if [ "$CONFIG_RT2860V2_AP_WDS" != "" ] || [ "$CONFIG_MT76X2_AP_WDS" != "" ]; then
	    first_wlan_wds="wds"			# this is mask name vifs for first wds wlan module
	fi
    fi
}

# this if flag say second physical wlan module exist
# and name/mask for second wlanmodule used in system logic
getSecWlanIfName() {
    if [ "$CONFIG_RT_SECOND_IF_NONE" = "" ]; then
	second_wlan_root_if="rai0"			# is root interface name
	second_wlan="rai"				# this is mask name vifs for second wlan module
	if [ "$CONFIG_MT7610_AP_MBSS" != "" ] || [ "$CONFIG_MT76X2_AP_MBSS" != "" ]; then
	    second_wlan_mbss="rai"			# this is mask name vifs for second mbss wlan module
	fi
	if [ "$CONFIG_MT7610_AP_APCLI" != "" ] || [ "$CONFIG_MT76X2_AP_APCLI" != "" ]; then
	    second_wlan_apcli="apclii0"			# this is name vif for first acli wlan module
	fi
	if [ "$CONFIG_MT7610_AP_WDS" != "" ] || [ "$CONFIG_MT76X2_AP_WDS" != "" ]; then
	    second_wlan_wds="wdsi"			# this is mask name vifs for second wds wlan module
	fi
    fi
}

# DEF pysical interface name -> $phys_*_if
getPhysIfName() {
    # physical names
    if [ "$CONFIG_RAETH_GMAC2" = "y" ]; then
	# external switch support
	phys_lan_if="eth2"
	phys_wan_if="eth3"
    else
	# internal switch or not switchible device
	# support vlan parted
	phys_lan_if="eth2.1"
	phys_wan_if="eth2.2"
    fi
}

# LAN interface name -> $lan_if
getLanIfName() {
    # logical names
    if [ "$OperationMode" = "2" ]; then
	lan_if="eth2"
	lan2_if="eth2:9"
    else
	lan_if="br0"
	lan2_if="br0:9"
    fi
    # export for goahead
    echo -n "$lan_if" > /tmp/lan_if_name
}

# VPN interface name -> $vpn_if
getVpnIfName() {
    if [ -f /tmp/vpn_if_name ]; then
	if_tmp=`grep -v "^$" < /tmp/vpn_if_name`
	if [ "$if_tmp" != "" ]; then
	    vpn_if="$if_tmp"
	fi
    fi
}

# WAN interface name -> $wan_if
getWanIfName() {
    # real wan name
    if [ "$OperationMode" = "0" ]; then
	# bridge
	wan_if="br0"
    elif [ "$OperationMode" = "1" ] || [ "$OperationMode" = "4" ]; then
	# gateway/chillispot
	wan_if="$phys_wan_if"
    elif [ "$OperationMode" = "2" ]; then
	# ethernet converter
	wan_if="$first_wlan_root_if"
    elif [ "$OperationMode" = "3" ]; then
        if [ "$ApCliBridgeOnly" = "1" ]; then
    	    # apclient bridge
	    wan_if="br0"
	else
    	    # apclient gw
	    wan_if="$ApCliIfName"
	fi
    fi
    # services wan name
    if [ "$vpnEnabled" = "on" -a  "$vpnDGW" = "1" ] || [ "$MODEMENABLED" = "1" ]; then
	if [ "$vpn_if" != "" ]; then
	    # read from file generated by ip-up script
    	    real_wan_if="$vpn_if"
	else
	    # first ppp iface is client
	    get_ppp_wan_if=`ip -4 -o link show | grep ppp | awk {' print $2 '} | cut -f -1 -d :`
	    if [ "$get_ppp_wan_if" != "" ]; then
    		real_wan_if="$get_ppp_wan_if"
	    fi
	fi
    else
        real_wan_if="$wan_if"
    fi
    # correct vpn_if for some services start
    # this workaround for preconfig igmprpoxy and vpnhelper
    if [ "$vpn_if" = "" ]; then
	vpn_if="$vpn_def_if"
    fi
}

getSixWanIfName() {
    if [ "$IPv6OpMode" = "1" ]; then
	if [ "$vpnEnabled" = "on" ] && [ "$Ipv6InVPN" = "1" ]; then
	    # first ppp iface is client
	    get_ppp_wan_if=`ip -4 -o link show | grep ppp | awk {' print $2 '} | cut -f -1 -d :`
	    if [ "$get_ppp_wan_if" != "" ]; then
    		six_wan_if="$get_ppp_wan_if"
	    else
		six_wan_if="$vpn_def_if"
	    fi
	else
	    six_wan_if="$wan_if"
	fi
    elif [ "$IPv6OpMode" = "2" ]; then
	# 6rd tunif name
	six_wan_if="6rd"
    elif [ "$IPv6OpMode" = "3" ]; then
	# 6to4 tunif name
	six_wan_if="sit0"
    fi
    # export for dhcp6c
    echo -n "$six_wan_if" > /tmp/six_wan_if_name
}

getWanIpaddr() {
    # in WAN non static mode and in full bridget modes always get parametrs direct from if
    if [ "$wanConnectionMode" != "STATIC" ] || [ "$OperationMode" = "0" ] || [ "$ApCliBridgeOnly" = "1" ]; then
	wan_ipaddr=""
	wan_netmask=""
	wan_gateway=""
	wan_manual_mtu=""
    fi

    # get from if and return physical wan ip
    if [ "$wan_ipaddr" = "" ]; then
	wan_ipaddr=`ip -o -4 addr show dev $wan_if scope global | awk {' print $4 '} | cut -f1 -d"/"` > /dev/null 2>&1
    fi

    # get from if and return vpn or physical wan ip
    real_wan_ipaddr=`ip -o -4 addr show dev $real_wan_if scope global | awk {' print $4 '} | cut -f1 -d"/"` > /dev/null 2>&1
    if [ "$real_wan_ipaddr" = "" ]; then
	real_wan_ipaddr="$wan_ipaddr"
    fi
}

getWanReady() {
    # check interfaces configured
    wan_is_not_null=`ip -o -4 addr show $wan_if scope global | wc -l` > /dev/null 2>&1
    realwan_is_not_null=`ip -o -4 addr show $real_wan_if scope global | wc -l` > /dev/null 2>&1
}

# reconnect to AP
wifi_reconnect() {
    if [ "$OperationMode" = "2" ]; then
	staCur_SSID=`nvram_get 2860 staCur_SSID`
	if [ "$staCur_SSID" != "" ]; then
	    # Reconnect to STA
	    iwpriv $first_wlan_root_if set SSID="$staCur_SSID"
	    usleep 500000
	fi
    elif [ "$OperationMode" = "3" ]; then
	if [ "$ApCliAutoConnect" = "1" ]; then
	    # Rescan switch channel if need and try reconnect
	    iwpriv $ApCliIfName set ApCliAutoConnect=1
	else
	    # Reenable apcli and rescan for reconnect
	    iwpriv $ApCliIfName set ApCliEnable=0
	    usleep 100000
	    iwpriv $ApCliIfName set ApCliEnable=1
	    iwpriv $ApCliIfName set SiteSurvey=1
	fi
    fi
}

# wait connect to AP
wait_connect() {
    if [ "$OperationMode" = "2" ]; then
	# Get connection status
	connected=`iwpriv $ApCliIfName connStatus | grep "Connected" -c`
	if [ "$connected" = "0" ]; then
	    exit 1
	fi
    elif [ "$OperationMode" = "3" ] && [ "$ApCliBridgeOnly" != "1" ]; then
	# Get connection status
	notconnected=`iwconfig $ApCliIfName | grep -c "Not-Associated"`
	if [ "$noconnected" = "1" ]; then
	    exit 1
	fi
    fi
}

flush_net_caches() {
    ip route flush cache > /dev/null 2>&1
    echo f > /proc/net/nf_conntrack
}

delif_from_br() {
    ip -4 addr flush dev $1 > /dev/null 2>&1
    ip link set $1 down > /dev/null 2>&1
    brctl delif br0 $1 > /dev/null 2>&1
}

readdif_to_br() {
    delif_from_br $1
    brctl addif br0 $1
    ip link set $1 up
}

set_vlan_map()
{
    for vlannum in `seq 0 7`; do
	# vlan priority tag => skb->priority mapping
        vconfig set_ingress_map $1 $vlannum $vlannum
	# skb->priority => vlan priority tag mapping
        vconfig set_egress_map $1  $vlannum $vlannum
    done
}

get_switch_type() {
    if [ -f /proc/mt7620/gmac ]; then
	procdir="/proc/mt7620/gmac"
	switchmode=3
    elif [ -f /proc/mt7628/gmac ]; then
	procdir="/proc/mt7628/gmac"
	switchmode=3
    elif [ -f /proc/mt7621/gmac ]; then
	procdir="/proc/mt7621/gmac"
	switchmode=4
    else
	$LOG "No switch in system!!!"
	procdir=
	switchmode=
    fi
}

get_switch_part() {
    if [ "$OperationMode" = "1" ] || [ "$OperationMode" = "4" ]; then
	# get manual vlan parts
	tv_portVLAN=`nvram_get 2860 tv_portVLAN | awk '{ gsub(","," "); print }'`
	sip_portVLAN=`nvram_get 2860 sip_portVLAN | awk '{ gsub(","," "); print }'`
	# manual vlan configured
	if [ "$tv_port" = "1" -a "$tv_portVLAN" != "" ] || [  "$sip_port" = "1" -a "$sip_portVLAN" != "" ]; then
	    VlanEnabled="1"
	    vlantvif="vlantv"
	    vlansipif="vlansip"
	    switchpart="VLANS"
	# tv and sip
	elif [ "$tv_port" = "1" ] && [ "$sip_port" = "1" ]; then
	    if [ "$wan_port" = "4" ]; then
		switchpart="WWWLL"
            else
		switchpart="LLWWW"
	    fi
	# only tv
	elif [ "$tv_port" = "1" ]; then
	    if [ "$wan_port" = "4" ]; then
		switchpart="WWLLL"
            else
		switchpart="LLLWW"
	    fi
	# only sip
	elif [ "$sip_port" = "1" ]; then
	    if [ "$wan_port" = "4" ]; then
		switchpart="WLWLL"
            else
		switchpart="LLWLW"
	    fi
	# without bridget ports
	else
	    if [ "$wan_port" = "4" ]; then
		switchpart="WLLLL"
            else
		switchpart="LLLLW"
	    fi
	fi
    elif [ "$OperationMode" = "0" ] || [ "$OperationMode" = "2" ] || [ "$OperationMode" = "3" ]; then
		switchpart="LLLLL"
    fi
}

# check pppoe vpn type
getPPPOEMode() {
    if [ "$vpnEnabled" = "on" ] && [ "$vpnType" = "0" ] && [ "$vpnPurePPPOE" = "1" ]; then
	purepppoemode="1"
    else
	purepppoemode="0"
    fi
}

# get params
getFirstWlanIfName
getSecWlanIfName
getPhysIfName
getLanIfName
getVpnIfName
getWanIfName
getSixWanIfName
getWanIpaddr
getWanReady

get_switch_type
get_switch_part

getPPPOEMode
