#!/bin/sh

############################################################
# global.sh - correct enviroment helper for automatization #
############################################################

############################################################
# OperationMode:
# 0 - AP Bridge Mode (all ports and wifi in one bridge)
# 1 - AP Gateway (classic router mode)
# 2 - ETH Converter (WAN - ra0 in STA mode, others LAN)
# 3 - AP-Client/Bridge mode
# 4 - Chillispot (classic router mode + chillispot)
############################################################

# include kernel config
. /etc/scripts/config.sh

# include profile variables
. /etc/profile

# set default variables
wan_if="eth2.2"
real_wan_if="eth2.2"
lan_if="br0"
lan2_if="br0:9"
vpn_def_if="ppp0"

# phys names
phys_lan_if="eth2.1"
phys_wan_if="eth2.2"

# set some constatns
mcast_net="224.0.0.0/4"
upmpm_net="239.0.0.0/8"
txqueuelen="1000"

# first get operation mode and wan mode  dns mode and relay mode vpn mode and type
eval `nvram_buf_get 2860 HostName OperationMode \
	wanConnectionMode wan_ipaddr wan_netmask wan_gateway wan_static_dns wan_manual_mtu \
	lan_ipaddr lan_netmask Lan2Enabled lan2_ipaddr lan2_netmask \
	tv_port sip_port tv_portVLAN sip_portVLAN tv_port_mcast sip_port_mcast \
	WLAN_MAC_ADDR WLAN2_MAC_ADDR WAN_MAC_ADDR LAN_MAC_ADDR \
	dnsPEnabled UDPXYMode UDPXYPort igmpEnabled \
	vpnEnabled vpnPurePPPOE vpnType vpnDGW \
	IPv6OpMode \
	ApCliBridgeOnly \
	MODEMENABLED \
	QoSEnable simple_qos`

# name/mask for first wlanmodule used in system logic
getFirstWlanIfName() {
    if [ "$CONFIG_RT2860V2_AP" != "" ]; then
	first_wlan_root_if="ra0"			# is first root interface name
	first_wlan="ra"					# this is mask name vifs for first wlan module
	if [ "$CONFIG_RT2860V2_AP_MBSS" != "" ]; then
	    first_wlan_mbss="ra"			# this is mask name vifs for first mbss wlan module
	fi
	if [ "$CONFIG_RT2860V2_AP_APCLI" != "" ]; then
	    first_wlan_apcli="apcli0"			# this is name vif for first acli wlan module
	fi
	if [ "$CONFIG_RT2860V2_AP_WDS" != "" ]; then
	    first_wlan_wds="wds"			# this is mask name vifs for first wds wlan module
	fi
    fi
}

# this if flag say second physical wlan module exist
# and name/mask for second wlanmodule used in system logic
getSecWlanIfName() {
    if [ "$CONFIG_RT3090_AP" != "" ]; then
	second_wlan_root_if="rai0"			# is root interface name
	second_wlan="rai"				# this is mask name vifs for second wlan module
	if [ "$CONFIG_RT3090_AP_MBSS" != "" ]; then
	    second_wlan_mbss="rai"			# this is mask name vifs for second mbss wlan module
	fi
	if [ "$CONFIG_RT3090_AP_APCLI" != "" ]; then
	    second_wlan_apcli="apclii0"			# this is name vif for first acli wlan module
	fi
	if [ "$CONFIG_RT3090_AP_WDS" != "" ]; then
	    second_wlan_wds="wdsi"			# this is mask name vifs for second wds wlan module
	fi
    fi
}

# LAN interface name -> $lan_if
getLanIfName() {
    # phys port names
    if [ "$CONFIG_RAETH_ESW" = "y" ]; then
	# internal switch support
	phys_lan_if="eth2.1"
    elif [ "$CONFIG_RAETH_GMAC2" = "y" ]; then
	# external switch support
	phys_lan_if="eth2"
    else
	# this is stub
	# support only switched devices
	phys_lan_if="eth2.1"
    fi
    # logical names
    if [ "$OperationMode" = "2" ]; then
	lan_if="eth2"
	lan2_if="eth2:9"
    else
	lan_if="br0"
	lan2_if="br0:9"
    fi
    # export for goahead
    echo -n "$lan_if" > /tmp/lan_if_name
}

# VPN interface name -> $vpn_if
getVpnIfName() {
    if [ -f /tmp/vpn_if_name ]; then
	if_tmp=`grep -v "^$" < /tmp/vpn_if_name`
	if [ "$if_tmp" != "" ]; then
	    vpn_if="$if_tmp"
	fi
    fi
}

# WAN interface name -> $wan_if
getWanIfName() {
    # phys wan name
    if [ "$CONFIG_RAETH_ESW" = "y" ]; then
	# internal switch support
	phys_wan_if="eth2.2"
    elif [ "$CONFIG_RAETH_GMAC2" = "y" ]; then
	# external dual phy switch support
	phys_wan_if="eth3"
    else
	# this is stub
	# support only switched devices
	phys_lan_if="eth2.2"
    fi
    # real wan name
    if [ "$OperationMode" = "0" ]; then
	# bridge
	wan_if="br0"
    elif [ "$OperationMode" = "1" ] || [ "$OperationMode" = "4" ]; then
	# gateway/chillispot
	wan_if="$phys_wan_if"
    elif [ "$OperationMode" = "2" ]; then
	# ethernet converter
	wan_if="$first_wlan_root_if"
    elif [ "$OperationMode" = "3" ]; then
        if [ "$ApCliBridgeOnly" = "1" ]; then
    	    # apclient bridge
	    wan_if="br0"
	else
    	    # apclient gw
	    if [ "$first_wlan_apcli" != "" ]; then
		wan_if="$first_wlan_apcli"
	    elif [ "$second_wlan_apcli" != "" ]; then
		wan_if="$second_wlan_apcli"
	    fi
	fi
    fi
    # services wan name
    if [ "$vpnEnabled" = "on" -a  "$vpnDGW" = "1" ] || [ "$MODEMENABLED" = "1" ]; then
	if [ "$vpn_if" != "" ]; then
	    # read from file generated by ip-up script
    	    real_wan_if="$vpn_if"
	else
	    # first ppp iface is client
	    get_ppp_wan_if=`ip -4 -o link show | grep ppp | awk {' print $2 '} | cut -f -1 -d :`
	    if [ "$get_ppp_wan_if" != "" ]; then
    		real_wan_if="$get_ppp_wan_if"
	    fi
	fi
    else
        real_wan_if="$wan_if"
    fi
    # correct vpn_if for some services start
    # this workaround for preconfig igmprpoxy and vpnhelper
    if [ "$vpn_if" = "" ]; then
	vpn_if="$vpn_def_if"
    fi
    # export for goahead
    echo -n "$wan_if" > /tmp/wan_if_name
}

getTunIfName() {
    if [ "$IPv6OpMode" = "1" ]; then
	six_wan_if="$real_wan_if"
    elif [ "$IPv6OpMode" = "2" ]; then
	six_wan_if="6rd"
    elif [ "$IPv6OpMode" = "3" ]; then
	six_wan_if="sit0"
    fi
}

getWanIpaddr() {
    # in non static mode always get parametrs direct from if
    if [ "$wanConnectionMode" != "STATIC" ]; then
	wan_ipaddr=""
	wan_netmask=""
	wan_gateway=""
    fi

    # get from if and return physical wan ip
    if [ "$wan_ipaddr" = "" ]; then
	wan_ipaddr=`ip -o -4 addr show dev $wan_if scope global | awk ' {print $4}' | cut -f1 -d"/"` > /dev/null 2>&1
    fi

    # get from if and return vpn or physical wan ip
    real_wan_ipaddr=`ip -o -4 addr show dev $real_wan_if scope global | awk ' {print $4}' | cut -f1 -d"/"` > /dev/null 2>&1
    if [ "$real_wan_ipaddr" = "" ]; then
	real_wan_ipaddr="$wan_ipaddr"
    fi

}

getWanReady() {
    wan_is_not_null=`ip -o -4 addr show $wan_if scope global | wc -l` > /dev/null 2>&1
    realwan_is_not_null=`ip -o -4 addr show $real_wan_if scope global | wc -l` > /dev/null 2>&1
}

getVlanConfig() {
    if [ "$tv_port" = "1" -o "$sip_port" = "1" ] && [ "$tv_portVLAN" != "" -o "$sip_portVLAN" != "" ]; then
	VlanEnabled="1"
	vlantvif="vlantv"
	vlansipif="vlansip"
    else
	VlanEnabled="0"
	vlantvif=""
	vlansipif=""
    fi
}

# reconnect to AP
wifi_reconnect() {
    if [ "$OperationMode" = "2" ]; then
	staCur_SSID=`nvram_get 2860 staCur_SSID`
	if [ "$staCur_SSID" != "" ]; then
	    # Reconnect to STA
	    iwpriv $first_wlan_root_if set SSID="$staCur_SSID"
	    usleep 500000
	fi
    elif [ "$OperationMode" = "3" ]; then
	# Reenable apcli for reconnect
	iwpriv $first_wlan_apcli set ApCliEnable=0
        usleep 100000
	iwpriv $first_wlan_apcli set ApCliEnable=1
	usleep 500000
    fi
}

# wait connect to AP
wait_connect() {
    if [ "$OperationMode" = "2" ]; then
	# Get connection status
	connected=`iwpriv $first_wlan_root_if connStatus | grep "Connected" -c`
	if [ "$connected" = "0" ]; then
	    exit 1
	fi
    elif [ "$OperationMode" = "3" ] && [ "$ApCliBridgeOnly" != "1" ]; then
	# Get connection status
	notconnected=`iwconfig $first_wlan_apcli | grep -c "Not-Associated"`
	if [ "$noconnected" = "1" ]; then
	    exit 1
	fi
    fi
}

# conntrack and route table/caches flush
flush_net_caches() {
    ip route flush cache > /dev/null 2>&1
    echo f > /proc/net/nf_conntrack
}

# flush arp cache in switch
flush_arp_cache() {
    if [ -e /bin/switch ]; then
	switch clear > /dev/null 2>&1
    fi
}

delif_from_br() {
    ip -4 addr flush dev $1 > /dev/null 2>&1
    ip link set $1 down > /dev/null 2>&1
    brctl delif br0 $1 > /dev/null 2>&1
}

readdif_to_br() {
    delif_from_br $1
    brctl addif br0 $1
    ip link set $1 up
}

# get params
getFirstWlanIfName
getSecWlanIfName
getLanIfName
getVpnIfName
getWanIfName
getTunIfName
getWanIpaddr
getWanReady
getVlanConfig
