#!/bin/sh

########################################################################################################################
# Template to wl command - onsole script tool for fast acces to AP/STA info
########################################################################################################################

# include kernel config
. /etc/scripts/config.sh

is_up=`ip -o link show $2 up`
if [ "$is_up" = "" ]; then
    echo ">>>>> Wifi interface $1 not up - exit <<<<<<<<<<"
    exit 0
fi

usage() {
  echo "Usage: $0 | showstat | showcalib | setmaxpwr " >&2
  echo "_____________________________________________________________________________________________________________________" >&2
  echo " " >&2
  echo " wl scan ra0 - scan and show result of wireless interface ra0" >&2
  echo " wl showstat  ra0 - show statistic of wireless interface ra0" >&2
  echo " wl showcalib ra0 - show fabric calibrations for wireless interface ra0" >&2
  echo "_____________________________________________________________________________________________________________________" >&2
 exit 1
}

scan()
{
    iwpriv $1 set SiteSurvey=1
    sleep 2
    iwpriv $1 get_site_survey
}

showstat()
{
    if [ "$1" = "" ]; then
	echo "Need iface name as argument."
	exit 1
    fi
    iwpriv $1 show stainfo
    iwpriv $1 show stacountinfo
    iwpriv $1 show stasecinfo
    iwpriv $1 show descinfo
    iwpriv $1 show wdsinfo
    iwpriv $1 show bainfo
    if [ "$CONFIG_RT2860V2_AP_IGMP_SNOOP" != "" ]|| [ "$CONFIG_MT76X2_AP_IGMP_SNOOP" != "" ]; then
	iwpriv $1 show igmpinfo
    fi
}

showcalib()
{
    if [ "$1" = "" ]; then
	echo "Need iface name as argument."
	exit 1
    fi
    iwpriv $1 e2p
}

main() {
  local cmd="$1"
  [ -z "$cmd" ] && usage
  shift
  case "$cmd" in
    scan)
      scan $@
      ;;
    showstat)
      showstat $@
      ;;
    showcalib)
      showcalib $@
      ;;
    *)
      usage $@
      ;;
  esac
}

main $@
