var WDS_NUM_MAX					= 4;
var MBSSID_MAX 					= 8;
var ACCESSPOLICYLIST_MAX			= 64;
var BSSID_NUM					= <% getBSSIDNum(); %>;
var MAX_STA_NUM					= <% getMaxStaNum(); %>;

var SDK_VERSION					= '<% getSdkVersion(); %>';
var PLATFORM					= '<% getPlatform(); %>';

var PRIMARY_DNS					= '<% getDns(1); %>';
var SECONDARY_DNS				= '<% getDns(2); %>';
var LAN_IP					= '<% getLanIp(); %>';
var LAN_NETMASK					= '<% getLanNetmask(); %>';

var ETHER_PORTS					= <% getEthernetPortCount(); %>;
var ETHER_FIRST_PORT				= (ETHER_PORTS == 3) ? 2 : 0;

var WLAN_CHANNEL_INDEX				= '<% getWlanChannel(); %>';
var WLAN_CHANNEL_INDEX_AC			= '<% getWlanChannelAC(); %>';

var BUILD_IPV6_6RD				= '<% getIPv66rdBuilt(); %>';
var BUILD_IPV6_TO4				= '<% getIP6to4Built(); %>';
var BUILD_RADVD					= '<% getRadvdBuilt(); %>';
var BUILD_DHCPV6				= '<% getDhcpv6Built(); %>';
var BUILD_LangEN				= '<% getLangBuilt("en"); %>'		== '1';
var BUILD_LangRU				= '<% getLangBuilt("ru"); %>'		== '1';
var BUILD_KABINET				= '<% getLANAUTHBuilt(); %>';
var BUILD_LDPC_SUPPORT				= '<% getLDPCBuilt(); %>';
var BUILD_VHT_STBC_SUPPORT			= '<% getVHTSTBCBuilt(); %>';
var BUILD_5GHZ_SUPPORT				= '<% is5gh_support(); %>'		== '1';
var BUILD_5GHZ_1T1R				= '<% is5gh_1t1r(); %>'			== '1';
var BUILD_GIGAPHY				= '<% gigaphy(); %>'			== '1';
var BUILD_DYNAMIC_ROUTING 			= '<% getDynamicRoutingBuilt(); %>'	== '1';
var BUILD_CHILLI				= '<% getChilliBuilt(); %>';
var BUILD_NODOG					= '<% getNoDogBuilt(); %>';
var BUILD_OPENSSL				= '<% getOpenSSLBuilt(); %>';
var BUILD_DATE					= '<% getDATEBuilt(); %>';
var BUILD_IGMPPROXY				= '<% getIgmpProxyBuilt(); %>'		== '1';
var BUILD_FASTPATH				= '<% getFastPathBuilt(); %>';
var BUILD_SMBFP					= '<% getSmbFPBuilt(); %>'		== '1';
var BUILD_TELNETD				= '<% getTelnetdBuilt(); %>'		== '1';
var BUILD_DNSMASQ				= '<% getDnsmasqBuilt(); %>'		== '1';
var BUILD_UPNP					= '<% getUpnpBuilt(); %>'		== '1';
var BUILD_ARPPT					= '<% getARPptBuilt(); %>'		== '1';
var BUILD_XUPNPD				= '<% getXupnpdBuilt(); %>'		== '1';
var BUILD_CDP					= '<% getCdpBuilt(); %>'		== '1';
var BUILD_LLTD					= '<% getLltdBuilt(); %>'		== '1';
var BUILD_LLDPD					= '<% getLldpdBuilt(); %>'		== '1';
var BUILD_SNMPD					= '<% getSNMPDBuilt(); %>'		== '1';
var BUILD_ARPWATCH				= '<% getARPwatchBuilt(); %>'		== '1';
var BUILD_SMP					= '<% getSMPBuilt(); %>'		== '1';
var BUILD_GW					= '<% getGWBuilt(); %>'			== '1';
var BUILD_WLANAPCLI				= '<% getWlanApcliBuilt(); %>'		== '1';
var BUILD_STATION				= '<% getStationBuilt(); %>'		== '1';
var BUILD_VPN 					= '<% getVPNBuilt(); %>';
var BUILD_IPV6					= '<% getIPv6Built(); %>';
var BUILD_WDS					= '<% getWDSBuilt(); %>';
var BUILD_USB					= '<% getUSBBuilt(); %>';
var BUILD_STORAGE				= '<% getStorageBuilt(); %>';
var BUILD_FTP					= '<% getFtpBuilt(); %>';
var BUILD_SMB					= '<% getSmbBuilt(); %>';
var BUILD_WEBSTR				= '<% getWebstrBuilt(); %>';
var BUILD_RADIUS				= '<% getRadiusBuilt(); %>';
var BUILD_CWMP					= '<% getCwmpBuilt(); %>';
var BUILD_PRINTER_SRV				= '<% getPrinterSrvBuilt(); %>';
var BUILD_USBMODEM				= '<% getUSBModemBuilt(); %>';
var BUILD_SYSLOG				= '<% getSysLogBuilt(); %>';
var BUILD_SWQOS					= '<% getSWQoSBuilt(); %>';
var BUILD_TRANSMISSION				= '<% getTransmissionBuilt(); %>';
var BUILD_IPTACCOUNT				= '<% getIPTAccountBuilt(); %>';
var BUILD_DDNS					= '<% getDDNSBuilt(); %>';
var BUILD_SPOT					= '<% getSpotBuilt(); %>';
var BUILD_8021X					= '<% get802_1XBuilt(); %>';
var BUILD_BANDSTEERING				= '<% getBandSteeringBuilt(); %>';
var BUILD_MBSSID				= '<% getMBSSIDBuilt(); %>';
var BUILD_WLAN_3T3R				= '<% is3t3r(); %>';
var BUILD_IDS_ENABLE				= '<% getIdsEnableBuilt(); %>';
var BUILD_TXBF					= '<% getTXBFBuilt(); %>';
var BUILD_DFS					= '<% getDFSBuilt(); %>';
var BUILD_RRM					= '<% getRRMBuilt(); %>';
var BUILD_FT					= '<% getFTBuilt(); %>';
var BUILD_EDCCA					= '<% getEDCCABuilt(); %>';
var BUILD_WLAN_M2U				= '<% getWlanM2UBuilt(); %>';
var BUILD_VIDEO_TURBINE				= '<% getVideoTurbineBuilt(); %>';
var BUILD_CLAMP					= '<% getClampBuilt(); %>';

var NVRAM_Login					= '<% getCfgGeneral(1, "Login"); %>';				NVRAM_Login				= (NVRAM_Login != '')				? NVRAM_Login				: 'Admin';
var NVRAM_Password				= '<% getCfgGeneral(1, "Password"); %>';			NVRAM_Password				= (NVRAM_Password!= '')				? NVRAM_Password			: 'Admin';
var NVRAM_AuthMode				= '<% getCfgGeneral(1, "AuthMode"); %>'; 			NVRAM_AuthMode				= (NVRAM_AuthMode!= '')				? NVRAM_AuthMode 			: 'OPEN';
var NVRAM_WPAPSK1				= '<% getCfgGeneral(1, "WPAPSK1"); %>';				NVRAM_WPAPSK1				= (NVRAM_WPAPSK1 != '')				? NVRAM_WPAPSK1				: '1234567890';
var NVRAM_OperationMode				= '<% getCfgGeneral(1, "OperationMode"); %>';			NVRAM_OperationMode 			= (NVRAM_OperationMode != '')			? NVRAM_OperationMode			: '1';
var NVRAM_offloadMode				= '<% getCfgGeneral(1, "offloadMode"); %>';			NVRAM_offloadMode			= (NVRAM_offloadMode != '')			? NVRAM_offloadMode			: '3';
var NVRAM_IPv6OpMode				= '<% getCfgGeneral(1, "IPv6OpMode"); %>';			NVRAM_IPv6OpMode			= (NVRAM_IPv6OpMode != '')			? NVRAM_IPv6OpMode			: '0';
var NVRAM_wan_port				= '<% getCfgGeneral(1, "wan_port"); %>';			NVRAM_wan_port				= (NVRAM_wan_port != '')			? NVRAM_wan_port			: '4';
var NVRAM_lan_port				= '<% getCfgGeneral(1, "lan_port"); %>';			NVRAM_lan_port				= (NVRAM_lan_port != '')			? NVRAM_lan_port			: 'near'
var NVRAM_stb_port				= '<% getCfgGeneral(1, "tv_port"); %>';				NVRAM_stb_port				= (NVRAM_stb_port != '')			? NVRAM_stb_port			: '0';
var NVRAM_sip_port				= '<% getCfgGeneral(1, "sip_port"); %>';			NVRAM_sip_port				= (NVRAM_sip_port != '')			? NVRAM_sip_port			: '0';
var NVRAM_KLogd					= '<% getCfgGeneral(1, "KLogd"); %>';				NVRAM_KLogd				= (NVRAM_KLogd != '')				? NVRAM_KLogd				: '1';
var NVRAM_SysLogd				= '<% getCfgGeneral(1, "SysLogd"); %>';				NVRAM_SysLogd				= (NVRAM_SysLogd != '')				? NVRAM_SysLogd				: '1';
var NVRAM_RemoteSysLogIP			= '<% getCfgGeneral(1, "RemoteSysLogIP"); %>';			NVRAM_RemoteSysLogIP			= (NVRAM_RemoteSysLogIP != '')			? NVRAM_RemoteSysLogIP			: '';
var NVRAM_fwAlgFTP				= '<% getCfgGeneral(1, "fwAlgFTP"); %>';			NVRAM_fwAlgFTP				= (NVRAM_fwAlgFTP != '')			? NVRAM_fwAlgFTP			: '1';
var NVRAM_fwAlgGRE				= '<% getCfgGeneral(1, "fwAlgGRE"); %>';			NVRAM_fwAlgGRE				= (NVRAM_fwAlgGRE != '')			? NVRAM_fwAlgGRE			: '0';
var NVRAM_fwAlgH323				= '<% getCfgGeneral(1, "fwAlgH323"); %>';			NVRAM_fwAlgH323				= (NVRAM_fwAlgH323 != '')			? NVRAM_fwAlgH323			: '0';
var NVRAM_fwAlgIPSec				= '<% getCfgGeneral(1, "fwAlgIPSec"); %>';			NVRAM_fwAlgIPSec			= (NVRAM_fwAlgIPSec != '')			? NVRAM_fwAlgIPSec			: '0';
var NVRAM_fwAlgL2TP				= '<% getCfgGeneral(1, "fwAlgL2TP"); %>';			NVRAM_fwAlgL2TP				= (NVRAM_fwAlgL2TP != '')			? NVRAM_fwAlgL2TP			: '0';
var NVRAM_fwAlgPPTP				= '<% getCfgGeneral(1, "fwAlgPPTP"); %>';			NVRAM_fwAlgPPTP				= (NVRAM_fwAlgPPTP != '')			? NVRAM_fwAlgPPTP			: '0';
var NVRAM_fwAlgSIP				= '<% getCfgGeneral(1, "fwAlgSIP"); %>';			NVRAM_fwAlgSIP				= (NVRAM_fwAlgSIP != '')			? NVRAM_fwAlgSIP			: '0';
var NVRAM_fwAlgRTSP				= '<% getCfgGeneral(1, "fwAlgRTSP"); %>';			NVRAM_fwAlgRTSP				= (NVRAM_fwAlgRTSP != '')			? NVRAM_fwAlgRTSP			: '0';
var NVRAM_websFilterProxy			= '<% getCfgGeneral(1, "websFilterProxy"); %>';			NVRAM_websFilterProxy			= (NVRAM_websFilterProxy != '')			? NVRAM_websFilterProxy			: '0';
var NVRAM_websFilterJava			= '<% getCfgGeneral(1, "websFilterJava"); %>';			NVRAM_websFilterJava			= (NVRAM_websFilterJava != '')			? NVRAM_websFilterJava			: '0';
var NVRAM_websFilterActivex			= '<% getCfgGeneral(1, "websFilterActivex"); %>';		NVRAM_websFilterActivex			= (NVRAM_websFilterActivex != '')		? NVRAM_websFilterActivex		: '0';
var NVRAM_websFilterCookies			= '<% getCfgGeneral(1, "websFilterCookies"); %>';		NVRAM_websFilterCookies			= (NVRAM_websFilterCookies != '')		? NVRAM_websFilterCookies		: '0';
var NVRAM_websURLFilters			= '<% getCfgGeneral(1, "websURLFilters"); %>';			NVRAM_websURLFilters			= (NVRAM_websURLFilters != '')			? NVRAM_websURLFilters			: '';
var NVRAM_websHostFilters			= '<% getCfgGeneral(1, "websHostFilters"); %>';			NVRAM_websHostFilters			= (NVRAM_websHostFilters != '')			? NVRAM_websHostFilters			: '';
var NVRAM_DMZEnable				= '<% getCfgGeneral(1, "DMZEnable"); %>';			NVRAM_DMZEnable				= (NVRAM_DMZEnable != '')			? NVRAM_DMZEnable			: '0';
var NVRAM_DMZNATLoopback			= '<% getCfgGeneral(1, "DMZNATLoopback"); %>';			NVRAM_DMZNATLoopback			= (NVRAM_DMZNATLoopback !='')			? NVRAM_DMZNATLoopback			: '0';
var NVRAM_DMZIPAddress				= '<% getCfgGeneral(1, "DMZIPAddress"); %>';			NVRAM_DMZIPAddress			= (NVRAM_DMZIPAddress !='')			? NVRAM_DMZIPAddress			: '';
var NVRAM_PortForwardEnable			= '<% getCfgGeneral(1, "PortForwardEnable"); %>';		NVRAM_PortForwardEnable			= (NVRAM_PortForwardEnable !='')		? NVRAM_PortForwardEnable		: '0';
var NVRAM_IPPortFilterEnable			= '<% getCfgGeneral(1, "IPPortFilterEnable"); %>';		NVRAM_IPPortFilterEnable		= (NVRAM_IPPortFilterEnable !='')		? NVRAM_IPPortFilterEnable		: '0';
var NVRAM_IPPortFilterInputEnable		= '<% getCfgGeneral(1, "IPPortFilterInputEnable"); %>';		NVRAM_IPPortFilterInputEnable		= (NVRAM_IPPortFilterInputEnable !='')		? NVRAM_IPPortFilterInputEnable		: '0';
var NVRAM_ForwardSesLimit			= '<% getCfgGeneral(1, "ForwardSesLimit"); %>';			NVRAM_ForwardSesLimit			= (NVRAM_ForwardSesLimit !='')			? NVRAM_ForwardSesLimit			: '0';
var NVRAM_dnsToLocalRedir			= '<% getCfgGeneral(1, "dnsToLocalRedir"); %>';			NVRAM_dnsToLocalRedir			= (NVRAM_dnsToLocalRedir !='')			? NVRAM_dnsToLocalRedir			: '0';
var NVRAM_dnsPEnabled				= '<% getCfgGeneral(1, "dnsPEnabled"); %>';			NVRAM_dnsPEnabled			= (NVRAM_dnsPEnabled !='')			? NVRAM_dnsPEnabled			: '1';
var NVRAM_port1_swmode				= '<% getCfgGeneral(1, "port1_swmode"); %>';			NVRAM_port1_swmode			= (NVRAM_port1_swmode !='')			? NVRAM_port1_swmode			: 'auto';
var NVRAM_port2_swmode				= '<% getCfgGeneral(1, "port2_swmode"); %>';			NVRAM_port2_swmode			= (NVRAM_port2_swmode !='')			? NVRAM_port2_swmode			: 'auto';
var NVRAM_port3_swmode				= '<% getCfgGeneral(1, "port3_swmode"); %>';			NVRAM_port3_swmode			= (NVRAM_port3_swmode !='')			? NVRAM_port3_swmode			: 'auto';
var NVRAM_port4_swmode				= '<% getCfgGeneral(1, "port4_swmode"); %>';			NVRAM_port4_swmode			= (NVRAM_port4_swmode !='')			? NVRAM_port4_swmode			: 'auto';
var NVRAM_port5_swmode				= '<% getCfgGeneral(1, "port5_swmode"); %>';			NVRAM_port5_swmode			= (NVRAM_port5_swmode !='')			? NVRAM_port5_swmode			: 'auto';
var NVRAM_port1_fcmode				= '<% getCfgGeneral(1, "port1_fcmode"); %>';			NVRAM_port1_fcmode			= (NVRAM_port1_fcmode !='')			? NVRAM_port1_fcmode			: 'off';
var NVRAM_port2_fcmode				= '<% getCfgGeneral(1, "port2_fcmode"); %>';			NVRAM_port2_fcmode			= (NVRAM_port2_fcmode !='')			? NVRAM_port2_fcmode			: 'off';
var NVRAM_port3_fcmode				= '<% getCfgGeneral(1, "port3_fcmode"); %>';			NVRAM_port3_fcmode			= (NVRAM_port3_fcmode !='')			? NVRAM_port3_fcmode			: 'off';
var NVRAM_port4_fcmode				= '<% getCfgGeneral(1, "port4_fcmode"); %>';			NVRAM_port4_fcmode			= (NVRAM_port4_fcmode !='')			? NVRAM_port4_fcmode			: 'off';
var NVRAM_port5_fcmode				= '<% getCfgGeneral(1, "port5_fcmode"); %>';			NVRAM_port5_fcmode			= (NVRAM_port5_fcmode !='')			? NVRAM_port5_fcmode			: 'off';
var NVRAM_wanConnectionMode			= '<% getCfgGeneral(1, "wanConnectionMode"); %>';		NVRAM_wanConnectionMode			= (NVRAM_wanConnectionMode !='')		? NVRAM_wanConnectionMode		: 'DHCP';
var NVRAM_natEnabled				= '<% getCfgGeneral(1, "natEnabled"); %>';			NVRAM_natEnabled			= (NVRAM_natEnabled !='')			? NVRAM_natEnabled			: '1';
var NVRAM_wan_static_dns			= '<% getCfgGeneral(1, "wan_static_dns"); %>';			NVRAM_wan_static_dns			= (NVRAM_wan_static_dns !='')			? NVRAM_wan_static_dns			: 'off';
var NVRAM_wan_manual_mtu			= '<% getCfgGeneral(1, "wan_manual_mtu"); %>';			NVRAM_wan_manual_mtu			= (NVRAM_wan_manual_mtu !='')			? NVRAM_wan_manual_mtu			: '0';
var NVRAM_wan_ipaddr				= '<% getCfgGeneral(1, "wan_ipaddr"); %>';			NVRAM_wan_ipaddr			= (NVRAM_wan_ipaddr !='')			? NVRAM_wan_ipaddr			: '';
var NVRAM_lan_ipaddr				= '<% getCfgGeneral(1, "lan_ipaddr"); %>';			NVRAM_lan_ipaddr			= (NVRAM_lan_ipaddr !='')			? NVRAM_lan_ipaddr			: '192.168.1.1';
var NVRAM_wan_netmask				= '<% getCfgGeneral(1, "wan_netmask"); %>';			NVRAM_wan_netmask			= (NVRAM_wan_netmask !='')			? NVRAM_wan_netmask			: '';	
var NVRAM_wan_gateway				= '<% getCfgGeneral(1, "wan_gateway"); %>';			NVRAM_wan_gateway			= (NVRAM_wan_gateway !='')			? NVRAM_wan_gateway			: '';
var NVRAM_dhcpRequestIP				= '<% getCfgGeneral(1, "dhcpRequestIP"); %>';			NVRAM_dhcpRequestIP			= (NVRAM_dhcpRequestIP !='')			? NVRAM_dhcpRequestIP			: '';
var NVRAM_dhcpVendorClass			= '<% getCfgGeneral(1, "dhcpVendorClass"); %>';			NVRAM_dhcpVendorClass			= (NVRAM_dhcpVendorClass !='')			? NVRAM_dhcpVendorClass			: '';
var NVRAM_wan_static_dns_profile		= '<% getCfgGeneral(1, "wan_static_dns_profile"); %>';		NVRAM_wan_static_dns_profile		= (NVRAM_wan_static_dns_profile !='')		? NVRAM_wan_static_dns_profile		: 'manual';
var NVRAM_wan_static_dns_profile_yandex		= '<% getCfgGeneral(1, "wan_static_dns_profile_yandex"); %>';	NVRAM_wan_static_dns_profile_yandex	= (NVRAM_wan_static_dns_profile_yandex !='')	? NVRAM_wan_static_dns_profile_yandex	: 'basic';
var NVRAM_wan_static_dns_profile_adguard	= '<% getCfgGeneral(1, "wan_static_dns_profile_adguard"); %>';	NVRAM_wan_static_dns_profile_adguard	= (NVRAM_wan_static_dns_profile_adguard !='')	? NVRAM_wan_static_dns_profile_adguard	: 'default';
var NVRAM_WAN_MAC_ADDR				= '<% getCfgGeneral(1, "WAN_MAC_ADDR"); %>';			NVRAM_WAN_MAC_ADDR			= (NVRAM_WAN_MAC_ADDR !='')			? NVRAM_WAN_MAC_ADDR.toUpperCase()	: '00:0C:43:30:52:62';
var NVRAM_vpnEnabled				= '<% getCfgGeneral(1, "vpnEnabled"); %>';			NVRAM_vpnEnabled			= (NVRAM_vpnEnabled !='')			? NVRAM_vpnEnabled			: 'off';
var NVRAM_vpnType				= '<% getCfgGeneral(1, "vpnType"); %>';				NVRAM_vpnType				= (NVRAM_vpnType !='')				? NVRAM_vpnType				: '0';
var NVRAM_vpnServer				= '<% getCfgGeneral(1, "vpnServer"); %>';			NVRAM_vpnServer				= (NVRAM_vpnServer !='')			? NVRAM_vpnServer			: '';
var NVRAM_vpnInterface				= '<% getCfgGeneral(1, "vpnInterface"); %>';			NVRAM_vpnInterface			= (NVRAM_vpnInterface !='')			? NVRAM_vpnInterface			: 'WAN';
var NVRAM_vpnMPPE				= '<% getCfgGeneral(1, "vpnMPPE"); %>';				NVRAM_vpnMPPE				= (NVRAM_vpnMPPE !='')				? NVRAM_vpnMPPE				: 'off';
var NVRAM_vpnPeerDNS				= '<% getCfgGeneral(1, "vpnPeerDNS"); %>';			NVRAM_vpnPeerDNS			= (NVRAM_vpnPeerDNS !='')			? NVRAM_vpnPeerDNS			: 'on';
var NVRAM_vpnDebug				= '<% getCfgGeneral(1, "vpnDebug"); %>';			NVRAM_vpnDebug				= (NVRAM_vpnDebug !='')				? NVRAM_vpnDebug			: 'off';
var NVRAM_vpnNAT				= '<% getCfgGeneral(1, "vpnNAT"); %>';				NVRAM_vpnNAT				= (NVRAM_vpnNAT !='')				? NVRAM_vpnNAT				: 'on';
var NVRAM_vpnDGW				= '<% getCfgGeneral(1, "vpnDGW"); %>';				NVRAM_vpnDGW				= (NVRAM_vpnDGW !='')				? NVRAM_vpnDGW				: '1';
var NVRAM_vpnAuthProtocol			= '<% getCfgGeneral(1, "vpnAuthProtocol"); %>';			NVRAM_vpnAuthProtocol			= (NVRAM_vpnAuthProtocol !='')			? NVRAM_vpnAuthProtocol			: '0';
var NVRAM_vpnEnableLCP				= '<% getCfgGeneral(1, "vpnEnableLCP"); %>';			NVRAM_vpnEnableLCP			= (NVRAM_vpnEnableLCP !='')			? NVRAM_vpnEnableLCP			: 'on';
var NVRAM_vpnPurePPPOE				= '<% getCfgGeneral(1, "vpnPurePPPOE"); %>';			NVRAM_vpnPurePPPOE			= (NVRAM_vpnPurePPPOE !='')			? NVRAM_vpnPurePPPOE			: '0';
var NVRAM_vpnLCPFailure				= '<% getCfgGeneral(1, "vpnLCPFailure"); %>';			NVRAM_vpnLCPFailure			= (NVRAM_vpnLCPFailure !='')			? NVRAM_vpnLCPFailure			: '10';
var NVRAM_vpnLCPInterval			= '<% getCfgGeneral(1, "vpnLCPInterval"); %>';			NVRAM_vpnLCPInterval			= (NVRAM_vpnLCPInterval !='')			? NVRAM_vpnLCPInterval			: '25';
var NVRAM_vpnTestReachable			= '<% getCfgGeneral(1, "vpnTestReachable"); %>';		NVRAM_vpnTestReachable			= (NVRAM_vpnTestReachable !='')			? NVRAM_vpnTestReachable		: '1';
var NVRAM_LANAUTH_LVL				= '<% getCfgGeneral(1, "LANAUTH_LVL"); %>';			NVRAM_LANAUTH_LVL			= (NVRAM_LANAUTH_LVL !='')			? NVRAM_LANAUTH_LVL			: '2';
var NVRAM_vpnMTU				= '<% getCfgGeneral(1, "vpnMTU"); %>';				NVRAM_vpnMTU				= (NVRAM_vpnMTU !='')				? NVRAM_vpnMTU				: 'AUTO';
var NVRAM_vpnUser 				= '<% getCfgGeneral(1, "vpnUser"); %>';				NVRAM_vpnUser				= (NVRAM_vpnUser !='')				? NVRAM_vpnUser				: 'vpn_user';
var NVRAM_vpnPassword				= '<% getCfgGeneral(1, "vpnPassword"); %>';			NVRAM_vpnPassword			= (NVRAM_vpnPassword !='')			? NVRAM_vpnPassword			: 'vpn_password';
var NVRAM_vpnService				= '<% getCfgGeneral(1, "vpnService"); %>';			NVRAM_vpnService			= (NVRAM_vpnService !='')			? NVRAM_vpnService			: '';
var NVRAM_tv_portVLAN				= '<% getCfgGeneral(1, "tv_portVLAN"); %>';			NVRAM_tv_portVLAN			= (NVRAM_tv_portVLAN !='')			? NVRAM_tv_portVLAN			: '';
var NVRAM_tv_portVLANPRIO			= '<% getCfgGeneral(1, "tv_portVLANPRIO"); %>';			NVRAM_tv_portVLANPRIO			= (NVRAM_tv_portVLANPRIO !='')			? NVRAM_tv_portVLANPRIO			: '';
var NVRAM_sip_portVLAN				= '<% getCfgGeneral(1, "sip_portVLAN"); %>';			NVRAM_sip_portVLAN			= (NVRAM_sip_portVLAN !='')			? NVRAM_sip_portVLAN			: '';
var NVRAM_sip_portVLANPRIO			= '<% getCfgGeneral(1, "sip_portVLANPRIO"); %>';		NVRAM_sip_portVLANPRIO			= (NVRAM_sip_portVLANPRIO !='')			? NVRAM_sip_portVLANPRIO		: '';
var NVRAM_VlanWifiLan				= '<% getCfgGeneral(1, "VlanWifiLan"); %>';			NVRAM_VlanWifiLan			= (NVRAM_VlanWifiLan !='')			? NVRAM_VlanWifiLan			: '';
var NVRAM_VlanWifiLanINIC			= '<% getCfgGeneral(1, "VlanWifiLanINIC"); %>';			NVRAM_VlanWifiLanINIC			= (NVRAM_VlanWifiLanINIC != '')			? NVRAM_VlanWifiLanINIC			: '';
var NVRAM_VlanWifiWan				= '<% getCfgGeneral(1, "VlanWifiWan"); %>';			NVRAM_VlanWifiWan			= (NVRAM_VlanWifiWan != '')			? NVRAM_VlanWifiWan			: '';
var NVRAM_VlanWifiWanINIC			= '<% getCfgGeneral(1, "VlanWifiWanINIC"); %>';			NVRAM_VlanWifiWanINIC			= (NVRAM_VlanWifiWanINIC != '')			? NVRAM_VlanWifiWanINIC			: '';
var NVRAM_BssidIfName				= '<% getCfgGeneral(1, "BssidIfName"); %>';			NVRAM_BssidIfName			= (NVRAM_BssidIfName != '')			? NVRAM_BssidIfName			: 'ra';
var NVRAM_BssidNum				= '<% getCfgGeneral(1, "BssidNum"); %>';			NVRAM_BssidNum				= (NVRAM_BssidNum != '')			? NVRAM_BssidNum			: '1';
var NVRAM_VlanLan				= '<% getCfgGeneral(1, "VlanLan"); %>';				NVRAM_VlanLan				= (NVRAM_VlanLan != '')				? NVRAM_VlanLan				: '';
var NVRAM_VlanLanIsolate			= '<% getCfgGeneral(1, "VlanLanIsolate"); %>';			NVRAM_VlanLanIsolate			= (NVRAM_VlanLanIsolate !='')			? NVRAM_VlanLanIsolate			: '';
var NVRAM_RIPEnable				= '<% getCfgGeneral(1, "RIPEnable"); %>';			NVRAM_RIPEnable				= (NVRAM_RIPEnable !='')			? NVRAM_RIPEnable			: '0';
var NVRAM_QoSEnable				= '<% getCfgGeneral(1, "QoSEnable"); %>';			NVRAM_QoSEnable				= (NVRAM_QoSEnable !='')			? NVRAM_QoSEnable			: '0';
var NVRAM_QoSMode				= '<% getCfgGeneral(1, "QoSMode"); %>';				NVRAM_QoSMode				= (NVRAM_QoSMode !='')				? NVRAM_QoSMode				: '0';
var NVRAM_QoS_rate_up				= '<% getCfgGeneral(1, "QoS_rate_up"); %>';			NVRAM_QoS_rate_up			= (NVRAM_QoS_rate_up !='')			? NVRAM_QoS_rate_up			: '90000';
var NVRAM_QoS_rate_limit_up			= '<% getCfgGeneral(1, "QoS_rate_limit_up"); %>';		NVRAM_QoS_rate_limit_up			= (NVRAM_QoS_rate_limit_up !='')		? NVRAM_QoS_rate_limit_up		: '80000';
var NVRAM_QoS_rate_down				= '<% getCfgGeneral(1, "QoS_rate_down"); %>';			NVRAM_QoS_rate_down			= (NVRAM_QoS_rate_down !='')			? NVRAM_QoS_rate_down			: '90000';
var NVRAM_QoS_rate_limit_down			= '<% getCfgGeneral(1, "QoS_rate_limit_down"); %>';		NVRAM_QoS_rate_limit_down		= (NVRAM_QoS_rate_limit_down !='')		? NVRAM_QoS_rate_limit_down		: '80000';
var NVRAM_QoS_rate_vpn_up			= '<% getCfgGeneral(1, "QoS_rate_vpn_up"); %>';			NVRAM_QoS_rate_vpn_up			= (NVRAM_QoS_rate_vpn_up !='')			? NVRAM_QoS_rate_vpn_up			: '70000';
var NVRAM_QoS_rate_vpn_limit_up			= '<% getCfgGeneral(1, "QoS_rate_vpn_limit_up"); %>';		NVRAM_QoS_rate_vpn_limit_up		= (NVRAM_QoS_rate_vpn_limit_up !='')		? NVRAM_QoS_rate_vpn_limit_up		: '60000';
var NVRAM_QoS_rate_mdm_up			= '<% getCfgGeneral(1, "QoS_rate_mdm_up"); %>';			NVRAM_QoS_rate_mdm_up			= (NVRAM_QoS_rate_mdm_up !='')			? NVRAM_QoS_rate_mdm_up			: '30000';
var NVRAM_QoS_rate_mdm_limit_up			= '<% getCfgGeneral(1, "QoS_rate_mdm_limit_up"); %>';		NVRAM_QoS_rate_mdm_limit_up		= (NVRAM_QoS_rate_mdm_limit_up !='')		? NVRAM_QoS_rate_mdm_limit_up		: '10000';
var NVRAM_QoS_high_pp				= '<% getCfgGeneral(1, "QoS_high_pp"); %>';			NVRAM_QoS_high_pp			= (NVRAM_QoS_high_pp !='')			? NVRAM_QoS_high_pp			: '1720 4190 5060 5190 5191 5192 5193 5222 5223 5269 5270';
var NVRAM_QoS_low_pp				= '<% getCfgGeneral(1, "QoS_low_pp"); %>';			NVRAM_QoS_low_pp			= (NVRAM_QoS_low_pp !='')			? NVRAM_QoS_low_pp			: '20 25 21 8010';
var NVRAM_QoS_high_dscp				= '<% getCfgGeneral(1, "QoS_high_dscp"); %>';			NVRAM_QoS_high_dscp			= (NVRAM_QoS_high_dscp !='')			? NVRAM_QoS_high_dscp			: 'EF';
var NVRAM_QoS_low_dscp				= '<% getCfgGeneral(1, "QoS_low_dscp"); %>';			NVRAM_QoS_low_dscp			= (NVRAM_QoS_low_dscp !='')			? NVRAM_QoS_low_dscp			: '';
var NVRAM_HostName				= '<% getCfgGeneral(1, "HostName"); %>';			NVRAM_HostName				= (NVRAM_HostName !='')				? NVRAM_HostName			: 'Wive-NG-MT';
var NVRAM_dhcpEnabled				= '<% getCfgGeneral(1, "dhcpEnabled"); %>';			NVRAM_dhcpEnabled			= (NVRAM_dhcpEnabled !='')			? NVRAM_dhcpEnabled			: '1';
var NVRAM_dhcpStart				= '<% getCfgGeneral(1, "dhcpStart"); %>';			NVRAM_dhcpStart				= (NVRAM_dhcpStart !='')			? NVRAM_dhcpStart			: '192.168.1.2';
var NVRAM_dhcpEnd				= '<% getCfgGeneral(1, "dhcpEnd"); %>';				NVRAM_dhcpEnd				= (NVRAM_dhcpEnd !='')				? NVRAM_dhcpEnd				: '192.168.1.254';
var NVRAM_dhcpGateway				= '<% getCfgGeneral(1, "dhcpGateway"); %>';			NVRAM_dhcpGateway			= (NVRAM_dhcpGateway !='')			? NVRAM_dhcpGateway			: '192.168.1.1';
var NVRAM_Ipv6InVPN				= '<% getCfgGeneral(1, "Ipv6InVPN"); %>';			NVRAM_Ipv6InVPN				= (NVRAM_Ipv6InVPN !='')			? NVRAM_Ipv6InVPN			: '0';
var NVRAM_IPv6Dhcpc				= '<% getCfgGeneral(1, "IPv6Dhcpc"); %>';			NVRAM_IPv6Dhcpc				= (NVRAM_IPv6Dhcpc !='')			? NVRAM_IPv6Dhcpc			: '1';
var NVRAM_IPv6AllowForward			= '<% getCfgGeneral(1, "IPv6AllowForward"); %>';		NVRAM_IPv6AllowForward			= (NVRAM_IPv6AllowForward !='')			? NVRAM_IPv6AllowForward		: '0';
var NVRAM_radvdEnabled				= '<% getCfgGeneral(1, "radvdEnabled"); %>';			NVRAM_radvdEnabled			= (NVRAM_radvdEnabled !='')			? NVRAM_radvdEnabled			: '0';
var NVRAM_dhcpv6Enabled				= '<% getCfgGeneral(1, "dhcpv6Enabled"); %>';			NVRAM_dhcpv6Enabled			= (NVRAM_dhcpv6Enabled !='')			? NVRAM_dhcpv6Enabled			: '0';
var NVRAM_IPv6ManualMTU				= '<% getCfgGeneral(1, "IPv6ManualMTU"); %>';			NVRAM_IPv6ManualMTU			= (NVRAM_IPv6ManualMTU !='')			? NVRAM_IPv6ManualMTU			: '0';
var NVRAM_IPv6OpMode				= '<% getCfgGeneral(1, "IPv6OpMode"); %>';			NVRAM_IPv6OpMode			= (NVRAM_IPv6OpMode !='')			? NVRAM_IPv6OpMode			: '0';
var NVRAM_IPv6IPAddr				= '<% getCfgGeneral(1, "IPv6IPAddr"); %>';			NVRAM_IPv6IPAddr			= (NVRAM_IPv6IPAddr !='')			? NVRAM_IPv6IPAddr			: '2a02:2560';
var NVRAM_IPv6PrefixLen				= '<% getCfgGeneral(1, "IPv6PrefixLen"); %>';			NVRAM_IPv6PrefixLen			= (NVRAM_IPv6PrefixLen !='')			? NVRAM_IPv6PrefixLen			: '32';
var NVRAM_IPv6WANIPAddr				= '<% getCfgGeneral(1, "IPv6WANIPAddr"); %>';			NVRAM_IPv6WANIPAddr			= (NVRAM_IPv6WANIPAddr !='')			? NVRAM_IPv6WANIPAddr			: '';
var NVRAM_IPv6WANPrefixLen			= '<% getCfgGeneral(1, "IPv6WANPrefixLen"); %>';		NVRAM_IPv6WANPrefixLen			= (NVRAM_IPv6WANPrefixLen !='')			? NVRAM_IPv6WANPrefixLen		: '';
var NVRAM_IPv6GWAddr				= '<% getCfgGeneral(1, "IPv6GWAddr"); %>';			NVRAM_IPv6GWAddr			= (NVRAM_IPv6GWAddr !='')			? NVRAM_IPv6GWAddr			: '';
var NVRAM_IPv6DNSPrimary			= '<% getCfgGeneral(1, "IPv6DNSPrimary"); %>';			NVRAM_IPv6DNSPrimary			= (NVRAM_IPv6DNSPrimary !='')			? NVRAM_IPv6DNSPrimary			: '2001:4860:4860::8888';
var NVRAM_IPv6DNSSecondary			= '<% getCfgGeneral(1, "IPv6DNSSecondary"); %>';		NVRAM_IPv6DNSSecondary			= (NVRAM_IPv6DNSSecondary !='')			? NVRAM_IPv6DNSSecondary		: '2001:4860:4860::4444';
var NVRAM_IPv6SrvAddr				= '<% getCfgGeneral(1, "IPv6SrvAddr"); %>';			NVRAM_IPv6SrvAddr			= (NVRAM_IPv6SrvAddr !='')			? NVRAM_IPv6SrvAddr			: '192.88.99.1';
var NVRAM_chilli_enable				= '<% getCfgGeneral(1, "chilli_enable"); %>';			NVRAM_chilli_enable			= (NVRAM_chilli_enable !='')			? NVRAM_chilli_enable			: 'off';
var NVRAM_chilli_profile			= '<% getCfgGeneral(1, "chilli_profile"); %>';			NVRAM_chilli_profile			= (NVRAM_chilli_profile !='')			? NVRAM_chilli_profile			: '';
var NVRAM_chilli_dhcpstart			= '<% getCfgGeneral(1, "chilli_dhcpstart"); %>';		NVRAM_chilli_dhcpstart			= (NVRAM_chilli_dhcpstart !='')			? NVRAM_chilli_dhcpstart		: '0';
var NVRAM_chilli_dhcpend			= '<% getCfgGeneral(1, "chilli_dhcpend"); %>';			NVRAM_chilli_dhcpend			= (NVRAM_chilli_dhcpend !='') 			? NVRAM_chilli_dhcpend			: '0';
var NVRAM_chilli_dns1				= '<% getCfgGeneral(1, "chilli_dns1"); %>';			NVRAM_chilli_dns1			= (NVRAM_chilli_dns1 !='')			? NVRAM_chilli_dns1			: '192.168.182.1';
var NVRAM_chilli_dns2				= '<% getCfgGeneral(1, "chilli_dns2"); %>';			NVRAM_chilli_dns2			= (NVRAM_chilli_dns2 !='')			? NVRAM_chilli_dns2			: '192.168.182.1';
var NVRAM_chilli_domain				= '<% getCfgGeneral(1, "chilli_domain"); %>';			NVRAM_chilli_domain			= (NVRAM_chilli_domain !='')			? NVRAM_chilli_domain			: 'Wive-NG-MT.lo';
var NVRAM_chilli_lease				= '<% getCfgGeneral(1, "chilli_lease"); %>';			NVRAM_chilli_lease			= (NVRAM_chilli_lease !='')			? NVRAM_chilli_lease			: '300';
var NVRAM_chilli_radiusserver1			= '<% getCfgGeneral(1, "chilli_radiusserver1"); %>';		NVRAM_chilli_radiusserver1		= (NVRAM_chilli_radiusserver1 !='')		? NVRAM_chilli_radiusserver1		: '192.168.254.254';
var NVRAM_chilli_radiusserver2			= '<% getCfgGeneral(1, "chilli_radiusserver2"); %>';		NVRAM_chilli_radiusserver2		= (NVRAM_chilli_radiusserver2 !='')		? NVRAM_chilli_radiusserver2		: '192.168.254.254';
var NVRAM_chilli_radiussecret			= '<% getCfgGeneral(1, "chilli_radiussecret"); %>';		NVRAM_chilli_radiussecret		= (NVRAM_chilli_radiussecret !='')		? NVRAM_chilli_radiussecret		: 'ratest';
var NVRAM_chilli_radiusnasid			= '<% getCfgGeneral(1, "chilli_radiusnasid"); %>';		NVRAM_chilli_radiusnasid		= (NVRAM_chilli_radiusnasid !='')		? NVRAM_chilli_radiusnasid		: 'nas01';
var NVRAM_chilli_radiuslocationid		= '<% getCfgGeneral(1, "chilli_radiuslocationid"); %>';		NVRAM_chilli_radiuslocationid		= (NVRAM_chilli_radiuslocationid !='')		? NVRAM_chilli_radiuslocationid		: '1';
var NVRAM_chilli_radiuslocationname		= '<% getCfgGeneral(1, "chilli_radiuslocationname"); %>';	NVRAM_chilli_radiuslocationname		= (NVRAM_chilli_radiuslocationname !='')	? NVRAM_chilli_radiuslocationname	: 'Wive-NG-MT.lo';
var NVRAM_chilli_coaport			= '<% getCfgGeneral(1, "chilli_coaport"); %>';			NVRAM_chilli_coaport			= (NVRAM_chilli_coaport !='')			? NVRAM_chilli_coaport			: '3779';
var NVRAM_chilli_coanoipcheck			= '<% getCfgGeneral(1, "chilli_coanoipcheck"); %>';		NVRAM_chilli_coanoipcheck		= (NVRAM_chilli_coanoipcheck !='')		? NVRAM_chilli_coanoipcheck		: '1';
var NVRAM_chilli_uamserver			= '<% getCfgGeneral(1, "chilli_uamserver"); %>';		NVRAM_chilli_uamserver			= (NVRAM_chilli_uamserver !='')			? NVRAM_chilli_uamserver		: 'http://192.168.254.254';
var NVRAM_chilli_uamhomepage			= '<% getCfgGeneral(1, "chilli_uamhomepage"); %>';		NVRAM_chilli_uamhomepage		= (NVRAM_chilli_uamhomepage !='')		? NVRAM_chilli_uamhomepage		: '';
var NVRAM_chilli_uamsecret			= '<% getCfgGeneral(1, "chilli_uamsecret"); %>';		NVRAM_chilli_uamsecret			= (NVRAM_chilli_uamsecret !='')			? NVRAM_chilli_uamsecret		: 'test';
var NVRAM_chilli_uamallowed			= '<% getCfgGeneral(1, "chilli_uamallowed"); %>';		NVRAM_chilli_uamallowed			= (NVRAM_chilli_uamallowed !='')		? NVRAM_chilli_uamallowed		: '';
var NVRAM_chilli_uamdomain			= '<% getCfgGeneral(1, "chilli_uamdomain"); %>';		NVRAM_chilli_uamdomain			= (NVRAM_chilli_uamdomain !='')			? NVRAM_chilli_uamdomain		: '';
var NVRAM_chilli_uamanydns			= '<% getCfgGeneral(1, "chilli_uamanydns"); %>';		NVRAM_chilli_uamanydns			= (NVRAM_chilli_uamanydns !='')			? NVRAM_chilli_uamanydns		: '1';
var NVRAM_chilli_macallowed			= '<% getCfgGeneral(1, "chilli_macallowed"); %>';		NVRAM_chilli_macallowed			= (NVRAM_chilli_macallowed !='')		? NVRAM_chilli_macallowed		: '';
var NVRAM_chilli_clisolate			= '<% getCfgGeneral(1, "chilli_clisolate"); %>';		NVRAM_chilli_clisolate			= (NVRAM_chilli_clisolate !='')			? NVRAM_chilli_clisolate		: '0';
var NVRAM_chilli_dnsparanoia			= '<% getCfgGeneral(1, "chilli_dnsparanoia"); %>';		NVRAM_chilli_dnsparanoia		= (NVRAM_chilli_dnsparanoia !='')		? NVRAM_chilli_dnsparanoia		: '0';
var NVRAM_chilli_maxclients			= '<% getCfgGeneral(1, "chilli_maxclients"); %>';		NVRAM_chilli_maxclients			= (NVRAM_chilli_maxclients !='')		? NVRAM_chilli_maxclients		: '384';
var NVRAM_chilli_https				= '<% getCfgGeneral(1, "chilli_https"); %>';			NVRAM_chilli_https			= (NVRAM_chilli_https !='')			? NVRAM_chilli_https			: '0';
var NVRAM_nodogsplash_enable			= '<% getCfgGeneral(1, "nodogsplash_enable"); %>';		NVRAM_nodogsplash_enable		= (NVRAM_nodogsplash_enable !='')		? NVRAM_nodogsplash_enable		: '0';
var NVRAM_nodog_AuthenticateImmediately		= '<% getCfgGeneral(1, "nodog_AuthenticateImmediately"); %>';	NVRAM_nodog_AuthenticateImmediately	= (NVRAM_nodog_AuthenticateImmediately !='')	? NVRAM_nodog_AuthenticateImmediately	: '0';
var NVRAM_nodog_MACMechanism			= '<% getCfgGeneral(1, "nodog_MACMechanism"); %>';		NVRAM_nodog_MACMechanism		= (NVRAM_nodog_MACMechanism !='')		? NVRAM_nodog_MACMechanism		: 'block';
var NVRAM_nodog_PasswordAuthentication		= '<% getCfgGeneral(1, "nodog_PasswordAuthentication"); %>';	NVRAM_nodog_PasswordAuthentication	= (NVRAM_nodog_PasswordAuthentication !='')	? NVRAM_nodog_PasswordAuthentication	: '0';
var NVRAM_nodog_UsernameAuthentication		= '<% getCfgGeneral(1, "nodog_UsernameAuthentication"); %>';	NVRAM_nodog_UsernameAuthentication	= (NVRAM_nodog_UsernameAuthentication !='')	? NVRAM_nodog_UsernameAuthentication	: '0';
var NVRAM_nodog_GatewayIPRange			= '<% getCfgGeneral(1, "nodog_GatewayIPRange"); %>';		NVRAM_nodog_GatewayIPRange		= (NVRAM_nodog_GatewayIPRange !='')		? NVRAM_nodog_GatewayIPRange		: '0.0.0.0/0';
var NVRAM_nodog_RedirectURL			= '<% getCfgGeneral(1, "nodog_RedirectURL"); %>';		NVRAM_nodog_RedirectURL			= (NVRAM_nodog_RedirectURL !='')		? NVRAM_nodog_RedirectURL		: 'http://wi-cat.ru';
var NVRAM_nodog_MaxClients			= '<% getCfgGeneral(1, "nodog_MaxClients"); %>';		NVRAM_nodog_MaxClients			= (NVRAM_nodog_MaxClients !='')			? NVRAM_nodog_MaxClients		: '32';
var NVRAM_nodog_ClientIdleTimeout		= '<% getCfgGeneral(1, "nodog_ClientIdleTimeout"); %>';		NVRAM_nodog_ClientIdleTimeout		= (NVRAM_nodog_ClientIdleTimeout !='')		? NVRAM_nodog_ClientIdleTimeout		: '30';
var NVRAM_nodog_ClientForceTimeout		= '<% getCfgGeneral(1, "nodog_ClientForceTimeout"); %>';	NVRAM_nodog_ClientForceTimeout		= (NVRAM_nodog_ClientForceTimeout !='')		? NVRAM_nodog_ClientForceTimeout	: '720';
var NVRAM_nodog_BlockedMACList			= '<% getCfgGeneral(1, "nodog_BlockedMACList"); %>';		NVRAM_nodog_BlockedMACList		= (NVRAM_nodog_BlockedMACList !='')		? NVRAM_nodog_BlockedMACList		: '';
var NVRAM_nodog_AllowedMACList			= '<% getCfgGeneral(1, "nodog_AllowedMACList"); %>';		NVRAM_nodog_AllowedMACList		= (NVRAM_nodog_AllowedMACList !='')		? NVRAM_nodog_AllowedMACList		: '';
var NVRAM_nodog_TrustedMACList			= '<% getCfgGeneral(1, "nodog_TrustedMACList"); %>';		NVRAM_nodog_TrustedMACList		= (NVRAM_nodog_TrustedMACList !='')		? NVRAM_nodog_TrustedMACList		: '';
var NVRAM_nodog_Password			= '<% getCfgGeneral(1, "nodog_Password"); %>';			NVRAM_nodog_Password			= (NVRAM_nodog_Password !='')			? NVRAM_nodog_Password			: 'guest';
var NVRAM_nodog_Username			= '<% getCfgGeneral(1, "nodog_Username"); %>';			NVRAM_nodog_Username			= (NVRAM_nodog_Username !='')			? NVRAM_nodog_Username			: 'guest';
var NVRAM_nodog_PasswordAttempts		= '<% getCfgGeneral(1, "nodog_PasswordAttempts"); %>';		NVRAM_nodog_PasswordAttempts		= (NVRAM_nodog_PasswordAttempts !='')		? NVRAM_nodog_PasswordAttempts		: '5';
var NVRAM_ipt_account				= '<% getCfgGeneral(1, "ipt_account"); %>';			NVRAM_ipt_account			= (NVRAM_ipt_account !='')			? NVRAM_ipt_account			: '0';
var NVRAM_DDNSProvider				= '<% getCfgGeneral(1, "DDNSProvider"); %>';			NVRAM_DDNSProvider			= (NVRAM_DDNSProvider !='')			? NVRAM_DDNSProvider			: '0';
var NVRAM_DDNSAccount				= '<% getCfgGeneral(1, "DDNSAccount"); %>';			NVRAM_DDNSAccount			= (NVRAM_DDNSAccount !='')			? NVRAM_DDNSAccount			: '';
var NVRAM_DDNSPassword				= '<% getCfgGeneral(1, "DDNSPassword"); %>';			NVRAM_DDNSPassword			= (NVRAM_DDNSPassword !='')			? NVRAM_DDNSPassword			: '';
var NVRAM_DDNS					= '<% getCfgGeneral(1, "DDNS"); %>';				NVRAM_DDNS				= (NVRAM_DDNS !='')				? NVRAM_DDNS				: '';
var NVRAM_cwmpdEnabled				= '<% getCfgGeneral(1, "cwmpdEnabled"); %>';			NVRAM_cwmpdEnabled			= (NVRAM_cwmpdEnabled !='')			? NVRAM_cwmpdEnabled			: '0';
var NVRAM_cwmp_acs_type				= '<% getCfgGeneral(1, "cwmp_acs_type"); %>';			NVRAM_cwmp_acs_type			= (NVRAM_cwmp_acs_type !='')			? NVRAM_cwmp_acs_type			: 'tr-098-1-8-0';
var NVRAM_cwmp_acs_url				= '<% getCfgGeneral(1, "cwmp_acs_url"); %>';			NVRAM_cwmp_acs_url			= (NVRAM_cwmp_acs_url !='')			? NVRAM_cwmp_acs_url			: 'http://acs.lo:30006/otomc/acs/webservice.action';
var NVRAM_cwmp_cpe_auth				= '<% getCfgGeneral(1, "cwmp_cpe_auth"); %>';			NVRAM_cwmp_cpe_auth			= (NVRAM_cwmp_cpe_auth !='')			? NVRAM_cwmp_cpe_auth			: '0';
var NVRAM_cwmp_cpe_username			= '<% getCfgGeneral(1, "cwmp_cpe_username"); %>';		NVRAM_cwmp_cpe_username			= (NVRAM_cwmp_cpe_username !='')		? NVRAM_cwmp_cpe_username		: 'cwmp';
var NVRAM_cwmp_cpe_password			= '<% getCfgGeneral(1, "cwmp_cpe_password"); %>';		NVRAM_cwmp_cpe_password 		= (NVRAM_cwmp_cpe_password !='')		? NVRAM_cwmp_cpe_password		: 'cwmp';
var NVRAM_cwmp_acs_auth				= '<% getCfgGeneral(1, "cwmp_acs_auth"); %>';			NVRAM_cwmp_acs_auth			= (NVRAM_cwmp_acs_auth !='')			? NVRAM_cwmp_acs_auth			: '0';
var NVRAM_cwmp_acs_username			= '<% getCfgGeneral(1, "cwmp_acs_username"); %>';		NVRAM_cwmp_acs_username			= (NVRAM_cwmp_acs_username !='')		? NVRAM_cwmp_acs_username		: 'cwmp';
var NVRAM_cwmp_acs_password			= '<% getCfgGeneral(1, "cwmp_acs_password"); %>';		NVRAM_cwmp_acs_password			= (NVRAM_cwmp_acs_password !='')		? NVRAM_cwmp_acs_password		: 'cwmp';
var NVRAM_cwmpd_inform_periodic_enable		= '<% getCfgGeneral(1, "cwmpd_inform_periodic_enable"); %>';	NVRAM_cwmpd_inform_periodic_enable	= (NVRAM_cwmpd_inform_periodic_enable !='')	? NVRAM_cwmpd_inform_periodic_enable	: '1';
var NVRAM_cwmpd_inform_periodic_interval	= '<% getCfgGeneral(1, "cwmpd_inform_periodic_interval"); %>';	NVRAM_cwmpd_inform_periodic_interval	= (NVRAM_cwmpd_inform_periodic_interval !='')	? NVRAM_cwmpd_inform_periodic_interval	: '3600';
var NVRAM_cwmpd_log_level			= '<% getCfgGeneral(1, "cwmpd_log_level"); %>';			NVRAM_cwmpd_log_level			= (NVRAM_cwmpd_log_level !='')			? NVRAM_cwmpd_log_level			: 'info';
var NVRAM_cwmpd_httpd_port			= '<% getCfgGeneral(1, "cwmpd_httpd_port"); %>';		NVRAM_cwmpd_httpd_port			= (NVRAM_cwmpd_httpd_port !='')			? NVRAM_cwmpd_httpd_port		: '1008';
var NVRAM_cwmpd_httpd_timeout			= '<% getCfgGeneral(1, "cwmpd_httpd_timeout"); %>';		NVRAM_cwmpd_httpd_timeout		= (NVRAM_cwmpd_httpd_timeout !='')		? NVRAM_cwmpd_httpd_timeout		: '5000';
var NVRAM_cwmpd_session_connect_timeout		= '<% getCfgGeneral(1, "cwmpd_session_connect_timeout"); %>';	NVRAM_cwmpd_session_connect_timeout	= (NVRAM_cwmpd_session_connect_timeout !='')	? NVRAM_cwmpd_session_connect_timeout	: '15';
var NVRAM_cwmpd_session_response_timeout	= '<% getCfgGeneral(1, "cwmpd_session_response_timeout"); %>';	NVRAM_cwmpd_session_response_timeout	= (NVRAM_cwmpd_session_response_timeout !='')	? NVRAM_cwmpd_session_response_timeout	: '30';
var NVRAM_cwmp_cpe_manufacture			= '<% getCfgGeneral(1, "cwmp_cpe_manufacture"); %>';		NVRAM_cwmp_cpe_manufacture		= (NVRAM_cwmp_cpe_manufacture !='')		? NVRAM_cwmp_cpe_manufacture		: 'NAG';
var NVRAM_cwmp_cpe_oui				= '<% getCfgGeneral(1, "cwmp_cpe_oui"); %>';			NVRAM_cwmp_cpe_oui			= (NVRAM_cwmp_cpe_oui !='')			? NVRAM_cwmp_cpe_oui			: 'A00001';
var NVRAM_cwmp_cpe_pc				= '<% getCfgGeneral(1, "cwmp_cpe_pc"); %>';			NVRAM_cwmp_cpe_pc			= (NVRAM_cwmp_cpe_pc !='')			? NVRAM_cwmp_cpe_pc			: 'OT2800';
var NVRAM_cwmp_ca_file				= '<% getCfgGeneral(1, "cwmp_ca_file"); %>';			NVRAM_cwmp_ca_file			= (NVRAM_cwmp_ca_file !='')			? NVRAM_cwmp_ca_file			: '/etc/raddb/certs/ca.pem';
var NVRAM_cwmp_ca_password			= '<% getCfgGeneral(1, "cwmp_ca_password"); %>';		NVRAM_cwmp_ca_password			= (NVRAM_cwmp_ca_password !='')			? NVRAM_cwmp_ca_password		: '';
var NVRAM_dhcpEnabled				= '<% getCfgGeneral(1, "dhcpEnabled"); %>';			NVRAM_dhcpEnabled			= (NVRAM_dhcpEnabled !='')			? NVRAM_dhcpEnabled			: '1';
var NVRAM_dhcpStatic				= '<% getCfgGeneral(1, "dhcpStatic"); %>';			NVRAM_dhcpStatic			= (NVRAM_dhcpStatic !='')			? NVRAM_dhcpStatic			: '';
var NVRAM_dhcpDomain				= '<% getCfgGeneral(1, "dhcpDomain"); %>';			NVRAM_dhcpDomain			= (NVRAM_dhcpDomain !='')			? NVRAM_dhcpDomain			: 'localnet';
var NVRAM_dhcpStart				= '<% getCfgGeneral(1, "dhcpStart"); %>';			NVRAM_dhcpStart				= (NVRAM_dhcpStart !='')			? NVRAM_dhcpStart			: '192.168.1.2';
var NVRAM_dhcpEnd				= '<% getCfgGeneral(1, "dhcpEnd"); %>';				NVRAM_dhcpEnd				= (NVRAM_dhcpEnd !='')				? NVRAM_dhcpEnd				: '192.168.1.254';
var NVRAM_dhcpMask				= '<% getCfgGeneral(1, "dhcpMask"); %>';			NVRAM_dhcpMask				= (NVRAM_dhcpMask !='')				? NVRAM_dhcpMask			: '255.255.255.0';
var NVRAM_dhcpPriDns				= '<% getCfgGeneral(1, "dhcpPriDns"); %>';			NVRAM_dhcpPriDns			= (NVRAM_dhcpPriDns !='')			? NVRAM_dhcpPriDns			: '';
var NVRAM_dhcpSecDns				= '<% getCfgGeneral(1, "dhcpSecDns"); %>';			NVRAM_dhcpSecDns			= (NVRAM_dhcpSecDns !='')			? NVRAM_dhcpSecDns			: '';
var NVRAM_dhcpGateway				= '<% getCfgGeneral(1, "dhcpGateway"); %>';			NVRAM_dhcpGateway			= (NVRAM_dhcpGateway !='')			? NVRAM_dhcpGateway			: '192.168.1.1';
var NVRAM_dhcpLease				= '<% getCfgGeneral(1, "dhcpLease"); %>';			NVRAM_dhcpLease				= (NVRAM_dhcpLease !='')			? NVRAM_dhcpLease			: '86400';
var NVRAM_dhcpARPPTimeout			= '<% getCfgGeneral(1, "dhcpARPPTimeout"); %>';			NVRAM_dhcpARPPTimeout			= (NVRAM_dhcpARPPTimeout !='')			? NVRAM_dhcpARPPTimeout			: '2000';
var NVRAM_dnsPEnabled				= '<% getCfgGeneral(1, "dnsPEnabled"); %>';			NVRAM_dnsPEnabled			= (NVRAM_dnsPEnabled !='')			? NVRAM_dnsPEnabled			: '1';
var NVRAM_l2tp_srv_enabled			= '<% getCfgGeneral(1, "l2tp_srv_enabled"); %>';		NVRAM_l2tp_srv_enabled			= (NVRAM_l2tp_srv_enabled !='')			? NVRAM_l2tp_srv_enabled		: '0';
var NVRAM_l2tp_srv_ip_local 			= '<% getCfgGeneral(1, "l2tp_srv_ip_local"); %>';		NVRAM_l2tp_srv_ip_local			= (NVRAM_l2tp_srv_ip_local !='')		? NVRAM_l2tp_srv_ip_local		: '172.16.200.1';
var NVRAM_l2tp_srv_ip_range			= '<% getCfgGeneral(1, "l2tp_srv_ip_range"); %>';		NVRAM_l2tp_srv_ip_range			= (NVRAM_l2tp_srv_ip_range !='')		? NVRAM_l2tp_srv_ip_range		: '172.16.200.2-172.16.200.20';
var NVRAM_l2tp_srv_mtu_size			= '<% getCfgGeneral(1, "l2tp_srv_mtu_size"); %>';		NVRAM_l2tp_srv_mtu_size			= (NVRAM_l2tp_srv_mtu_size !='')		? NVRAM_l2tp_srv_mtu_size		: 'AUTO';
var NVRAM_l2tp_srv_mru_size			= '<% getCfgGeneral(1, "l2tp_srv_mru_size"); %>';		NVRAM_l2tp_srv_mru_size			= (NVRAM_l2tp_srv_mru_size !='')		? NVRAM_l2tp_srv_mru_size		: 'AUTO';
var NVRAM_l2tp_srv_lcp_adapt			= '<% getCfgGeneral(1, "l2tp_srv_lcp_adapt"); %>';		NVRAM_l2tp_srv_lcp_adapt		= (NVRAM_l2tp_srv_lcp_adapt !='')		? NVRAM_l2tp_srv_lcp_adapt		: '1';
var NVRAM_l2tp_srv_debug			= '<% getCfgGeneral(1, "l2tp_srv_debug"); %>';			NVRAM_l2tp_srv_debug			= (NVRAM_l2tp_srv_debug !='')			? NVRAM_l2tp_srv_debug			: '0';
var NVRAM_l2tp_srv_nat_enabled			= '<% getCfgGeneral(1, "l2tp_srv_nat_enabled"); %>';		NVRAM_l2tp_srv_nat_enabled		= (NVRAM_l2tp_srv_nat_enabled !='')		? NVRAM_l2tp_srv_nat_enabled		: '1';
var NVRAM_l2tp_srv_mppe_enabled			= '<% getCfgGeneral(1, "l2tp_srv_mppe_enabled"); %>';		NVRAM_l2tp_srv_mppe_enabled		= (NVRAM_l2tp_srv_mppe_enabled !='')		? NVRAM_l2tp_srv_mppe_enabled		: '0';
var NVRAM_l2tp_srv_proxyarp			= '<% getCfgGeneral(1, "l2tp_srv_proxyarp"); %>';		NVRAM_l2tp_srv_proxyarp			= (NVRAM_l2tp_srv_proxyarp !='')		? NVRAM_l2tp_srv_proxyarp		: '0';
var NVRAM_TZ					= '<% getCfgGeneral(1, "TZ"); %>';				NVRAM_TZ				= (NVRAM_TZ !='')				? NVRAM_TZ				: 'OMST-6';
var NVRAM_NTPEnabled				= '<% getCfgGeneral(1, "NTPEnabled"); %>';			NVRAM_NTPEnabled			= (NVRAM_NTPEnabled !='')			? NVRAM_NTPEnabled			: '0';
var NVRAM_NTPServerIP				= '<% getCfgGeneral(1, "NTPServerIP"); %>';			NVRAM_NTPServerIP			= (NVRAM_NTPServerIP !='')			? NVRAM_NTPServerIP			: 'ru.pool.ntp.org';
var NVRAM_SmbEnabled 				= '<% getCfgGeneral(1, "SmbEnabled"); %>';			NVRAM_SmbEnabled			= (NVRAM_SmbEnabled !='')			? NVRAM_SmbEnabled			: '0';
var NVRAM_SmbTimeserver				= '<% getCfgGeneral(1, "SmbTimeserver"); %>';			NVRAM_SmbTimeserver			= (NVRAM_SmbTimeserver !='')			? NVRAM_SmbTimeserver			: '0';
var NVRAM_WorkGroup				= '<% getCfgGeneral(1, "WorkGroup"); %>';			NVRAM_WorkGroup				= (NVRAM_WorkGroup !='')			? NVRAM_WorkGroup			: 'LOCALNET';
var NVRAM_SmbNetBIOS				= '<% getCfgGeneral(1, "SmbNetBIOS"); %>';			NVRAM_SmbNetBIOS			= (NVRAM_SmbNetBIOS !='')			? NVRAM_SmbNetBIOS			: 'Wive-NG-MT';
var NVRAM_SmbString				= '<% getCfgGeneral(1, "SmbString"); %>';			NVRAM_SmbString				= (NVRAM_SmbString !='')			? NVRAM_SmbString			: 'SERVER';
var NVRAM_SmbOsLevel				= '<% getCfgGeneral(1, "SmbOsLevel"); %>';			NVRAM_SmbOsLevel			= (NVRAM_SmbOsLevel !='')			? NVRAM_SmbOsLevel			: '255';
var NVRAM_radius_srv_enabled			= '<% getCfgGeneral(1, "radius_srv_enabled"); %>';		NVRAM_radius_srv_enabled		= (NVRAM_radius_srv_enabled !='')		? NVRAM_radius_srv_enabled		: '0';
var NVRAM_radius_srv_secret			= '<% getCfgGeneral(1, "radius_srv_secret"); %>';		NVRAM_radius_srv_secret			= (NVRAM_radius_srv_secret !='')		? NVRAM_radius_srv_secret		: 'wive-ng-mt';
var NVRAM_RemoteManagementPort			= '<% getCfgGeneral(1, "RemoteManagementPort"); %>';		NVRAM_RemoteManagementPort		= (NVRAM_RemoteManagementPort !='')		? NVRAM_RemoteManagementPort		: '80';
var NVRAM_RemoteSSHPort				= '<% getCfgGeneral(1, "RemoteSSHPort"); %>';			NVRAM_RemoteSSHPort			= (NVRAM_RemoteSSHPort !='')			? NVRAM_RemoteSSHPort			: '22';
var NVRAM_hw_nat_bind				= '<% getCfgGeneral(1, "hw_nat_bind"); %>';			NVRAM_hw_nat_bind			= (NVRAM_hw_nat_bind !='')			? NVRAM_hw_nat_bind			: '50';
var NVRAM_stpEnabled				= '<% getCfgGeneral(1, "stpEnabled"); %>';			NVRAM_stpEnabled			= (NVRAM_stpEnabled !='')			? NVRAM_stpEnabled			: '0';
var NVRAM_igmpEnabled				= '<% getCfgGeneral(1, "igmpEnabled"); %>';			NVRAM_igmpEnabled			= (NVRAM_igmpEnabled !='')			? NVRAM_igmpEnabled			: '0';
var NVRAM_igmpSnoopMode				= '<% getCfgGeneral(1, "igmpSnoopMode"); %>';			NVRAM_igmpSnoopMode			= (NVRAM_igmpSnoopMode !='')			? NVRAM_igmpSnoopMode			: '';
var NVRAM_igmpFastLeave				= '<% getCfgGeneral(1, "igmpFastLeave"); %>';			NVRAM_igmpFastLeave			= (NVRAM_igmpFastLeave !='')			? NVRAM_igmpFastLeave			: '0';
var NVRAM_igmpM2UConvMode			= '<% getCfgGeneral(1, "igmpM2UConvMode"); %>';			NVRAM_igmpM2UConvMode			= (NVRAM_igmpM2UConvMode !='')			? NVRAM_igmpM2UConvMode			: '';
var NVRAM_upnpEnabled				= '<% getCfgGeneral(1, "upnpEnabled"); %>';			NVRAM_upnpEnabled			= (NVRAM_upnpEnabled !='')			? NVRAM_upnpEnabled			: '0';
var NVRAM_xupnpd				= '<% getCfgGeneral(1, "xupnpd"); %>';				NVRAM_xupnpd				= (NVRAM_xupnpd !='')				? NVRAM_xupnpd				: '0';
var NVRAM_dnsPEnabled				= '<% getCfgGeneral(1, "dnsPEnabled"); %>';			NVRAM_dnsPEnabled			= (NVRAM_dnsPEnabled !='')			? NVRAM_dnsPEnabled			: '1';
var NVRAM_cdpEnabled				= '<% getCfgGeneral(1, "cdpEnabled"); %>';			NVRAM_cdpEnabled			= (NVRAM_cdpEnabled !='')			? NVRAM_cdpEnabled			: '0';
var NVRAM_arpwatch				= '<% getCfgGeneral(1, "arpwatch"); %>';			NVRAM_arpwatch				= (NVRAM_arpwatch !='')				? NVRAM_arpwatch			: '0';
var NVRAM_lltdEnabled				= '<% getCfgGeneral(1, "lltdEnabled"); %>';			NVRAM_lltdEnabled			= (NVRAM_lltdEnabled !='')			? NVRAM_lltdEnabled			: '1';
var NVRAM_lldpdEnabled				= '<% getCfgGeneral(1, "lldpdEnabled"); %>';			NVRAM_lldpdEnabled			= (NVRAM_lldpdEnabled !='')			? NVRAM_lldpdEnabled			: '0';
var NVRAM_pppoe_pass				= '<% getCfgGeneral(1, "pppoe_pass"); %>';			NVRAM_pppoe_pass			= (NVRAM_pppoe_pass !='')			? NVRAM_pppoe_pass			: '0';
var NVRAM_ipv6_pass				= '<% getCfgGeneral(1, "ipv6_pass"); %>';			NVRAM_ipv6_pass				= (NVRAM_ipv6_pass !='')			? NVRAM_ipv6_pass			: '0';
var NVRAM_WANPingFilter				= '<% getCfgGeneral(1, "WANPingFilter"); %>';			NVRAM_WANPingFilter			= (NVRAM_WANPingFilter !='')			? NVRAM_WANPingFilter			: '1';
var NVRAM_parproutedEnabled			= '<% getCfgGeneral(1, "parproutedEnabled"); %>';		NVRAM_parproutedEnabled			= (NVRAM_parproutedEnabled !='')		? NVRAM_parproutedEnabled		: '0';
var NVRAM_hw_nat_wifi				= '<% getCfgGeneral(1, "hw_nat_wifi"); %>';			NVRAM_hw_nat_wifi			= (NVRAM_hw_nat_wifi !='')			? NVRAM_hw_nat_wifi			: '1';
var NVRAM_hw_nat_udp				= '<% getCfgGeneral(1, "hw_nat_udp"); %>';			NVRAM_hw_nat_udp			= (NVRAM_hw_nat_udp !='')			? NVRAM_hw_nat_udp			: '1';
var NVRAM_hw_nat_six				= '<% getCfgGeneral(1, "hw_nat_six"); %>';			NVRAM_hw_nat_six			= (NVRAM_hw_nat_six !='')			? NVRAM_hw_nat_six			: '1';
var NVRAM_pinger_check_on			= '<% getCfgGeneral(1, "pinger_check_on"); %>';			NVRAM_pinger_check_on			= (NVRAM_pinger_check_on !='')			? NVRAM_pinger_check_on			: '0';
var NVRAM_mss_use_pmtu				= '<% getCfgGeneral(1, "mss_use_pmtu"); %>';			NVRAM_mss_use_pmtu			= (NVRAM_mss_use_pmtu !='')			? NVRAM_mss_use_pmtu			: '1';
var NVRAM_nat_mode				= '<% getCfgGeneral(1, "nat_mode"); %>';			NVRAM_nat_mode				= (NVRAM_nat_mode !='')				? NVRAM_nat_mode			: '0';
var NVRAM_RemoteManagement			= '<% getCfgGeneral(1, "RemoteManagement"); %>';		NVRAM_RemoteManagement			= (NVRAM_RemoteManagement !='')			? NVRAM_RemoteManagement		: '1';
var NVRAM_RemoteSSH				= '<% getCfgGeneral(1, "RemoteSSH"); %>';			NVRAM_RemoteSSH				= (NVRAM_RemoteSSH !='')			? NVRAM_RemoteSSH			: '1';
var NVRAM_RemoteTelnet				= '<% getCfgGeneral(1, "RemoteTelnet"); %>';			NVRAM_RemoteTelnet			= (NVRAM_RemoteTelnet !='')			? NVRAM_RemoteTelnet			: '1';
var NVRAM_UDPXYMode				= '<% getCfgGeneral(1, "UDPXYMode"); %>';			NVRAM_UDPXYMode				= (NVRAM_UDPXYMode !='')			? NVRAM_UDPXYMode			: '0';
var NVRAM_UDPXYPort				= '<% getCfgGeneral(1, "UDPXYPort"); %>';			NVRAM_UDPXYPort				= (NVRAM_UDPXYPort !='')			? NVRAM_UDPXYPort			: '81';
var NVRAM_WatchdogEnabled			= '<% getCfgGeneral(1, "WatchdogEnabled"); %>';			NVRAM_WatchdogEnabled			= (NVRAM_WatchdogEnabled !='')			? NVRAM_WatchdogEnabled			: '0';
var NVRAM_vlanDoubleTag				= '<% getCfgGeneral(1, "vlanDoubleTag"); %>';			NVRAM_vlanDoubleTag			= (NVRAM_vlanDoubleTag !='')			? NVRAM_vlanDoubleTag			: '0';
var NVRAM_dhcpSwReset				= '<% getCfgGeneral(1, "dhcpSwReset"); %>';			NVRAM_dhcpSwReset			= (NVRAM_dhcpSwReset !='')			? NVRAM_dhcpSwReset			: '0';
var NVRAM_natFastpath				= '<% getCfgGeneral(1, "natFastpath"); %>';			NVRAM_natFastpath			= (NVRAM_natFastpath !='')			? NVRAM_natFastpath			: '1';
var NVRAM_routeFastpath				= '<% getCfgGeneral(1, "routeFastpath"); %>';			NVRAM_routeFastpath			= (NVRAM_routeFastpath !='')			? NVRAM_routeFastpath			: '1';
var NVRAM_filterFastpath			= '<% getCfgGeneral(1, "filterFastpath"); %>';			NVRAM_filterFastpath			= (NVRAM_filterFastpath !='')			? NVRAM_filterFastpath			: '1';
var NVRAM_CrondEnable				= '<% getCfgGeneral(1, "CrondEnable"); %>';			NVRAM_CrondEnable			= (NVRAM_CrondEnable !='')			? NVRAM_CrondEnable			: '0';
var NVRAM_ForceRenewDHCP			= '<% getCfgGeneral(1, "ForceRenewDHCP"); %>';			NVRAM_ForceRenewDHCP			= (NVRAM_ForceRenewDHCP !='')			? NVRAM_ForceRenewDHCP			: '1';
var NVRAM_snmpd					= '<% getCfgGeneral(1, "snmpd"); %>';				NVRAM_snmpd				= (NVRAM_snmpd !='')				? NVRAM_snmpd				: '0';
var NVRAM_store_ttl				= '<% getCfgGeneral(1, "store_ttl"); %>';			NVRAM_store_ttl				= (NVRAM_store_ttl !='')			? NVRAM_store_ttl			: '0';
var NVRAM_store_ttl_mcast			= '<% getCfgGeneral(1, "store_ttl_mcast"); %>';			NVRAM_store_ttl_mcast			= (NVRAM_store_ttl_mcast !='')			? NVRAM_store_ttl_mcast			: '0';
var NVRAM_IRQBalance				= '<% getCfgGeneral(1, "IRQBalance"); %>';			NVRAM_IRQBalance			= (NVRAM_IRQBalance !='')			? NVRAM_IRQBalance			: 'auto';
var NVRAM_ping_check_time			= '<% getCfgGeneral(1, "ping_check_time"); %>';			NVRAM_ping_check_time			= (NVRAM_ping_check_time !='')			? NVRAM_ping_check_time			: '300';
var NVRAM_ping_check_interval			= '<% getCfgGeneral(1, "ping_check_interval"); %>';		NVRAM_ping_check_interval		= (NVRAM_ping_check_interval !='')		? NVRAM_ping_check_interval		: '30';
var NVRAM_smbFastpath				= '<% getCfgGeneral(1, "smbFastpath"); %>';			NVRAM_smbFastpath			= (NVRAM_smbFastpath !='')			? NVRAM_smbFastpath			: '1';
var NVRAM_ApCliBridgeOnly			= '<% getCfgGeneral(1, "ApCliBridgeOnly"); %>';			NVRAM_ApCliBridgeOnly			= (NVRAM_ApCliBridgeOnly !='')			? NVRAM_ApCliBridgeOnly			: '0';
var NVRAM_snmpdcommunity			= '<% getCfgGeneral(1, "snmpdcommunity"); %>';			NVRAM_snmpdcommunity			= (NVRAM_snmpdcommunity !='')			? NVRAM_snmpdcommunity			: 'Wive-NG-MT';
var NVRAM_Language				= '<% getCfgGeneral(1, "Language"); %>';			NVRAM_Language				= (NVRAM_Language !='')				? NVRAM_Language			: 'en';
var NVRAM_WdsNum				= '<% getCfgGeneral(1, "WdsNum"); %>';				NVRAM_WdsNum				= (NVRAM_WdsNum !='')				? NVRAM_WdsNum				: '1';
var NVRAM_WdsPhyMode				= '<% getCfgGeneral(1, "WdsPhyMode"); %>';			NVRAM_WdsPhyMode			= (NVRAM_WdsPhyMode !='')			? NVRAM_WdsPhyMode			: 'HTMIX;HTMIX;HTMIX;HTMIX';
var NVRAM_WdsEncrypType				= '<% getCfgGeneral(1, "WdsEncrypType"); %>';			NVRAM_WdsEncrypType			= (NVRAM_WdsEncrypType !='')			? NVRAM_WdsEncrypType			: 'AES;AES;AES;AES';
var NVRAM_Wds0Key				= '<% getCfgGeneral(1, "Wds0Key"); %>';				NVRAM_Wds0Key				= (NVRAM_Wds0Key !='')				? NVRAM_Wds0Key				: '';
var NVRAM_Wds1Key				= '<% getCfgGeneral(1, "Wds1Key"); %>';				NVRAM_Wds1Key				= (NVRAM_Wds1Key !='')				? NVRAM_Wds1Key				: '';
var NVRAM_Wds2Key				= '<% getCfgGeneral(1, "Wds2Key"); %>';				NVRAM_Wds2Key				= (NVRAM_Wds2Key !='')				? NVRAM_Wds2Key				: '';
var NVRAM_Wds3Key				= '<% getCfgGeneral(1, "Wds3Key"); %>';				NVRAM_Wds3Key				= (NVRAM_Wds3Key !='')				? NVRAM_Wds3Key				: '';
var NVRAM_WdsIfName				= '<% getCfgGeneral(1, "WdsIfName"); %>';			NVRAM_WdsIfName				= (NVRAM_WdsIfName !='')			? NVRAM_WdsIfName			: 'wds';
var NVRAM_RadioOn				= '<% getCfgGeneral(1, "RadioOn"); %>';				NVRAM_RadioOn				= (NVRAM_RadioOn !='')				? NVRAM_RadioOn				: '1';
var NVRAM_RadioOnINIC				= '<% getCfgGeneral(1, "RadioOnINIC"); %>';			NVRAM_RadioOnINIC			= (NVRAM_RadioOnINIC !='')			? NVRAM_RadioOnINIC			: '1';
var NVRAM_WdsEnable				= '<% getCfgGeneral(1, "WdsEnable"); %>';			NVRAM_WdsEnable				= (NVRAM_WdsEnable !='')			? NVRAM_WdsEnable			: '0';
var NVRAM_WdsList				= '<% getCfgGeneral(1, "WdsList"); %>';				NVRAM_WdsList				= (NVRAM_WdsList !='')				? NVRAM_WdsList				: '';
var NVRAM_SSID1 				= '<% getCfgGeneral(1, "SSID1"); %>';				NVRAM_SSID1				= (NVRAM_SSID1 !='')				? NVRAM_SSID1				: 'Wive-NG-MT';
var NVRAM_SSID2					= '<% getCfgGeneral(1, "SSID2"); %>';				NVRAM_SSID2				= (NVRAM_SSID2 !='')				? NVRAM_SSID2				: '';
var NVRAM_SSID3					= '<% getCfgGeneral(1, "SSID3"); %>';				NVRAM_SSID3				= (NVRAM_SSID3 !='')				? NVRAM_SSID3				: '';
var NVRAM_SSID4					= '<% getCfgGeneral(1, "SSID4"); %>';				NVRAM_SSID4				= (NVRAM_SSID4 !='')				? NVRAM_SSID4				: '';
var NVRAM_SSID5					= '<% getCfgGeneral(1, "SSID5"); %>';				NVRAM_SSID5				= (NVRAM_SSID5 !='')				? NVRAM_SSID5				: '';
var NVRAM_SSID6					= '<% getCfgGeneral(1, "SSID6"); %>';				NVRAM_SSID6				= (NVRAM_SSID6 !='')				? NVRAM_SSID6				: '';
var NVRAM_SSID7					= '<% getCfgGeneral(1, "SSID7"); %>';				NVRAM_SSID7				= (NVRAM_SSID7 !='')				? NVRAM_SSID7				: '';
var NVRAM_SSID8					= '<% getCfgGeneral(1, "SSID8"); %>';				NVRAM_SSID8				= (NVRAM_SSID8 !='')				? NVRAM_SSID8				: '';
var NVRAM_SSID1INIC				= '<% getCfgGeneral(1, "SSID1INIC"); %>';			NVRAM_SSID1INIC				= (NVRAM_SSID1INIC !='')			? NVRAM_SSID1INIC			: 'Wive-NG-MT-5GHZ';
var NVRAM_WPAPSK1INIC 				= '<% getCfgGeneral(1, "WPAPSK1INIC"); %>';			NVRAM_WPAPSK1INIC			= (NVRAM_WPAPSK1INIC !='')			? NVRAM_WPAPSK1INIC			: '1234567890';
var NVRAM_WirelessMode				= '<% getCfgGeneral(1, "WirelessMode"); %>';			NVRAM_WirelessMode			= (NVRAM_WirelessMode !='')			? NVRAM_WirelessMode			: '7';
var NVRAM_WirelessModeINIC			= '<% getCfgGeneral(1, "WirelessModeINIC"); %>';		NVRAM_WirelessModeINIC			= (NVRAM_WirelessModeINIC !='')			? NVRAM_WirelessModeINIC		: '14';
var NVRAM_TxPower				= '<% getCfgGeneral(1, "TxPower"); %>';				NVRAM_TxPower				= (NVRAM_TxPower !='')				? NVRAM_TxPower				: '100';
var NVRAM_TxPowerINIC				= '<% getCfgGeneral(1, "TxPowerINIC"); %>';			NVRAM_TxPowerINIC			= (NVRAM_TxPowerINIC !='')			? NVRAM_TxPowerINIC			: '100';
var NVRAM_NoForwardingBTNBSSID			= '<% getCfgGeneral(1, "NoForwardingBTNBSSID"); %>';		NVRAM_NoForwardingBTNBSSID		= (NVRAM_NoForwardingBTNBSSID !='')		? NVRAM_NoForwardingBTNBSSID		: '0';
var NVRAM_FixedTxMode				= '<% getCfgGeneral(1, "FixedTxMode"); %>';			NVRAM_FixedTxMode			= (NVRAM_FixedTxMode !='')			? NVRAM_FixedTxMode			: '';
var NVRAM_CountryCode				= '<% getCfgGeneral(1, "CountryCode"); %>';			NVRAM_CountryCode			= (NVRAM_CountryCode !='')			? NVRAM_CountryCode			: 'RU';
var NVRAM_HT_TxStream				= '<% getCfgGeneral(1, "HT_TxStream"); %>';			NVRAM_HT_TxStream			= (NVRAM_HT_TxStream !='')			? NVRAM_HT_TxStream			: '2';
var NVRAM_HT_RxStream				= '<% getCfgGeneral(1, "HT_RxStream"); %>';			NVRAM_HT_RxStream			= (NVRAM_HT_RxStream !='')			? NVRAM_HT_RxStream			: '2';
var NVRAM_HT_OpMode				= '<% getCfgGeneral(1, "HT_OpMode"); %>';			NVRAM_HT_OpMode				= (NVRAM_HT_OpMode !='')			? NVRAM_HT_OpMode			: '1';
var NVRAM_HT_GI					= '<% getCfgGeneral(1, "HT_GI"); %>';				NVRAM_HT_GI				= (NVRAM_HT_GI !='')				? NVRAM_HT_GI				: '1';
var NVRAM_HT_STBC				= '<% getCfgGeneral(1, "HT_STBC"); %>';				NVRAM_HT_STBC				= (NVRAM_HT_STBC !='')				? NVRAM_HT_STBC				: '1';
var NVRAM_HT_MCS				= '<% getCfgGeneral(1, "HT_MCS"); %>';				NVRAM_HT_MCS				= (NVRAM_HT_MCS !='')				? NVRAM_HT_MCS				: '33';
var NVRAM_HT_HTC				= '<% getCfgGeneral(1, "HT_HTC"); %>';				NVRAM_HT_HTC				= (NVRAM_HT_HTC !='')				? NVRAM_HT_HTC				: '0';
var NVRAM_HT_RDG				= '<% getCfgGeneral(1, "HT_RDG"); %>';				NVRAM_HT_RDG				= (NVRAM_HT_RDG !='')				? NVRAM_HT_RDG				: '0';
var NVRAM_HT_EXTCHA				= '<% getCfgGeneral(1, "HT_EXTCHA"); %>';			NVRAM_HT_EXTCHA				= (NVRAM_HT_EXTCHA !='')			? NVRAM_HT_EXTCHA			: '1';
var NVRAM_HT_AMSDU				= '<% getCfgGeneral(1, "HT_AMSDU"); %>';			NVRAM_HT_AMSDU				= (NVRAM_HT_AMSDU !='')				? NVRAM_HT_AMSDU			: '1';
var NVRAM_HT_AutoBA				= '<% getCfgGeneral(1, "HT_AutoBA"); %>';			NVRAM_HT_AutoBA				= (NVRAM_HT_AutoBA !='')			? NVRAM_HT_AutoBA			: '1';
var NVRAM_HT_BADecline				= '<% getCfgGeneral(1, "HT_BADecline"); %>';			NVRAM_HT_BADecline			= (NVRAM_HT_BADecline !='')			? NVRAM_HT_BADecline			: '0';
var NVRAM_HT_BW					= '<% getCfgGeneral(1, "HT_BW"); %>';				NVRAM_HT_BW				= (NVRAM_HT_BW !='')				? NVRAM_HT_BW				: '1';
var NVRAM_HT_BWINIC				= '<% getCfgGeneral(1, "HT_BWINIC"); %>';			NVRAM_HT_BWINIC				= (NVRAM_HT_BWINIC !='')			? NVRAM_HT_BWINIC			: '1';
var NVRAM_VHT_SGI				= '<% getCfgGeneral(1, "VHT_SGI"); %>';				NVRAM_VHT_SGI				= (NVRAM_VHT_SGI !='')				? NVRAM_VHT_SGI				: '1';
var NVRAM_VHT_STBC				= '<% getCfgGeneral(1, "VHT_STBC"); %>';			NVRAM_VHT_STBC				= (NVRAM_VHT_STBC !='')				? NVRAM_VHT_STBC			: '0';
var NVRAM_VHT_LDPC				= '<% getCfgGeneral(1, "VHT_LDPC"); %>';			NVRAM_VHT_LDPC				= (NVRAM_VHT_LDPC !='')				? NVRAM_VHT_LDPC			: '0';
var NVRAM_VHT_BW				= '<% getCfgGeneral(1, "VHT_BW"); %>';				NVRAM_VHT_BW				= (NVRAM_VHT_BW !='')				? NVRAM_VHT_BW				: '1';
var NVRAM_VHT_BW_SIGNAL				= '<% getCfgGeneral(1, "VHT_BW_SIGNAL"); %>';			NVRAM_VHT_BW_SIGNAL			= (NVRAM_VHT_BW_SIGNAL !='')			? NVRAM_VHT_BW_SIGNAL			: '0';
var NVRAM_BGProtection				= '<% getCfgGeneral(1, "BGProtection"); %>';			NVRAM_BGProtection			= (NVRAM_BGProtection !='')			? NVRAM_BGProtection			: '2';
var NVRAM_TxPreamble				= '<% getCfgGeneral(1, "TxPreamble"); %>';			NVRAM_TxPreamble			= (NVRAM_TxPreamble !='')			? NVRAM_TxPreamble			: '2';
var NVRAM_ShortSlot				= '<% getCfgGeneral(1, "ShortSlot"); %>';			NVRAM_ShortSlot				= (NVRAM_ShortSlot !='')			? NVRAM_ShortSlot			: '1';
var NVRAM_TxBurst				= '<% getCfgGeneral(1, "TxBurst"); %>';				NVRAM_TxBurst				= (NVRAM_TxBurst !='')				? NVRAM_TxBurst				: '1';
var NVRAM_PktAggregate				= '<% getCfgGeneral(1, "PktAggregate"); %>';			NVRAM_PktAggregate			= (NVRAM_PktAggregate !='')			? NVRAM_PktAggregate			: '1';
var NVRAM_M2UEnabled				= '<% getCfgGeneral(1, "M2UEnabled"); %>';			NVRAM_M2UEnabled			= (NVRAM_M2UEnabled !='')			? NVRAM_M2UEnabled			: '0';
var NVRAM_McastPhyMode				= '<% getCfgGeneral(1, "McastPhyMode"); %>';			NVRAM_McastPhyMode			= (NVRAM_McastPhyMode !='')			? NVRAM_McastPhyMode			: '2';
var NVRAM_McastMcs				= '<% getCfgGeneral(1, "McastMcs"); %>';			NVRAM_McastMcs				= (NVRAM_McastMcs !='')				? NVRAM_McastMcs			: '3';
var NVRAM_VideoTurbine				= '<% getCfgGeneral(1, "VideoTurbine"); %>';			NVRAM_VideoTurbine			= (NVRAM_VideoTurbine !='')			? NVRAM_VideoTurbine			: '1';
var NVRAM_DyncVgaEnable				= '<% getCfgGeneral(1, "DyncVgaEnable"); %>';			NVRAM_DyncVgaEnable			= (NVRAM_DyncVgaEnable !='')			? NVRAM_DyncVgaEnable			: '1';
var NVRAM_SkipLongRangeVga			= '<% getCfgGeneral(1, "SkipLongRangeVga"); %>';		NVRAM_SkipLongRangeVga			= (NVRAM_SkipLongRangeVga !='')			? NVRAM_SkipLongRangeVga		: '0';
var NVRAM_VgaClamp				= '<% getCfgGeneral(1, "VgaClamp"); %>';			NVRAM_VgaClamp				= (NVRAM_VgaClamp !='')				? NVRAM_VgaClamp			: '0';
var NVRAM_MaxStaNum				= '<% getCfgGeneral(1, "MaxStaNum"); %>';			NVRAM_MaxStaNum				= (NVRAM_MaxStaNum !='')			? NVRAM_MaxStaNum			: '56;56;56;56';
var NVRAM_StationKeepAlive			= '<% getCfgGeneral(1, "StationKeepAlive"); %>';		NVRAM_StationKeepAlive			= (NVRAM_StationKeepAlive !='')			? NVRAM_StationKeepAlive		: '60;60;60;60';
var NVRAM_IdleTimeout				= '<% getCfgGeneral(1, "IdleTimeout"); %>';			NVRAM_IdleTimeout			= (NVRAM_IdleTimeout !='')			? NVRAM_IdleTimeout			: '300';
var NVRAM_AckPolicy				= '<% getCfgGeneral(1, "AckPolicy"); %>';			NVRAM_AckPolicy				= (NVRAM_AckPolicy !='')			? NVRAM_AckPolicy			: '0;0;0;0';
var NVRAM_WmmCapable				= '<% getCfgGeneral(1, "WmmCapable"); %>';			NVRAM_WmmCapable			= (NVRAM_WmmCapable !='')			? NVRAM_WmmCapable			: '1';
var NVRAM_ED_MODE				= '<% getCfgGeneral(1, "ED_MODE"); %>';				NVRAM_ED_MODE				= (NVRAM_ED_MODE !='')				? NVRAM_ED_MODE				: '0';
var NVRAM_AutoChannelSelect			= '<% getCfgGeneral(1, "AutoChannelSelect"); %>';		NVRAM_AutoChannelSelect			= (NVRAM_AutoChannelSelect !='')		? NVRAM_AutoChannelSelect		: '0';
var NVRAM_AutoChannelSelectINIC			= '<% getCfgGeneral(1, "AutoChannelSelectINIC"); %>';		NVRAM_AutoChannelSelectINIC		= (NVRAM_AutoChannelSelectINIC !='')		? NVRAM_AutoChannelSelectINIC		: '0';
var NVRAM_ACSCheckTime				= '<% getCfgGeneral(1, "ACSCheckTime"); %>';			NVRAM_ACSCheckTime			= (NVRAM_ACSCheckTime !='')			? NVRAM_ACSCheckTime			: '0';
var NVRAM_ACSCheckTimeINIC			= '<% getCfgGeneral(1, "ACSCheckTimeINIC"); %>';		NVRAM_ACSCheckTimeINIC			= (NVRAM_ACSCheckTimeINIC !='')			? NVRAM_ACSCheckTimeINIC		: '';
var NVRAM_HideSSID				= '<% getCfgGeneral(1, "HideSSID"); %>';			NVRAM_HideSSID				= (NVRAM_HideSSID !='')				? NVRAM_HideSSID			: '0';
var NVRAM_NoForwarding				= '<% getCfgGeneral(1, "NoForwarding"); %>';			NVRAM_NoForwarding			= (NVRAM_NoForwarding !='')			? NVRAM_NoForwarding			: '0;0;0;0';
var NVRAM_NoForwardingMBCast			= '<% getCfgGeneral(1, "NoForwardingMBCast"); %>';		NVRAM_NoForwardingMBCast		= (NVRAM_NoForwardingMBCast !='')		? NVRAM_NoForwardingMBCast		: '0;0;0;0';
var NVRAM_IEEE80211H				= '<% getCfgGeneral(1, "IEEE80211H"); %>';			NVRAM_IEEE80211H			= (NVRAM_IEEE80211H !='')			? NVRAM_IEEE80211H			: '1';
var NVRAM_TXPath				= '<% getCfgGeneral(1, "TXPath"); %>';				NVRAM_TXPath				= (NVRAM_TXPath !='')				? NVRAM_TXPath				: '';
var NVRAM_RXPath				= '<% getCfgGeneral(1, "RXPath"); %>';				NVRAM_RXPath				= (NVRAM_RXPath !='')				? NVRAM_RXPath				: '';
var NVRAM_BandSteering				= '<% getCfgGeneral(1, "BandSteering"); %>';			NVRAM_BandSteering			= (NVRAM_BandSteering != '')			? NVRAM_BandSteering			: '0';
var NVRAM_FastRoaming				= '<% getCfgGeneral(1, "FastRoaming"); %>';			NVRAM_FastRoaming			= (NVRAM_FastRoaming != '')			? NVRAM_FastRoaming			: '0';
var NVRAM_IdsEnable				= '<% getCfgGeneral(1, "IdsEnable"); %>';			NVRAM_IdsEnable				= (NVRAM_IdsEnable != '')			? NVRAM_IdsEnable			: '0';
var NVRAM_ITxBfEn				= '<% getCfgGeneral(1, "ITxBfEn"); %>';				NVRAM_ITxBfEn				= (NVRAM_ITxBfEn != '')				? NVRAM_ITxBfEn				: '0';
var NVRAM_ETxBfeeEn				= '<% getCfgGeneral(1, "ETxBfeeEn"); %>';			NVRAM_ETxBfeeEn				= (NVRAM_ETxBfeeEn != '')			? NVRAM_ETxBfeeEn			: '0';
var NVRAM_ETxBfEnCond				= '<% getCfgGeneral(1, "ETxBfEnCond"); %>';			NVRAM_ETxBfEnCond			= (NVRAM_ETxBfEnCond != '')			? NVRAM_ETxBfEnCond			: '0';
var NVRAM_RRMEnable				= '<% getCfgGeneral(1, "RRMEnable"); %>';			NVRAM_RRMEnable				= (NVRAM_RRMEnable != '')			? NVRAM_RRMEnable			: '0';
var NVRAM_FtSupport				= '<% getCfgGeneral(1, "FtSupport"); %>';			NVRAM_FtSupport				= (NVRAM_FtSupport != '')			? NVRAM_FtSupport			: '0';
var NVRAM_LanWifiIsolate			= '<% getCfgGeneral(1, "LanWifiIsolate"); %>';			NVRAM_LanWifiIsolate			= (NVRAM_LanWifiIsolate != '')			? NVRAM_LanWifiIsolate			: '0';
var NVRAM_BeaconPeriod				= '<% getCfgGeneral(1, "BeaconPeriod"); %>';			NVRAM_BeaconPeriod			= (NVRAM_BeaconPeriod != '')			? NVRAM_BeaconPeriod			: '160';
var NVRAM_BeaconPeriodINIC			= '<% getCfgGeneral(1, "BeaconPeriodINIC"); %>';		NVRAM_BeaconPeriodINIC			= (NVRAM_BeaconPeriod != '')			? NVRAM_BeaconPeriodINIC		: '80';
var NVRAM_DtimPeriod				= '<% getCfgGeneral(1, "DtimPeriod"); %>';			NVRAM_DtimPeriod			= (NVRAM_DtimPeriod != '')			? NVRAM_DtimPeriod			: '1';
var NVRAM_FragThreshold				= '<% getCfgGeneral(1, "FragThreshold"); %>';			NVRAM_FragThreshold			= (NVRAM_FragThreshold != '')			? NVRAM_FragThreshold			: '2346';
var NVRAM_RTSThreshold				= '<% getCfgGeneral(1, "RTSThreshold"); %>';			NVRAM_RTSThreshold			= (NVRAM_RTSThreshold != '')			? NVRAM_RTSThreshold			: '2347';
var NVRAM_EntryLifeCheck			= '<% getCfgGeneral(1, "EntryLifeCheck"); %>';			NVRAM_EntryLifeCheck			= (NVRAM_EntryLifeCheck != '')			? NVRAM_EntryLifeCheck			: '1024';
var NVRAM_ApProbeRspTimes			= '<% getCfgGeneral(1, "ApProbeRspTimes"); %>';			NVRAM_ApProbeRspTimes			= (NVRAM_ApProbeRspTimes != '')			? NVRAM_ApProbeRspTimes			: '3';
var NVRAM_BandDeltaRssi				= '<% getCfgGeneral(1, "BandDeltaRssi"); %>';			NVRAM_BandDeltaRssi			= (NVRAM_BandDeltaRssi != '')			? NVRAM_BandDeltaRssi			: '-8';
var NVRAM_AuthRspFail				= '<% getCfgGeneral(1, "AuthRspFail"); %>';			NVRAM_AuthRspFail			= (NVRAM_AuthRspFail != '')			? NVRAM_AuthRspFail			: '0';
var NVRAM_AuthRspRssi				= '<% getCfgGeneral(1, "AuthRspRssi"); %>';			NVRAM_AuthRspRssi			= (NVRAM_AuthRspRssi != '')			? NVRAM_AuthRspRssi			: '0';
var NVRAM_AssocReqRssiThres 			= '<% getCfgGeneral(1, "AssocReqRssiThres"); %>';		NVRAM_AssocReqRssiThres			= (NVRAM_AssocReqRssiThres != '')		? NVRAM_AssocReqRssiThres		: '-68';
var NVRAM_AssocRspIgnor				= '<% getCfgGeneral(1, "AssocRspIgnor"); %>';			NVRAM_AssocRspIgnor			= (NVRAM_AssocRspIgnor != '')			? NVRAM_AssocRspIgnor			: '0';
var NVRAM_ProbeRspRssi				= '<% getCfgGeneral(1, "ProbeRspRssi"); %>';			NVRAM_ProbeRspRssi			= (NVRAM_ProbeRspRssi != '')			? NVRAM_ProbeRspRssi			: '-80';
var NVRAM_KickStaRssiLow			= '<% getCfgGeneral(1, "KickStaRssiLow"); %>';			NVRAM_KickStaRssiLow			= (NVRAM_KickStaRssiLow != '')			? NVRAM_KickStaRssiLow			: '-76';
var NVRAM_KickStaRssiLowPSM			= '<% getCfgGeneral(1, "KickStaRssiLowPSM"); %>';		NVRAM_KickStaRssiLowPSM			= (NVRAM_KickStaRssiLowPSM != '')		? NVRAM_KickStaRssiLowPSM		: '-80';
var NVRAM_KickStaRssiLowDelay			= '<% getCfgGeneral(1, "KickStaRssiLowDelay"); %>';		NVRAM_KickStaRssiLowDelay		= (NVRAM_KickStaRssiLowDelay != '')		? NVRAM_KickStaRssiLowDelay		: '6';
var NVRAM_BndStrgRssiDiff			= '<% getCfgGeneral(1, "BndStrgRssiDiff"); %>';			NVRAM_BndStrgRssiDiff			= (NVRAM_BndStrgRssiDiff != '')			? NVRAM_BndStrgRssiDiff			: '15';
var NVRAM_BndStrgRssiLow			= '<% getCfgGeneral(1, "BndStrgRssiLow"); %>';			NVRAM_BndStrgRssiLow			= (NVRAM_BndStrgRssiLow != '')			? NVRAM_BndStrgRssiLow			: '-88';
var NVRAM_BndStrgAge				= '<% getCfgGeneral(1, "BndStrgAge"); %>';			NVRAM_BndStrgAge			= (NVRAM_BndStrgAge != '')			? NVRAM_BndStrgAge			: '200000';
var NVRAM_BndStrgHoldTime			= '<% getCfgGeneral(1, "BndStrgHoldTime"); %>';			NVRAM_BndStrgHoldTime			= (NVRAM_BndStrgHoldTime != '')			? NVRAM_BndStrgHoldTime			: '8000';
var NVRAM_BndStrgCheckTime			= '<% getCfgGeneral(1, "BndStrgCheckTime"); %>';		NVRAM_BndStrgCheckTime			= (NVRAM_BndStrgCheckTime != '')		? NVRAM_BndStrgCheckTime		: '4000';
var NVRAM_AuthFloodThreshold			= '<% getCfgGeneral(1, "AuthFloodThreshold"); %>';		NVRAM_AuthFloodThreshold		= (NVRAM_AuthFloodThreshold != '')		? NVRAM_AuthFloodThreshold		: '64';
var NVRAM_AssocReqFloodThreshold		= '<% getCfgGeneral(1, "AssocReqFloodThreshold"); %>';		NVRAM_AssocReqFloodThreshold		= (NVRAM_AssocReqFloodThreshold != '')		? NVRAM_AssocReqFloodThreshold		: '64';
var NVRAM_ReassocReqFloodThreshold		= '<% getCfgGeneral(1, "ReassocReqFloodThreshold"); %>';	NVRAM_ReassocReqFloodThreshold		= (NVRAM_ReassocReqFloodThreshold != '')	? NVRAM_ReassocReqFloodThreshold	: '64';
var NVRAM_ProbeReqFloodThreshold		= '<% getCfgGeneral(1, "ProbeReqFloodThreshold"); %>';		NVRAM_ProbeReqFloodThreshold		= (NVRAM_ProbeReqFloodThreshold != '')		? NVRAM_ProbeReqFloodThreshold		: '64';
var NVRAM_DisassocFloodThreshold		= '<% getCfgGeneral(1, "DisassocFloodThreshold"); %>';		NVRAM_DisassocFloodThreshold		= (NVRAM_DisassocFloodThreshold != '')		? NVRAM_DisassocFloodThreshold		: '64';
var NVRAM_DeauthFloodThreshold			= '<% getCfgGeneral(1, "DeauthFloodThreshold"); %>';		NVRAM_DeauthFloodThreshold		= (NVRAM_DeauthFloodThreshold != '')		? NVRAM_DeauthFloodThreshold		: '64';
var NVRAM_EapReqFloodThreshold			= '<% getCfgGeneral(1, "EapReqFloodThreshold"); %>';		NVRAM_EapReqFloodThreshold		= (NVRAM_EapReqFloodThreshold != '')		? NVRAM_EapReqFloodThreshold		: '64';
var NVRAM_ApCliEnable				= '<% getCfgGeneral(1, "ApCliEnable"); %>';			NVRAM_ApCliEnable			= (NVRAM_ApCliEnable != '')			? NVRAM_ApCliEnable			: '0';
var NVRAM_ApCliSsid				= '<% getCfgGeneral(1, "ApCliSsid"); %>';			NVRAM_ApCliSsid				= (NVRAM_ApCliSsid != '')			? NVRAM_ApCliSsid			: 'Wive-NG-MT';
var NVRAM_ApCliBssid				= '<% getCfgGeneral(1, "ApCliBssid"); %>';			NVRAM_ApCliBssid			= (NVRAM_ApCliBssid != '')			? NVRAM_ApCliBssid			: '';
var NVRAM_ApCliAuthMode				= '<% getCfgGeneral(1, "ApCliAuthMode"); %>';			NVRAM_ApCliAuthMode			= (NVRAM_ApCliAuthMode != '')			? NVRAM_ApCliAuthMode			: 'WPA2PSK';
var NVRAM_ApCliAutoConnect			= '<% getCfgGeneral(1, "ApCliAutoConnect"); %>';		NVRAM_ApCliAutoConnect			= (NVRAM_ApCliAutoConnect != '')		? NVRAM_ApCliAutoConnect		: '1';
var NVRAM_ApCliClientOnly			= '<% getCfgGeneral(1, "ApCliClientOnly"); %>';			NVRAM_ApCliClientOnly			= (NVRAM_ApCliClientOnly != '')			? NVRAM_ApCliClientOnly			: '0';
var NVRAM_ApCliBridgeOnly			= '<% getCfgGeneral(1, "ApCliBridgeOnly"); %>';			NVRAM_ApCliBridgeOnly			= (NVRAM_ApCliBridgeOnly != '')			? NVRAM_ApCliBridgeOnly			: '0';
var NVRAM_ApCliWPAPSK				= '<% getCfgGeneral(1, "ApCliWPAPSK"); %>';			NVRAM_ApCliWPAPSK			= (NVRAM_ApCliWPAPSK != '')			? NVRAM_ApCliWPAPSK			: '';
var NVRAM_ApCliIfName				= '<% getCfgGeneral(1, "ApCliIfName"); %>';			NVRAM_ApCliIfName			= (NVRAM_ApCliIfName != '')			? NVRAM_ApCliIfName			: 'apcli0';
var NVRAM_TmpBlockAfterKick			= '<% getCfgGeneral(1, "TmpBlockAfterKick"); %>';		NVRAM_TmpBlockAfterKick			= (NVRAM_TmpBlockAfterKick != '')		? NVRAM_TmpBlockAfterKick		: '14';
var NVRAM_KickStaRssiLowFT			= '<% getCfgGeneral(1, "KickStaRssiLowFT"); %>';		NVRAM_KickStaRssiLowFT			= (NVRAM_KickStaRssiLowFT != '')		? NVRAM_KickStaRssiLowFT		: '0';
var NVRAM_RegulatoryClass			= '<% getCfgGeneral(1, "RegulatoryClass"); %>';			NVRAM_RegulatoryClass			= (NVRAM_RegulatoryClass != '')			? NVRAM_RegulatoryClass			: '5;0;0;0;0';
var NVRAM_RegulatoryClassINIC			= '<% getCfgGeneral(1, "RegulatoryClassINIC"); %>';		NVRAM_RegulatoryClassINIC		= (NVRAM_RegulatoryClassINIC != '')		? NVRAM_RegulatoryClassINIC		: '1;2;3;4;0';
