/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_ZLIB
#undef  CONFIG_LIB_USB1
#define CONFIG_LIB_EVENT 1
#undef  CONFIG_LIB_CURL
#undef  CONFIG_LIB_PCAP
#undef  CONFIG_LIB_NATPMP
#define CONFIG_LIB_NFNETLINK 1
#undef  CONFIG_LIB_NL
#undef  CONFIG_LIB_OPENSSL
#undef  CONFIG_LIB_ICONV
#undef  CONFIG_LIB_XML2
#undef  CONFIG_LIB_NEON

/*
 * Network Applications
 */
#define CONFIG_USER_GOAHEAD_HTTPD 1
#undef  CONFIG_USER_GOAHEAD_IPV6
#undef  CONFIG_USER_GOAHEAD_SSL
#define CONFIG_USER_GOAHEAD_HOSTNAME 1
#define CONFIG_USER_GOAHEAD_LANG_RU 1
#undef  CONFIG_USER_IRQBALANCE
#define CONFIG_USER_DNSMASQ 1
#undef  CONFIG_USER_NTFS3G
#undef  CONFIG_USER_DAVFS
#define CONFIG_USER_SAMBA 1
#undef  CONFIG_USER_TRANSMISSION
#undef  CONFIG_USER_STORAGE
#define CONFIG_USER_IGMP_PROXY 1
#define CONFIG_USER_UDPXY 1
#define CONFIG_USER_WIVE 1
#define CONFIG_USER_KABINET 1
#define CONFIG_USER_INADYN 1
#define CONFIG_USER_IPTABLES_IPTABLES 1
#undef  CONFIG_USER_IPTABLES_SAVE_RESTORE
#define CONFIG_USER_IPTABLES_IP6TABLES 1
#define CONFIG_USER_DROPBEAR 1
#undef  CONFIG_USER_P910ND
#define CONFIG_USER_PPPD 1
#undef  CONFIG_USER_PPPD_CHAT
#define CONFIG_USER_XL2TPD 1
#define CONFIG_USER_PARPROUTED 1
#define CONFIG_USER_ZEBRA 1
#define CONFIG_USER_SNMPD 1
#define CONFIG_USER_MINIUPNPD 1
#define CONFIG_USER_XUPNPD 1
#define CONFIG_USER_RADVD 1
#define CONFIG_USER_DHCP6 1
#define CONFIG_USER_DHCP6_SERVER 1
#define CONFIG_USER_DHCP6_CLIENT 1
#define CONFIG_USER_CDP 1
#define CONFIG_USER_LLTD 1
#define CONFIG_USER_LLDPD 1
#undef  CONFIG_USER_WPA_SUPPLICANT
#define CONFIG_USER_WIRELESS_TOOLS 1
#undef  CONFIG_USER_WIRELESS_IW_TOOL
#define CONFIG_LIB_EVENT 1

/*
 * Miscellaneous Applications
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1
#define CONFIG_USER_ETHTOOL 1
#undef  CONFIG_USER_TCPDUMP

/*
 * Ralink RT288x Application
 */
#define CONFIG_RT2880_APP 1
#undef  CONFIG_RT2880_REG_RW
#define CONFIG_RT2880_MII_MGR 1
#define CONFIG_RT2880_NVRAM 1
#define CONFIG_RT2880_MTD 1
#define CONFIG_ETHMAC_TOOL 1
#define CONFIG_RT2880_GPIO_TEST 1
#define CONFIG_RALINKAPP_HWNAT 1
#undef  CONFIG_RALINKAPP_ATED
#undef  CONFIG_RALINKAPP_HWNAT_AC
#undef  CONFIG_RALINKAPP_HWNAT_ACL
#undef  CONFIG_RALINKAPP_HWNAT_MTR
#define CONFIG_USER_IPROUTE2 1
#define CONFIG_USER_IPROUTE2_IP 1
#define CONFIG_USER_IPROUTE2_TC 1
#define CONFIG_RTESW_SWITCH 1
#define CONFIG_RALINKAPP_SWQOS 1

/*
 * 3G support
 */
#undef  CONFIG_USB_MODESWITCH

/*
 * Optimization options.
 */
#undef  CONFIG_LIB_SMALLSIZE
#undef  CONFIG_USER_SMALLSIZE
#undef  CONFIG_LIB_SAVERAM
#undef  CONFIG_USER_SAVERAM
