/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux sfstudio.sadnet.lo 4.2.3 #32 SMP PREEMPT Sat Oct 3 19:34:27 OMST 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "Fri Oct 23 02:56:53 OMST 2015"
#define BUILD_ENV_SRCDIR "/opt/Wive-MT/user/samba/source"
#define BUILD_ENV_BUILDDIR "/opt/Wive-MT/user/samba/source"
#define BUILD_ENV_USER "sfstudio"
#define BUILD_ENV_HOST "sfstudio.sadnet.lo"
#define BUILD_ENV_COMPILER "/opt/Wive-MT/toolchain/bin/mipsel-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
