#ifndef __WIRELESS_H__
#define __WIRELESS_H__

#include "asp_mod_helpers.h"

typedef struct country_code_t
{
	const char *iso;
	const char *name;
} country_code_t;


static const country_code_t country_codes[] =
{
	{ "AL", "ALBANIA" },
	{ "DZ", "ALGERIA" },
	{ "AR", "ARGENTINA" },
	{ "AM", "ARMENIA" },
	{ "AU", "AUSTRALIA" },
	{ "AT", "AUSTRIA" },
	{ "AZ", "AZERBAIJAN" },
	{ "BH", "BAHRAIN" },
	{ "BY", "BELARUS" },
	{ "BE", "BELGIUM" },
	{ "BZ", "BELIZE" },
	{ "BO", "BOLIVIA" },
	{ "BR", "BRAZIL" },
	{ "BN", "BRUNEI DARUSSALAM" },
	{ "BG", "BULGARIA" },
	{ "CA", "CANADA" },
	{ "CL", "CHILE" },
	{ "CN", "CHINA" },
	{ "CO", "COLOMBIA" },
	{ "CR", "COSTA RICA" },
	{ "HR", "CROATIA" },
	{ "CY", "CYPRUS" },
	{ "CZ", "CZECH REPUBLIC" },
	{ "DK", "DENMARK" },
	{ "DO", "DOMINICAN REPUBLIC" },
	{ "EC", "ECUADOR" },
	{ "EG", "EGYPT" },
	{ "SV", "EL SALVADOR" },
	{ "EE", "ESTONIA" },
	{ "FI", "FINLAND" },
	{ "FR", "FRANCE" },
	{ "GE", "GEORGIA" },
	{ "DE", "GERMANY" },
	{ "GR", "GREECE" },
	{ "GT", "GUATEMALA" },
	{ "HN", "HONDURAS" },
	{ "HK", "HONG KONG" },
	{ "HU", "HUNGARY" },
	{ "IS", "ICELAND" },
	{ "IN", "INDIA" },
	{ "ID", "INDONESIA" },
	{ "IR", "IRAN" },
	{ "IE", "IRELAND" },
	{ "IL", "ISRAEL" },
	{ "IT", "ITALY" },
	{ "JP", "JAPAN" },
	{ "JO", "JORDAN" },
	{ "KZ", "KAZAKHSTAN" },
	{ "KP", "KOREA DEMOCRATIC PEOPLE'S REPUBLIC OF" },
	{ "KR", "KOREA REPUBLIC OF" },
	{ "KW", "KUWAIT" },
	{ "LV", "LATVIA" },
	{ "LB", "LEBANON" },
	{ "LI", "LIECHTENSTEIN" },
	{ "LT", "LITHUANIA" },
	{ "LU", "LUXEMBOURG" },
	{ "MO", "MACAU" },
	{ "MK", "MACEDONIA" },
	{ "MY", "MALAYSIA" },
	{ "MX", "MEXICO" },
	{ "MC", "MONACO" },
	{ "MA", "MOROCCO" },
	{ "NL", "NETHERLANDS" },
	{ "NZ", "NEW ZEALAND" },
	{ "NO", "NORWAY" },
	{ "OM", "OMAN" },
	{ "PK", "PAKISTAN" },
	{ "PA", "PANAMA" },
	{ "PE", "PERU" },
	{ "PH", "PHILIPPINES" },
	{ "PL", "POLAND" },
	{ "PT", "PORTUGAL" },
	{ "PR", "PUERTO RICO" },
	{ "QA", "QATAR" },
	{ "RO", "ROMANIA" },
	{ "RU", "RUSSIAN FEDERATION" },
	{ "SA", "SAUDI ARABIA" },
	{ "SG", "SINGAPORE" },
	{ "SK", "SLOVAKIA" },
	{ "SI", "SLOVENIA" },
	{ "ZA", "SOUTH AFRICA" },
	{ "ES", "SPAIN" },
	{ "SE", "SWEDEN" },
	{ "CH", "SWITZERLAND" },
	{ "SY", "SYRIAN ARAB REPUBLIC" },
	{ "TW", "TAIWAN" },
	{ "TH", "THAILAND" },
	{ "TT", "TRINIDAD AND TOBAGO" },
	{ "TN", "TUNISIA" },
	{ "TR", "TURKEY" },
	{ "UA", "UKRAINE" },
	{ "AE", "UNITED ARAB EMIRATES" },
	{ "GB", "UNITED KINGDOM" },
	{ "US", "UNITED STATES" },
	{ "UY", "URUGUAY" },
	{ "UZ", "UZBEKISTAN" },
	{ "VE", "VENEZUELA" },
	{ "VN", "VIET NAM" },
	{ "YE", "YEMEN" },
	{ "ZW", "ZIMBABWE" },
	{ NULL, NULL }
};

int asp_mod_wireless_init();

#endif // __WIRELESS_H__